'use client';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { TxActionsContext } from '@/components/tx-actions';
import { UndoDeleteProvider, useUndoDelete } from '@/components/undo-delete';
import { HubTabs, hubByKey, hubOf, hubs } from '@/components/hubs';
import { useBackGuard } from '@/components/back-guard';
import { Emoji } from '@/components/emoji';
import { useRouter } from 'next/navigation';
import { BarChart3, BookOpenText, CalendarDays, CalendarClock, ChartNoAxesCombined, CreditCard, HandCoins, HeartPulse, Home, Inbox, Layers3, LayoutGrid, ListFilter, Plus, Repeat, ScrollText, Settings, ShieldCheck, Sparkles, Target, Wallet } from 'lucide-react';
import { useApp } from '@/components/app-provider';
import dynamic from 'next/dynamic';
// Every page except Beranda is its own download, fetched when first opened (and warmed up in the background).
const viewLoading = () => <div className="view-skeleton" aria-busy="true" aria-label="Memuat halaman"><span/><span/><span/></div>;
const pages = {
  insights: () => import('@/components/insights'), reports: () => import('@/components/reports'), manage: () => import('@/components/manage-views'),
  receivables: () => import('@/components/receivables-refined'), budgets: () => import('@/components/budgets-refined'), identity: () => import('@/components/identity-views'),
  settings: () => import('@/components/settings'), inbox: () => import('@/components/transaction-inbox'), recurring: () => import('@/components/recurring-control'),
  planning: () => import('@/components/financial-planning'), control: () => import('@/components/financial-control-views'),
};
const ForecastView = dynamic(() => pages.insights().then(m => m.ForecastView), { loading: viewLoading });
const AnalyticsView = dynamic(() => pages.reports().then(m => m.AnalyticsView), { loading: viewLoading });
const ReportView = dynamic(() => pages.reports().then(m => m.ReportView), { loading: viewLoading });
const TransactionsView = dynamic(() => pages.manage().then(m => m.TransactionsView), { loading: viewLoading });
const ClaimsView = dynamic(() => pages.manage().then(m => m.ClaimsView), { loading: viewLoading });
const DebtsView = dynamic(() => pages.manage().then(m => m.DebtsView), { loading: viewLoading });
const FundsView = dynamic(() => pages.manage().then(m => m.FundsView), { loading: viewLoading });
const ReceivablesView = dynamic(() => pages.receivables().then(m => m.ReceivablesView), { loading: viewLoading });
const BudgetsView = dynamic(() => pages.budgets().then(m => m.BudgetsView), { loading: viewLoading });
const CategoriesView = dynamic(() => pages.identity().then(m => m.CategoriesView), { loading: viewLoading });
const WalletsView = dynamic(() => pages.identity().then(m => m.WalletsView), { loading: viewLoading });
const SettingsView = dynamic(() => pages.settings().then(m => m.SettingsView), { loading: viewLoading });
const TransactionInbox = dynamic(() => pages.inbox().then(m => m.TransactionInbox), { loading: viewLoading });
const RecurringControl = dynamic(() => pages.recurring().then(m => m.RecurringControl), { loading: viewLoading });
const FinancialCalendar = dynamic(() => pages.planning().then(m => m.FinancialCalendar), { loading: viewLoading });
const UpcomingView = dynamic(() => pages.planning().then(m => m.UpcomingView), { loading: viewLoading });
const CycleHistory = dynamic(() => pages.control().then(m => m.CycleHistory), { loading: viewLoading });
const DataHealth = dynamic(() => pages.control().then(m => m.DataHealth), { loading: viewLoading });
import { Dashboard } from '@/components/dashboard-home';
import { Sidebar } from '@/components/sidebar';
import { MobileNavigation } from '@/components/mobile-navigation';
import { TransactionForm } from '@/components/transaction-form';
import { isCycleClosed } from '@/lib/finance-control';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent } from '@/components/ui/dialog';
import { Confirm } from '@/components/ui/alert-dialog';
import { Field, Input, Money } from '@/components/fields';
import { saveProfile, saveWallet, deleteTransaction, seedCategoryTemplates } from '@/lib/firestore';
import { categoryTemplates, planTemplateSeed, presetHex } from '@/lib/category-templates';
import { TemplateChecklist } from '@/components/category-template-picker';
import { NotificationBell, NotificationProvider, useNotify } from '@/components/notifications';
import { PinLockScreen, useAppLock } from '@/components/pin-lock';
import { useReminderEngine } from '@/components/reminders';
import type { LedgerTx } from '@/lib/types';
const nav=[{key:'dashboard',label:'Beranda',icon:Home},{key:'transactions',label:'Transaksi',icon:ListFilter},{key:'inbox',label:'Perlu Dikonfirmasi',icon:Inbox},{key:'budgets',label:'Anggaran',icon:LayoutGrid},{key:'wallets',label:'Dompet',icon:Wallet},{key:'claims',label:'Klaim kantor',icon:ShieldCheck},{key:'receivables',label:'Piutang',icon:HandCoins},{key:'debts',label:'Utang',icon:CreditCard},{key:'funds',label:'Tujuan dana',icon:Target},{key:'recurring',label:'Rutin',icon:Repeat},{key:'upcoming',label:'Arus Kas Mendatang',icon:CalendarClock},{key:'calendar',label:'Kalender Keuangan',icon:CalendarDays},{key:'categories',label:'Kategori',icon:Layers3},{key:'forecast',label:'Proyeksi',icon:ChartNoAxesCombined},{key:'analytics',label:'Analisis',icon:BarChart3},{key:'report',label:'Laporan',icon:BookOpenText},{key:'cycles',label:'Riwayat Siklus',icon:ScrollText},{key:'health',label:'Periksa Data',icon:HeartPulse},{key:'settings',label:'Pengaturan',icon:Settings}];
/** What the sidebar and the phone menu show: related pages are grouped into hubs with tabs. */
const menu=[...['dashboard','transactions','budgets'].map(key=>({...nav.find(item=>item.key===key)!})),{...nav.find(item=>item.key==='wallets')!,section:'KEUANGAN'},{...nav.find(item=>item.key==='funds')!},...hubs.filter(hub=>hub.key!=='reports').map(hub=>({key:hub.key,label:hub.label,icon:hub.icon})),{key:'reports',label:'Laporan',icon:BookOpenText,section:'LAPORAN'},{...nav.find(item=>item.key==='categories')!,section:'LAINNYA'},{...nav.find(item=>item.key==='settings')!}];
function Onboarding({notify}:{notify:(s:string)=>void}){const {user,profile,data}=useApp();const [name,setName]=useState(profile?.displayName||''),[day,setDay]=useState(24),[salary,setSalary]=useState(0),[wallets,setWallets]=useState(true),[cash,setCash]=useState(0),[bank,setBank]=useState(0),[choice,setChoice]=useState<'default'|'pick'|'empty'>('default'),[picked,setPicked]=useState<string[]>(()=>categoryTemplates.map(t=>t.key)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function finish(e?:FormEvent,skip=false){e?.preventDefault();if(!user)return;const salaryDay=Math.min(31,Math.max(1,Math.round(day)||24));setBusy(true);setError('');try{
  if(!skip&&wallets){if(!data.wallets.some(w=>w.type==='cash'))await saveWallet(user.uid,{name:'Tunai',type:'cash',openingBalance:cash,icon:'💵',color:presetHex('green'),displayOrder:0});if(!data.wallets.some(w=>w.type==='bank'))await saveWallet(user.uid,{name:'Bank',type:'bank',openingBalance:bank,icon:'🏦',color:presetHex('blue'),displayOrder:1});}
  const keys=skip||choice==='empty'?[]:choice==='default'?categoryTemplates.map(t=>t.key):picked;
  const records=planTemplateSeed(data.categories,keys);
  if(records.length)await seedCategoryTemplates(user.uid,records);
  const gaji=records.find(r=>r.data.templateKey==='income.gaji');
  await saveProfile(user.uid,{displayName:name.trim()||profile?.username||'',salaryCycleStartDay:salaryDay,monthlySalary:salary,onboardingDone:true,...(gaji?{salaryIncomeCategoryId:gaji.id}:{})});notify('Akun siap dipakai.');}catch(e){setError((e as Error).message||'Pengaturan awal gagal.');}finally{setBusy(false);}}
 const choices:[typeof choice,string,string][]=[['default','Pakai kategori bawaan','Kami sudah menyiapkan kategori umum. Semuanya bisa diubah kapan saja.'],['pick','Pilih sendiri','Centang kategori yang ingin dipakai.'],['empty','Mulai dari kosong','Buat kategori sendiri nanti.']];
 return <main className="onboarding"><div className="panel"><div className="brand" style={{color:'var(--ink)'}}><span className="brand-mark"><Sparkles size={20}/></span><strong>dompet ajaib<span className="brand-dot">.</span></strong></div><h1>Siapkan Dompet Ajaib</h1><p>Beberapa langkah singkat. Semua bisa diubah kapan saja.</p><form className="form-stack" onSubmit={e=>void finish(e)}>
  <section className="onboarding-step"><h3>1 · Profil</h3><div className="form-grid"><Field label="Nama panggilan"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Nama yang ingin ditampilkan"/></Field><Field label="Tanggal gajian"><Input type="number" inputMode="numeric" min="1" max="31" value={day} onChange={e=>setDay(Number(e.target.value))}/></Field><Field label="Perkiraan gaji bulanan"><Money value={salary} onChange={setSalary}/></Field></div></section>
  <section className="onboarding-step"><h3>2 · Dompet</h3><label className="check-row"><input type="checkbox" checked={wallets} onChange={e=>setWallets(e.target.checked)}/> Buat dompet Tunai <Emoji e="💵"/> dan Bank <Emoji e="🏦"/></label>{wallets&&<div className="form-grid"><Field label="Saldo Tunai sekarang"><Money value={cash} onChange={setCash}/></Field><Field label="Saldo Bank sekarang"><Money value={bank} onChange={setBank}/></Field></div>}<small>Dompet lain (e-wallet, tabungan) bisa ditambah nanti di menu Dompet.</small></section>
  <section className="onboarding-step"><h3>3 · Kategori</h3><p className="muted">Pakai kategori yang sudah disiapkan?</p><div className="choice-cards" role="radiogroup" aria-label="Pilihan kategori">{choices.map(([value,title,text])=><label key={value} className={`choice-card ${choice===value?'is-selected':''}`}><input type="radio" name="category-choice" checked={choice===value} onChange={()=>setChoice(value)}/><span><strong>{title}{value==='default'&&<em className="tag">Disarankan</em>}</strong><small>{text}</small></span></label>)}</div>
   {choice==='pick'&&<TemplateChecklist selected={picked} onChange={setPicked}/>}</section>
  {error&&<p className="form-error">{error}</p>}<div className="modal-actions"><Button type="button" variant="secondary" disabled={busy} onClick={()=>void finish(undefined,true)}>Lewati dulu</Button><Button disabled={busy||(choice==='pick'&&!picked.length)}>{busy?'Menyiapkan…':'Simpan & mulai'}</Button></div></form></div></main>;
}
export default function Page(){return <NotificationProvider><UndoDeleteProvider><AppPage/></UndoDeleteProvider></NotificationProvider>}
function AppPage(){const {user,profile,data,loading,error,ready,sync}=useApp();const {notify:setToast,track,push}=useNotify();const undo=useUndoDelete();const appLock=useAppLock();const router=useRouter(),[view,setView]=useState('dashboard'),[txOpen,setTxOpen]=useState(false),[preset,setPreset]=useState<Partial<LedgerTx>|undefined>(),[editing,setEditing]=useState<LedgerTx|undefined>(),[focus,setFocus]=useState<string|undefined>(),[revision,setRevision]=useState(0),[online,setOnline]=useState(true);
 const trail=useRef<string[]>([]),viewRef=useRef(view),lastTab=useRef<Record<string,string>>({});viewRef.current=view;
 // Back button: previous page first, then Beranda, then "press again to exit".
 useBackGuard(()=>{const previous=trail.current.pop();if(previous!==undefined){setFocus(undefined);setView(previous);return true}if(viewRef.current!=='dashboard'){setFocus(undefined);setView('dashboard');return true}return false},()=>push({title:'Tekan kembali sekali lagi untuk keluar',kind:'info',history:false}));
 useEffect(()=>{if(!loading&&!user&&ready)router.replace('/login/');},[loading,user,ready,router]);
 useEffect(()=>{if(!user)return;const warm=()=>Object.values(pages).forEach(load=>void load().catch(()=>{}));const idle=(window as Window&{requestIdleCallback?:(cb:()=>void)=>number}).requestIdleCallback;const id=idle?idle(warm):window.setTimeout(warm,2500);return()=>{if(!idle)clearTimeout(id)}},[user?.uid]);
 useEffect(()=>{if(!profile?.onboardingDone)return;const params=new URLSearchParams(window.location.search),action=params.get('action'),target=params.get('view');if(!action&&!target)return;if(target&&nav.some(item=>item.key===target))setView(target);if(action==='expense'||action==='income'||action==='transfer')openTx({type:action});window.history.replaceState(window.history.state,'',window.location.pathname)},[profile?.onboardingDone]);useEffect(()=>{setOnline(navigator.onLine);const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off)}},[]);useEffect(()=>{const close=(event:Event)=>{const target=event.target instanceof Element?event.target:null;document.querySelectorAll<HTMLDetailsElement>('details.more-actions[open]').forEach(menu=>{if(!target||!menu.contains(target)||target.closest('.more-menu button'))menu.open=false})};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')document.querySelectorAll<HTMLDetailsElement>('details.more-actions[open]').forEach(menu=>{menu.open=false})};document.addEventListener('click',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('click',close);document.removeEventListener('keydown',escape)}},[]);
 function openTx(p?:Partial<LedgerTx>,e?:LedgerTx){setPreset(p);setEditing(e);setTxOpen(true)}
 /** Deletes with a few seconds to undo; opening records of debts/claims/receivables are changed through their record instead. */
 const txActions={remove:(tx:LedgerTx)=>removeTx(tx),edit:(tx:LedgerTx)=>openTx(undefined,tx)};
 function removeTx(tx:LedgerTx){if(!user)return;if(['claim_advance','receivable_issue','borrowing'].includes(tx.type)){openTx(undefined,tx);return}const uid=user.uid;undo.remove(tx.id,'Transaksi',()=>deleteTransaction(uid,tx.id).then(()=>setRevision(n=>n+1)))}
 /** Saves in the background: the form closes at once and a card shows the sync progress. */
 function saveInBackground(run:()=>Promise<unknown>,info:{message:string;retry:{preset?:Partial<LedgerTx>;editing?:LedgerTx}}){setTxOpen(false);track(run(),{pending:info.retry.editing?'Memperbarui transaksi…':'Menyimpan transaksi…',success:info.message,failure:'Transaksi belum tersimpan',retry:{label:'Buka lagi',run:()=>openTx(info.retry.preset,info.retry.editing)},after:()=>setRevision(n=>n+1)})}const go=(requested:string,target?:string)=>{const hub=hubByKey(requested),key=hub?(lastTab.current[hub.key]||hub.tabs[0][0]):requested;if(key==='dashboard')trail.current=[];else if(key!==view){trail.current.push(view);if(trail.current.length>30)trail.current.shift()}setFocus(target);setView(key);const inHub=hubOf(key);if(inHub)lastTab.current[inHub.key]=key;window.scrollTo({top:0,behavior:'smooth'})};const selectTab=(key:string)=>{const inHub=hubOf(key);if(inHub)lastTab.current[inHub.key]=key;setFocus(undefined);setView(key)};const props={notify:setToast,openTx,revision};
 useReminderEngine(go);
 if(!ready)return <main className="loading-screen"><div className="panel"><h2>Dompet Ajaib belum terhubung</h2><p className="muted" style={{marginTop:8}}>Isi konfigurasi Firebase pada berkas .env.local sesuai panduan proyek, lalu jalankan ulang aplikasi.</p></div></main>;
 if(!loading&&user&&!profile&&error)return <main className="loading-screen"><div className="panel"><h2>Catatan keuangan belum bisa dibuka</h2><p className="form-error" style={{marginTop:12}}>{error}</p><p className="muted" style={{marginTop:12}}>Jika baru membuat link percobaan, buka Firebase Console → Firestore Database → Rules dan pastikan akunmu diberi akses ke datanya sendiri.</p><Button style={{marginTop:16}} onClick={()=>window.location.reload()}>Coba lagi</Button></div></main>;
 if(loading||!user||!profile)return <div className="loading-screen"><div><div className="spinner"/>Menyiapkan catatan keuangan…{error&&<p className="form-error">{error}</p>}</div></div>;
 if(!profile.onboardingDone)return <Onboarding notify={setToast}/>;
 if(appLock.locked)return <PinLockScreen onUnlock={appLock.unlock}/>;
 const views:Record<string,React.ReactNode>={dashboard:<Dashboard openTx={openTx} navigate={go} notify={setToast}/>,transactions:<TransactionsView {...props} focus={focus}/>,inbox:<TransactionInbox openTx={openTx} notify={setToast}/>,budgets:<BudgetsView {...props} navigate={go}/>,wallets:<WalletsView {...props} focus={focus} navigate={go}/>,claims:<ClaimsView {...props}/>,receivables:<ReceivablesView {...props}/>,debts:<DebtsView {...props}/>,funds:<FundsView {...props}/>,recurring:<RecurringControl notify={setToast} navigateInbox={()=>go('inbox')}/>,upcoming:<UpcomingView openTx={openTx} notify={setToast}/>,calendar:<FinancialCalendar notify={setToast}/>,categories:<CategoriesView {...props}/>,forecast:<ForecastView/>,analytics:<AnalyticsView navigate={go}/>,report:<ReportView navigate={go}/>,cycles:<CycleHistory notify={setToast}/>,health:<DataHealth notify={setToast}/>,settings:<SettingsView notify={setToast} navigate={go} onLockNow={appLock.enabled?appLock.lock:undefined}/>};
 return <div className="app-layout"><Sidebar items={menu} view={view} onNavigate={go}/><div className="main-area"><header className="topbar"><div className="topbar-title">{hubOf(view)?.label||nav.find(item=>item.key===view)?.label||'Dompet Ajaib'}</div><div className="topbar-actions"><NotificationBell navigate={go}/><span className={`status-pill ${online&&sync!=='offline'&&sync!=='error'?'':'offline'}`}><i/>{online?(sync==='syncing'?'Menyinkron…':sync==='error'?'Gagal sinkron':sync==='offline'?'Data tersimpan lokal':'Tersinkron'):'Offline'}</span><Button className="small" aria-label="Catat transaksi" title="Catat transaksi" onClick={()=>openTx()}><Plus size={16}/><span className="btn-label">Catat transaksi</span></Button></div></header><TxActionsContext.Provider value={txActions}><main className="content">{error&&<div className="notice error">Koneksi data bermasalah: {error}</div>}<HubTabs view={view} onSelect={selectTab}/><div key={`${view}:${focus||''}`} className="view-enter">{views[view]}</div></main></TxActionsContext.Provider></div><MobileNavigation view={view} items={menu} onNavigate={go} openTx={openTx}/><Dialog open={txOpen} onOpenChange={setTxOpen}><DialogContent title={editing?'Ubah transaksi':'Catat transaksi'}>{editing&&!['claim_advance','receivable_issue','borrowing'].includes(editing.type)&&<Button variant="danger" className="full" style={{marginBottom:15}} onClick={()=>{setTxOpen(false);removeTx(editing)}}>Hapus transaksi</Button>}{editing&&isCycleClosed(editing.date,data.cycleSnapshots||[])&&<div className="notice">Transaksi ini berada dalam siklus yang sudah ditutup. Penghapusan akan menghitung ulang laporan siklus.</div>}{editing&&['claim_advance','receivable_issue','borrowing','claim_writeoff'].includes(editing.type)&&<div className="notice">Transaksi ini dibuat otomatis dari catatan utang, klaim, atau piutang, jadi ubah lewat catatan tersebut. Untuk klaim yang ditolak, hapus transaksi penolakannya lalu catat ulang.</div>}<TransactionForm key={editing?.id||JSON.stringify(preset)||'new'} preset={preset} editing={editing} background={saveInBackground} onDone={m=>{setTxOpen(false);setRevision(n=>n+1);setToast(m)}} onCancel={()=>setTxOpen(false)}/></DialogContent></Dialog></div>;
}
