'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { BarChart3, BookOpenText, CalendarDays, CalendarClock, ChartNoAxesCombined, CreditCard, HandCoins, HeartPulse, Home, Inbox, Layers3, LayoutGrid, ListFilter, Plus, Repeat, ScrollText, Settings, ShieldCheck, Sparkles, Target, Wallet } from 'lucide-react';
import { useApp } from '@/components/app-provider';
import { Dashboard } from '@/components/dashboard-home';
import { Sidebar } from '@/components/sidebar';
import { MobileNavigation } from '@/components/mobile-navigation';
import { ForecastView } from '@/components/insights';
import { AnalyticsView, ReportView } from '@/components/reports';
import { ClaimsView, DebtsView, FundsView, TransactionsView } from '@/components/manage-views';
import { ReceivablesView } from '@/components/receivables-refined';
import { BudgetsView } from '@/components/budgets-refined';
import { CategoriesView, WalletsView } from '@/components/identity-views';
import { SettingsView } from '@/components/settings';
import { TransactionForm } from '@/components/transaction-form';
import { TransactionInbox } from '@/components/transaction-inbox';
import { RecurringControl } from '@/components/recurring-control';
import { FinancialCalendar, UpcomingView } from '@/components/financial-planning';
import { CycleHistory, DataHealth } from '@/components/financial-control-views';
import { isCycleClosed } from '@/lib/finance-control';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent } from '@/components/ui/dialog';
import { Confirm } from '@/components/ui/alert-dialog';
import { Field, Input, Money } from '@/components/fields';
import { saveProfile, saveWallet, deleteTransaction, seedCategoryTemplates } from '@/lib/firestore';
import { categoryTemplates, planTemplateSeed, presetHex } from '@/lib/category-templates';
import { TemplateChecklist } from '@/components/category-template-picker';
import { NotificationBell, NotificationProvider, useNotify } from '@/components/notifications';
import { PinLockScreen, useAppLock } from '@/components/pin-lock';
import { useReminderEngine } from '@/components/reminders';
import type { LedgerTx } from '@/lib/types';
const nav=[{key:'dashboard',label:'Beranda',icon:Home},{key:'transactions',label:'Transaksi',icon:ListFilter},{key:'inbox',label:'Perlu Dikonfirmasi',icon:Inbox},{key:'budgets',label:'Anggaran',icon:LayoutGrid},{key:'wallets',label:'Dompet',icon:Wallet},{key:'claims',label:'Klaim kantor',icon:ShieldCheck},{key:'receivables',label:'Piutang',icon:HandCoins},{key:'debts',label:'Utang',icon:CreditCard},{key:'funds',label:'Tujuan dana',icon:Target},{key:'recurring',label:'Rutin',icon:Repeat},{key:'upcoming',label:'Arus Kas Mendatang',icon:CalendarClock},{key:'calendar',label:'Kalender Keuangan',icon:CalendarDays},{key:'categories',label:'Kategori',icon:Layers3},{key:'forecast',label:'Proyeksi',icon:ChartNoAxesCombined},{key:'analytics',label:'Analisis',icon:BarChart3},{key:'report',label:'Laporan',icon:BookOpenText},{key:'cycles',label:'Riwayat Siklus',icon:ScrollText},{key:'health',label:'Periksa Data',icon:HeartPulse},{key:'settings',label:'Pengaturan',icon:Settings}];
function Onboarding({notify}:{notify:(s:string)=>void}){const {user,profile,data}=useApp();const [name,setName]=useState(profile?.displayName||''),[day,setDay]=useState(24),[salary,setSalary]=useState(0),[wallets,setWallets]=useState(true),[cash,setCash]=useState(0),[bank,setBank]=useState(0),[choice,setChoice]=useState<'default'|'pick'|'empty'>('default'),[picked,setPicked]=useState<string[]>(()=>categoryTemplates.map(t=>t.key)),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function finish(e?:FormEvent,skip=false){e?.preventDefault();if(!user)return;const salaryDay=Math.min(31,Math.max(1,Math.round(day)||24));setBusy(true);setError('');try{
  if(!skip&&wallets){if(!data.wallets.some(w=>w.type==='cash'))await saveWallet(user.uid,{name:'Tunai',type:'cash',openingBalance:cash,icon:'💵',color:presetHex('green'),displayOrder:0});if(!data.wallets.some(w=>w.type==='bank'))await saveWallet(user.uid,{name:'Bank',type:'bank',openingBalance:bank,icon:'🏦',color:presetHex('blue'),displayOrder:1});}
  const keys=skip||choice==='empty'?[]:choice==='default'?categoryTemplates.map(t=>t.key):picked;
  const records=planTemplateSeed(data.categories,keys);
  if(records.length)await seedCategoryTemplates(user.uid,records);
  const gaji=records.find(r=>r.data.templateKey==='income.gaji');
  await saveProfile(user.uid,{displayName:name.trim()||profile?.username||'',salaryCycleStartDay:salaryDay,monthlySalary:salary,onboardingDone:true,...(gaji?{salaryIncomeCategoryId:gaji.id}:{})});notify('Akun siap dipakai.');}catch(e){setError((e as Error).message||'Pengaturan awal gagal.');}finally{setBusy(false);}}
 const choices:[typeof choice,string,string][]=[['default','Gunakan Kategori Default','Kami sudah menyiapkan kategori umum. Semuanya bisa diubah kapan saja.'],['pick','Pilih Sendiri','Centang kategori yang ingin dipakai.'],['empty','Mulai dari Kosong','Buat kategori sendiri nanti.']];
 return <main className="onboarding"><div className="panel"><div className="brand" style={{color:'var(--ink)'}}><span className="brand-mark"><Sparkles size={20}/></span><strong>dompet ajaib<span className="brand-dot">.</span></strong></div><h1>Atur ruang uangmu</h1><p>Beberapa langkah singkat. Semua bisa diubah kapan saja.</p><form className="form-stack" onSubmit={e=>void finish(e)}>
  <section className="onboarding-step"><h3>1 · Profil</h3><div className="form-grid"><Field label="Nama panggilan"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Nama yang ingin ditampilkan"/></Field><Field label="Tanggal gajian"><Input type="number" inputMode="numeric" min="1" max="31" value={day} onChange={e=>setDay(Number(e.target.value))}/></Field><Field label="Perkiraan gaji bulanan"><Money value={salary} onChange={setSalary}/></Field></div></section>
  <section className="onboarding-step"><h3>2 · Dompet</h3><label className="check-row"><input type="checkbox" checked={wallets} onChange={e=>setWallets(e.target.checked)}/> Buat dompet Tunai 💵 dan Bank 🏦</label>{wallets&&<div className="form-grid"><Field label="Saldo Tunai sekarang"><Money value={cash} onChange={setCash}/></Field><Field label="Saldo Bank sekarang"><Money value={bank} onChange={setBank}/></Field></div>}<small>Dompet lain (e-wallet, tabungan) bisa ditambah nanti di menu Dompet.</small></section>
  <section className="onboarding-step"><h3>3 · Kategori</h3><p className="muted">Pakai kategori yang sudah disiapkan?</p><div className="choice-cards" role="radiogroup" aria-label="Pilihan kategori">{choices.map(([value,title,text])=><label key={value} className={`choice-card ${choice===value?'is-selected':''}`}><input type="radio" name="category-choice" checked={choice===value} onChange={()=>setChoice(value)}/><span><strong>{title}{value==='default'&&<em className="tag">Disarankan</em>}</strong><small>{text}</small></span></label>)}</div>
   {choice==='pick'&&<TemplateChecklist selected={picked} onChange={setPicked}/>}</section>
  {error&&<p className="form-error">{error}</p>}<div className="modal-actions"><Button type="button" variant="secondary" disabled={busy} onClick={()=>void finish(undefined,true)}>Lewati dulu</Button><Button disabled={busy||(choice==='pick'&&!picked.length)}>{busy?'Menyiapkan…':'Simpan & mulai'}</Button></div></form></div></main>;
}
export default function Page(){return <NotificationProvider><AppPage/></NotificationProvider>}
function AppPage(){const {user,profile,data,loading,error,ready,sync}=useApp();const {notify:setToast,track}=useNotify();const appLock=useAppLock();const router=useRouter(),[view,setView]=useState('dashboard'),[txOpen,setTxOpen]=useState(false),[preset,setPreset]=useState<Partial<LedgerTx>|undefined>(),[editing,setEditing]=useState<LedgerTx|undefined>(),[focus,setFocus]=useState<string|undefined>(),[revision,setRevision]=useState(0),[online,setOnline]=useState(true);
 useEffect(()=>{if(!loading&&!user&&ready)router.replace('/login/');},[loading,user,ready,router]);
 useEffect(()=>{if(!profile?.onboardingDone)return;const params=new URLSearchParams(window.location.search),action=params.get('action'),target=params.get('view');if(!action&&!target)return;if(target&&nav.some(item=>item.key===target))setView(target);if(action==='expense'||action==='income'||action==='transfer')openTx({type:action});window.history.replaceState(null,'',window.location.pathname)},[profile?.onboardingDone]);useEffect(()=>{setOnline(navigator.onLine);const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off)}},[]);useEffect(()=>{const close=(event:Event)=>{const target=event.target instanceof Element?event.target:null;document.querySelectorAll<HTMLDetailsElement>('details.more-actions[open]').forEach(menu=>{if(!target||!menu.contains(target)||target.closest('.more-menu button'))menu.open=false})};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')document.querySelectorAll<HTMLDetailsElement>('details.more-actions[open]').forEach(menu=>{menu.open=false})};document.addEventListener('click',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('click',close);document.removeEventListener('keydown',escape)}},[]);
 function openTx(p?:Partial<LedgerTx>,e?:LedgerTx){setPreset(p);setEditing(e);setTxOpen(true)}
 /** Saves in the background: the form closes at once and a card shows the sync progress. */
 function saveInBackground(run:()=>Promise<unknown>,info:{message:string;retry:{preset?:Partial<LedgerTx>;editing?:LedgerTx}}){setTxOpen(false);track(run(),{pending:info.retry.editing?'Memperbarui transaksi…':'Menyimpan transaksi…',success:info.message,failure:'Transaksi belum tersimpan',retry:{label:'Buka lagi',run:()=>openTx(info.retry.preset,info.retry.editing)},after:()=>setRevision(n=>n+1)})}const go=(key:string,target?:string)=>{setFocus(target);setView(key);window.scrollTo({top:0,behavior:'smooth'})};const props={notify:setToast,openTx,revision};
 useReminderEngine(go);
 if(!ready)return <main className="loading-screen"><div className="panel"><h2>Dompet Ajaib belum terhubung</h2><p className="muted" style={{marginTop:8}}>Isi konfigurasi Firebase pada berkas .env.local sesuai panduan proyek, lalu jalankan ulang aplikasi.</p></div></main>;
 if(!loading&&user&&!profile&&error)return <main className="loading-screen"><div className="panel"><h2>Catatan keuangan belum bisa dibuka</h2><p className="form-error" style={{marginTop:12}}>{error}</p><p className="muted" style={{marginTop:12}}>Jika baru membuat link percobaan, buka Firebase Console → Firestore Database → Rules dan pastikan akunmu diberi akses ke datanya sendiri.</p><Button style={{marginTop:16}} onClick={()=>window.location.reload()}>Coba lagi</Button></div></main>;
 if(loading||!user||!profile)return <div className="loading-screen"><div><div className="spinner"/>Menyiapkan catatan keuangan…{error&&<p className="form-error">{error}</p>}</div></div>;
 if(!profile.onboardingDone)return <Onboarding notify={setToast}/>;
 if(appLock.locked)return <PinLockScreen onUnlock={appLock.unlock}/>;
 const views:Record<string,React.ReactNode>={dashboard:<Dashboard openTx={openTx} navigate={go} notify={setToast}/>,transactions:<TransactionsView {...props} focus={focus}/>,inbox:<TransactionInbox openTx={openTx} notify={setToast}/>,budgets:<BudgetsView {...props}/>,wallets:<WalletsView {...props} focus={focus} navigate={go}/>,claims:<ClaimsView {...props}/>,receivables:<ReceivablesView {...props}/>,debts:<DebtsView {...props}/>,funds:<FundsView {...props}/>,recurring:<RecurringControl notify={setToast} navigateInbox={()=>go('inbox')}/>,upcoming:<UpcomingView openTx={openTx} notify={setToast}/>,calendar:<FinancialCalendar notify={setToast}/>,categories:<CategoriesView {...props}/>,forecast:<ForecastView/>,analytics:<AnalyticsView navigate={go}/>,report:<ReportView navigate={go}/>,cycles:<CycleHistory notify={setToast}/>,health:<DataHealth notify={setToast}/>,settings:<SettingsView notify={setToast} navigate={go} onLockNow={appLock.enabled?appLock.lock:undefined}/>};
 return <div className="app-layout"><Sidebar items={nav} view={view} onNavigate={go}/><div className="main-area"><header className="topbar"><div className="topbar-title">{nav.find(item=>item.key===view)?.label||'Dompet Ajaib'}</div><div className="topbar-actions"><NotificationBell navigate={go}/><span className={`status-pill ${online&&sync!=='offline'&&sync!=='error'?'':'offline'}`}><i/>{online?(sync==='syncing'?'Menyinkron…':sync==='error'?'Gagal sinkron':sync==='offline'?'Data tersimpan lokal':'Tersinkron'):'Offline'}</span><Button className="small" aria-label="Catat transaksi" title="Catat transaksi" onClick={()=>openTx()}><Plus size={16}/><span className="btn-label">Catat transaksi</span></Button></div></header><main className="content">{error&&<div className="notice error">Koneksi data bermasalah: {error}</div>}<div key={`${view}:${focus||''}`} className="view-enter">{views[view]}</div></main></div><MobileNavigation view={view} items={nav} onNavigate={go} openTx={openTx}/><Dialog open={txOpen} onOpenChange={setTxOpen}><DialogContent title={editing?'Ubah transaksi':'Catat transaksi'}>{editing&&!['claim_advance','receivable_issue','borrowing'].includes(editing.type)&&<Confirm title="Hapus transaksi?" description="Saldo dompet dan catatan terkait akan dikembalikan sesuai transaksi ini." onConfirm={()=>{if(!user)return;const id=editing.id;setTxOpen(false);track(deleteTransaction(user.uid,id),{pending:'Menghapus transaksi…',success:'Transaksi dihapus.',failure:'Transaksi belum terhapus',after:()=>setRevision(n=>n+1)})}}><Button variant="danger" className="full" style={{marginBottom:15}}>Hapus transaksi</Button></Confirm>}{editing&&isCycleClosed(editing.date,data.cycleSnapshots||[])&&<div className="notice">Transaksi ini berada dalam siklus yang sudah ditutup. Penghapusan akan menghitung ulang laporan siklus.</div>}{editing&&['claim_advance','receivable_issue','borrowing','claim_writeoff'].includes(editing.type)&&<div className="notice">Transaksi pembuka diubah melalui catatan induknya. Jika klaim ditolak, hapus peristiwa penolakan dan catat ulang untuk mengoreksi nilainya.</div>}<TransactionForm key={editing?.id||JSON.stringify(preset)||'new'} preset={preset} editing={editing} background={saveInBackground} onDone={m=>{setTxOpen(false);setRevision(n=>n+1);setToast(m)}} onCancel={()=>setTxOpen(false)}/></DialogContent></Dialog></div>;
}
