'use client';
import { useMemo, useState } from 'react';
import { Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts';
import { useApp } from './app-provider';
import { Empty, Field, Select } from './fields';
import { PeriodSelector, usePeriodTransactions } from './period-selector';
import { IdentityBadge } from './visual-identity';
import { budgetCurrent, rupiah } from '@/lib/accounting';
import { budgetCommitted } from '@/lib/finance-control';
import { categoryBreakdown, transactionsForCategory, type CategorySlice } from '@/lib/category-analytics';
import { saveProfile } from '@/lib/firestore';
import { dateInTimeZone, daysInRange, groupTransactions, localDate, parseDate, periodLabel, resolvePeriodRange, summarizeTransactions, type DateRange, type Granularity, type PeriodPreset } from '@/lib/period';
import type { LedgerTx } from '@/lib/types';

function Detail({category,items,range,wallet,onClose}:{category:CategorySlice;items:LedgerTx[];range:DateRange;wallet:string;onClose:()=>void}){
 const {data,profile}=useApp();const [expanded,setExpanded]=useState(false);const before=parseDate(range.start);before.setDate(before.getDate()-daysInRange(range));const previous=usePeriodTransactions({start:localDate(before),end:range.start});
 const older=previous.items.filter(t=>!wallet||t.walletId===wallet||t.destinationWalletId===wallet);const olderAmount=categoryBreakdown(older,data.categories).find(c=>c.id===category.id)?.amount||0;
 const budget=data.budgets.filter(b=>b.active&&(b.categoryId===category.id||data.categories.some(c=>c.id===b.categoryId&&c.parentId===category.id)));
 const today=dateInTimeZone(new Date(),profile?.timeZone),elapsed=Math.max(1,Math.min(daysInRange(range),Math.ceil((today.getTime()-parseDate(range.start).getTime())/86400000)+1)),estimate=category.amount/elapsed*daysInRange(range);
 const allocations=transactionsForCategory(items,data.categories,category.id).filter(t=>t.type==='expense'||t.type==='transfer'||t.type==='claim_writeoff');
 return <div className="panel analytics-detail"><div className="budget-line"><h3><IdentityBadge icon={category.icon} color={category.color} label={category.name}/></h3><button className="link-button" onClick={onClose}>Tutup rincian</button></div><div className="kpi-strip"><div><small>Pengeluaran</small><strong>{rupiah(category.amount)}</strong></div><div><small>Jumlah transaksi</small><strong>{category.count}</strong></div><div><small>Rata-rata per transaksi</small><strong>{rupiah(category.amount/Math.max(1,category.count))}</strong></div></div><details className="disclosure"><summary>Bandingkan & lihat anggaran</summary><div className="money-detail"><div><span>Periode sebelumnya</span><strong>{previous.loading?'Memuat…':rupiah(olderAmount)}</strong></div><div><span>Perkiraan akhir periode</span><strong>{rupiah(estimate)}</strong></div>{budget.map(b=>{const progress=budgetCurrent(b,data.transactions,data.categories,today,profile?.salaryCycleStartDay||24);const committed=budgetCommitted(b,data,today,profile?.salaryCycleStartDay||24);return <div key={b.id}><span>Anggaran {b.name} · sisa setelah komitmen</span><strong>{rupiah(progress.remaining-committed)}</strong></div>})}{!budget.length&&<small>Belum ada anggaran untuk kategori ini.</small>}</div></details>{category.subcategories.length>0&&<div className="mini-list subcategory-list"><h4>Subkategori</h4>{category.subcategories.map(sub=><div key={sub.id}><IdentityBadge icon={sub.icon} color={sub.color||category.color} label={sub.name}/><strong>{rupiah(sub.amount)}</strong></div>)}</div>}<div className="budget-line"><h4>Transaksi yang terkait</h4><button className="link-button" onClick={()=>setExpanded(x=>!x)}>{expanded?'Tampilkan 5':'Lihat semua'}</button></div>{(expanded?allocations:allocations.slice(0,5)).map(tx=><div className="data-row" key={tx.id}><span className="data-row-main"><strong>{tx.description||tx.merchant||category.name}</strong><small>{tx.date} · porsi kategori{tx.splits?.length?' · transaksi terbagi':''}</small></span><strong>{rupiah(tx.type==='transfer'?tx.transferFee||0:tx.amount)}</strong></div>)}{!allocations.length&&<Empty message="Tidak ada transaksi pengeluaran pada kategori ini."/>}</div>;
}
export function AnalyticsView(){
 const {user,profile,data}=useApp();const [wallet,setWallet]=useState(''),[category,setCategory]=useState(''),[focus,setFocus]=useState(''),[limit,setLimit]=useState<5|7|0>(5),[error,setError]=useState('');
 const period=profile?.analyticsPeriod||'salary_cycle';const range=resolvePeriodRange(period,profile?.salaryCycleStartDay||24,dateInTimeZone(new Date(),profile?.timeZone),profile?.analyticsCustom);const history=usePeriodTransactions(range);
 const walletItems=useMemo(()=>history.items.filter(t=>!wallet||t.walletId===wallet||t.destinationWalletId===wallet),[history.items,wallet]);
 const items=useMemo(()=>transactionsForCategory(walletItems,data.categories,category),[walletItems,data.categories,category]);const summary=useMemo(()=>summarizeTransactions(items),[items]);const rows=useMemo(()=>categoryBreakdown(items,data.categories),[items,data.categories]);
 const visible=limit?rows.slice(0,limit):rows;const selected=rows.find(c=>c.id===focus);const granularity=profile?.analyticsGranularity||'auto';const trend=useMemo(()=>groupTransactions(items,range,granularity),[items,range.start,range.end,granularity]);
 async function save(changes:Parameters<typeof saveProfile>[1]){if(!user)return;setError('');try{await saveProfile(user.uid,changes)}catch(e){setError((e as Error).message)}}
 return <><div className="page-heading"><div><h1>Analisis</h1><p>Kenali pengeluaranmu per kategori, tanpa mengubah transaksi.</p></div></div><div className="panel analytics-period"><PeriodSelector value={period} custom={profile?.analyticsCustom} onChange={value=>void save({analyticsPeriod:value as PeriodPreset})} onCustomChange={value=>void save({analyticsCustom:value})}/></div><div className="card-grid analysis-summary"><div className="stat-card"><small>Pemasukan</small><strong className="stat-value">{history.loading?'Memuat…':rupiah(summary.income)}</strong></div><div className="stat-card"><small>Pengeluaran</small><strong className="stat-value">{history.loading?'Memuat…':rupiah(summary.expense)}</strong></div><div className="stat-card"><small>Selisih Uang</small><strong className="stat-value">{history.loading?'Memuat…':rupiah(summary.cashFlow)}</strong></div></div>
 <details className="panel disclosure analytics-filters"><summary>Filter lanjut {wallet||category?'· aktif':''}</summary><div className="form-grid"><Field label="Dompet"><Select value={wallet} onChange={e=>{setWallet(e.target.value);setFocus('')}}><option value="">Semua dompet</option>{data.wallets.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select></Field><Field label="Kategori"><Select value={category} onChange={e=>{setCategory(e.target.value);setFocus('')}}><option value="">Semua kategori</option>{data.categories.filter(c=>!c.isArchived).map(c=><option key={c.id} value={c.id}>{c.parentId?'↳ ':''}{c.name}</option>)}</Select></Field></div><small>Jika satu pembayaran punya beberapa kategori, angka hanya menghitung porsi kategori yang dipilih. Saldo dompet tetap mengikuti satu pembayaran asli.</small></details>
 {(history.error||error)&&<p className="form-error" role="alert">{history.error||error}</p>}<div className="panel analytics-chart"><div className="budget-line"><div><h3>Pengeluaran per kategori</h3><small>{periodLabel(range)}</small></div><Field label="Tampilkan"><Select value={limit} onChange={e=>setLimit(Number(e.target.value) as 0|5|7)}><option value={5}>5 teratas</option><option value={7}>7 teratas</option><option value={0}>Semua</option></Select></Field></div>{visible.length?<>{visible.length>7?<div className="analytics-bar-list">{visible.map((row,index)=><button type="button" key={row.id} onClick={()=>setFocus(row.id)} aria-label={`${row.name}: ${rupiah(row.amount)}`}><span>{row.name}</span><i><i style={{width:`${row.amount/Math.max(1,visible[0].amount)*100}%`,background:row.color||`var(--chart-${index%6+1})`}}/></i></button>)}</div>:<div className="chart-box donut-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={visible} dataKey="amount" nameKey="name" innerRadius="53%" outerRadius="80%" onClick={(_,index)=>setFocus(visible[index]?.id||'')}>{visible.map((c,i)=><Cell key={c.id} fill={c.color||`var(--chart-${i%6+1})`}/>)}</Pie><Tooltip formatter={v=>rupiah(Number(v))}/></PieChart></ResponsiveContainer></div>}<div className="analytics-category-list">{visible.map(row=><button type="button" aria-pressed={focus===row.id} className={focus===row.id?'active':''} key={row.id} onClick={()=>setFocus(row.id)}><IdentityBadge icon={row.icon} color={row.color} label={row.name}/><span>{Math.round(row.amount/Math.max(1,summary.expense)*100)}% · {row.count} transaksi</span><strong>{rupiah(row.amount)}</strong></button>)}</div>{limit!==0&&rows.length>visible.length&&<small>+ {rows.length-visible.length} kategori lain · {rupiah(rows.slice(visible.length).reduce((n,x)=>n+x.amount,0))}. Pilih “Semua” untuk melihatnya.</small>}</>:<Empty message={history.loading?'Memuat kategori…':'Belum ada pengeluaran pada periode ini.'}/>}</div>{selected&&<Detail key={`${selected.id}:${range.start}:${range.end}`} category={selected} items={walletItems} range={range} wallet={wallet} onClose={()=>setFocus('')}/>}
 <details className="panel disclosure analytics-more"><summary>Grafik waktu dan angka tambahan</summary><div className="form-grid"><Field label="Kelompok waktu"><Select value={granularity} onChange={e=>void save({analyticsGranularity:e.target.value as Granularity})}><option value="auto">Otomatis</option><option value="daily">Harian</option><option value="weekly">Mingguan</option><option value="monthly">Bulanan</option><option value="yearly">Tahunan</option></Select></Field><div><small>Rata-rata pengeluaran per hari</small><strong>{rupiah(summary.expense/daysInRange(range))}</strong></div></div>{trend.length>0&&<div className="chart-box"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><XAxis dataKey="label" tick={{fill:'var(--muted)',fontSize:10}}/><Tooltip formatter={v=>rupiah(Number(v))}/><Line type="monotone" dataKey="expense" name="Pengeluaran" stroke="var(--accent)" strokeWidth={3}/><Line type="monotone" dataKey="income" name="Pemasukan" stroke="var(--chart-2)" strokeWidth={2}/></LineChart></ResponsiveContainer></div>}</details></>;
}
