'use client';
import { useEffect, useMemo, useState } from 'react';
import { walletGroup, walletGroups } from '@/lib/wallet-groups';
import { Emoji } from './emoji';
import { ArrowDown, ArrowLeftRight, ArrowRight, ArrowUp, CalendarCheck, CalendarClock, CalendarDays, CreditCard, Landmark, Lock, Banknote, Scale, Settings2, Sparkles, TrendingDown, TrendingUp, X, type LucideIcon } from 'lucide-react';
import dynamic from 'next/dynamic';
import { useApp } from './app-provider';
import { Button } from './ui/button';
import { Empty, Select } from './fields';
import { TxList } from './dashboard';
import { QuickActions } from './quick-actions';
import { PeriodSelector, usePeriodTransactions } from './period-selector';
import { dropRow, ReorderHandle, reorder } from './reorder-handle';
import { AppIcon, IdentityBadge, identityStyle } from './visual-identity';
import { Delta } from './delta';
// Charts load after Beranda shows its numbers, keeping the chart library out of the first download.
const chartLoading = () => <div className="chart-skeleton" aria-hidden="true"/>;
const TrendMiniChart = dynamic(() => import('./trend-mini-chart'), { ssr: false, loading: chartLoading });
const ForecastWidget = dynamic(() => import('./forecast').then(m => m.ForecastWidget), { ssr: false, loading: () => <div className="panel"><div className="chart-skeleton" aria-hidden="true"/></div> });
const CategoryDonut = dynamic(() => import('./category-donut').then(m => m.CategoryDonut), { ssr: false, loading: chartLoading });
import { budgetCurrent, countedBudgets, metrics, rupiah } from '@/lib/accounting';
import { availableMoney, budgetCommitted, committedAmount, upcomingEvents } from '@/lib/finance-control';
import { categoryBreakdown, transactionsForCategory } from '@/lib/category-analytics';
import { incomeBreakdown } from '@/lib/insights';
import { saveProfile } from '@/lib/firestore';
import { dateInTimeZone, formatDate, previousComparableRange, groupTransactions, nextDate, periodLabel, resolvePeriodRange, summarizeTransactions, todayInTimeZone, type DateRange, type PeriodPreset } from '@/lib/period';
import type { LedgerTx } from '@/lib/types';

export const dashboardOptions=[
 ['free','Uang Bebas'],['budget','Sisa Anggaran'],['income','Pemasukan'],['expenses','Pengeluaran'],['cashFlow','Selisih Masuk & Keluar'],
 ['assets','Total Aset'],['netWorth','Aset Bersih'],['liabilities','Utang'],['reserved','Dana Disimpan'],['safeDaily','Jatah Aman per Hari'],
 ['daysUntilSalary','Hari Menuju Gajian'],['money','Uang Tersedia'],['quickActions','Catat Cepat'],['inbox','Perlu Dikonfirmasi'],
 ['upcoming','7 Hari Mendatang'],['budgets','Anggaran Berjalan'],['recent','Transaksi Terbaru'],['wallets','Saldo Dompet'],
 ['claims','Klaim Kantor'],['receivables','Piutang'],['funds','Tujuan Dana'],['topCategories','Kategori Teratas'],
 ['categoryDonut','Grafik Kategori'],['expenseTrend','Tren Pengeluaran'],['forecast','Proyeksi'],['incomeExpense','Pemasukan & Pengeluaran'],
] as const;
type WidgetId=typeof dashboardOptions[number][0];
type BookRow={id:string;name:string;icon?:string;color?:string;amount:number};
const known=new Set<string>(dashboardOptions.map(([id])=>id));
const defaultLayout:WidgetId[]=['free','budget','income','expenses','quickActions','recent','categoryDonut','budgets','wallets','incomeExpense','forecast'];
/** Saved layouts from before the Pemasukan & Pengeluaran card get it once, right under Saldo Dompet. */
const LAYOUT_VERSION=2;
const withNewCards=(list:string[],version?:number)=>(version||1)>=LAYOUT_VERSION||list.includes('incomeExpense')?list:list.includes('wallets')?list.flatMap(id=>id==='wallets'?[id,'incomeExpense']:[id]):[...list,'incomeExpense'];
/** Cards that stay open at full width, right under the summary. */
const pinned=new Set<WidgetId>(['recent','categoryDonut']);
/** Layouts that were saved while an older default was shown; they follow the new default. */
const oldDefaults=[['free','budget','income','expenses','money','quickActions','inbox','upcoming','budgets','recent'],['free','budget','income','expenses','money','quickActions','inbox','upcoming','budgets','recent','wallets'],['free','budget','income','expenses','quickActions','recent','budgets','wallets','categoryDonut','forecast'],['free','budget','income','expenses','quickActions','recent','categoryDonut','budgets','wallets','forecast']].map(list=>list.join());
/** Where each summary card leads when clicked. */
const cardTarget:Partial<Record<WidgetId,[string,string?]>>={free:['wallets'],budget:['budgets'],income:['transactions','type:income'],expenses:['transactions','type:expense'],cashFlow:['transactions'],assets:['wallets'],netWorth:['wallets'],liabilities:['debts'],reserved:['funds'],safeDaily:['budgets'],daysUntilSalary:['forecast']};
/** Icon in the top-right corner of each summary card. */
const metricIcons:Partial<Record<WidgetId,LucideIcon>>={free:Sparkles,budget:Banknote,income:TrendingUp,expenses:TrendingDown,cashFlow:ArrowLeftRight,assets:Landmark,netWorth:Scale,liabilities:CreditCard,reserved:Lock,safeDaily:CalendarCheck,daysUntilSalary:CalendarClock};
const metricIds=new Set<WidgetId>(['free','budget','income','expenses','cashFlow','assets','netWorth','liabilities','reserved','safeDaily','daysUntilSalary']);

/** Widgets start expanded on wide screens where there is room, and collapsed on phones. */
function useWideScreen(){const [wide,setWide]=useState(false);useEffect(()=>{const media=window.matchMedia('(min-width: 1101px)');const update=()=>setWide(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);return wide;}
function AnalyticsWidget({id,navigate,defaultPeriod,open}:{id:'topCategories'|'categoryDonut'|'expenseTrend';navigate:(view:string,focus?:string)=>void;defaultPeriod:PeriodPreset;open?:boolean}){
 const {data,profile}=useApp(),config=profile?.dashboardWidgetConfig?.[id],period=config?.period||defaultPeriod,range=resolvePeriodRange(period,profile?.salaryCycleStartDay||24,dateInTimeZone(new Date(),profile?.timeZone),profile?.dashboardCustom),history=usePeriodTransactions(range);
 const prevRange=previousComparableRange(period,profile?.salaryCycleStartDay||24,range,todayInTimeZone(profile?.timeZone)),prevHistory=usePeriodTransactions(prevRange);
 const basis=prevRange.partial?`Periode lalu, ${prevRange.days} hari pertama`:'Periode lalu';
 const previous=useMemo(()=>categoryBreakdown(transactionsForCategory(prevHistory.items,data.categories,config?.categoryId||''),data.categories),[prevHistory.items,data.categories,config?.categoryId]);
 const items=useMemo(()=>transactionsForCategory(history.items,data.categories,config?.categoryId||''),[history.items,data.categories,config?.categoryId]);const categories=useMemo(()=>categoryBreakdown(items,data.categories),[items,data.categories]),trend=useMemo(()=>groupTransactions(items,range,'auto'),[items,range.start,range.end]);
 const title=id==='topCategories'?'Kategori Teratas':id==='categoryDonut'?'Grafik Kategori':'Tren Pengeluaran';
 const total=categories.reduce((n,c)=>n+c.amount,0),prevTotal=previous.reduce((n,c)=>n+c.amount,0);
 if(id==='categoryDonut')return <section className="panel widget-details widget-static donut-widget"><div className="widget-head"><span><strong>Grafik Kategori</strong><small>{periodLabel(range)} · ketuk kategori untuk detail{!prevHistory.loading&&total>0&&<> · <Delta current={total} previous={prevTotal} good="down" basis={basis}/></>}</small></span><button type="button" className="link-button" onClick={()=>navigate('analytics')}>Analisis →</button></div><div className="widget-body">{history.error&&<p className="form-error" role="alert">{history.error}</p>}{categories.length?<CategoryDonut slices={categories} previous={previous} previousReady={!prevHistory.loading} navigate={navigate} basis={basis} rangeFocus={`@${range.start}..${range.end}`}/>:<Empty message={history.loading?'Memuat…':'Belum ada pengeluaran pada periode ini.'}/>}</div></section>;
 return <details className="panel widget-details" open={open||undefined}><summary><strong>{title}</strong><small>{periodLabel(range)}</small></summary><div className="widget-body">{history.error&&<p className="form-error" role="alert">{history.error}</p>}{id==='topCategories'?categories.slice(0,6).map(c=><button type="button" className="budget-line row-link" key={c.id} onClick={()=>navigate('transactions',`category:${c.id}@${range.start}..${range.end}`)}><IdentityBadge icon={c.icon} color={c.color} label={c.name}/><span className="row-amount"><strong>{rupiah(c.amount)}</strong>{!prevHistory.loading&&<Delta current={c.amount} previous={previous.find(p=>p.id===c.id)?.amount||0} good="down" basis={basis} compact/>}</span></button>):id==='expenseTrend'&&trend.length&&categories.length?<div className="chart-box"><TrendMiniChart data={trend}/></div>:null}{!categories.length&&<Empty message={history.loading?'Memuat…':'Belum ada pengeluaran.'}/>}<button type="button" className="link-button" onClick={()=>navigate('analytics')}>Buka analisis →</button></div></details>;
}

export function Dashboard({openTx,navigate,notify}:{openTx:(preset?:Partial<LedgerTx>,editing?:LedgerTx)=>void;navigate:(view:string,focus?:string)=>void;notify:(message:string)=>void}){
 const {data,profile,cycle,user}=useApp();const wide=useWideScreen(),open=wide||undefined;const [customize,setCustomize]=useState(false),[picker,setPicker]=useState(false),[configure,setConfigure]=useState<string|null>(null),[pending,setPending]=useState<string[]|null>(null),[error,setError]=useState('');
 const period=profile?.dashboardPeriod||'salary_cycle';const range=resolvePeriodRange(period,profile?.salaryCycleStartDay||24,dateInTimeZone(new Date(),profile?.timeZone),profile?.dashboardCustom);
 const history=usePeriodTransactions(range);const summary=useMemo(()=>summarizeTransactions(history.items),[history.items]);const day=dateInTimeZone(new Date(),profile?.timeZone),today=todayInTimeZone(profile?.timeZone);
 const prevRange=previousComparableRange(period,profile?.salaryCycleStartDay||24,range,today),prevHistory=usePeriodTransactions(prevRange),prevSummary=useMemo(()=>summarizeTransactions(prevHistory.items),[prevHistory.items]);
 const stat=useMemo(()=>metrics(data,cycle.start,cycle.end,profile?.salaryCycleStartDay,day,Boolean(profile?.netWorthIncludesReceivables)),[data,cycle.start,cycle.end,profile?.salaryCycleStartDay,profile?.netWorthIncludesReceivables,profile?.timeZone]);
 const saved=profile?.dashboardWidgets?.length&&!oldDefaults.includes(profile.dashboardWidgets.join())?withNewCards(profile.dashboardWidgets,profile.dashboardWidgetsVersion):null;const current=(pending||saved||defaultLayout).filter((key):key is WidgetId=>known.has(key));
 const selected=current.length?current:defaultLayout;const inbox=data.drafts.filter(d=>d.status==='pending');let weekEnd=today;for(let i=0;i<7;i++)weekEnd=nextDate(weekEnd);
 const due=upcomingEvents(data,profile!,{start:today,end:weekEnd}).filter(e=>e.kind!=='note');const committed=committedAmount(data,today,cycle.end,profile||{});
 const after=availableMoney(stat.free,committed,profile||{});
 const activeBudgets=data.budgets.map((b,i)=>({b,i})).filter(({b})=>b.active).sort((x,y)=>(x.b.sortOrder??1e6+x.i)-(y.b.sortOrder??1e6+y.i)||x.b.name.localeCompare(y.b.name)).map(({b})=>b);const uniqueBudgets=countedBudgets(activeBudgets);// Spending room only: what is left of a savings target is not money to spend (same as the Anggaran page).
 const remaining=uniqueBudgets.filter(b=>b.classification!=='savings'&&b.classification!=='sinking').reduce((sum,b)=>{const row=budgetCurrent(b,data.transactions,data.categories,day,profile?.salaryCycleStartDay||24);return sum+row.remaining-budgetCommitted(b,data,day,profile?.salaryCycleStartDay||24)},0);
 const borrowed=history.items.filter(t=>t.type==='borrowing').reduce((n,t)=>n+t.amount,0),repaid=history.items.filter(t=>t.type==='debt_payment').reduce((n,t)=>n+t.amount,0);
 const flowBasis=prevRange.partial?`Periode lalu, ${prevRange.days} hari pertama`:'Periode lalu',startBasis='Awal periode ini (akhir periode lalu)';
 /** Value to compare with, the tone of a rise, and what it is compared with. Balances compare with the start of this period. */
 const compare:Partial<Record<WidgetId,[number,'up'|'down',string]>>={income:[prevSummary.income,'up',flowBasis],expenses:[prevSummary.expense,'down',flowBasis],cashFlow:[prevSummary.cashFlow,'up',flowBasis],budget:[remaining+summary.expense-prevSummary.expense,'up',`${flowBasis} (sisa jika belanja sama)`],free:[stat.free-summary.cashFlow,'up',startBasis],assets:[stat.assets-summary.cashFlow,'up',startBasis],netWorth:[stat.netWorth-summary.cashFlow,'up',startBasis],liabilities:[stat.liabilities-borrowed+repaid,'down',startBasis]};
 const amount:Partial<Record<WidgetId,number>>={free:stat.free,budget:remaining,income:summary.income,expenses:summary.expense,cashFlow:summary.cashFlow,assets:stat.assets,netWorth:stat.netWorth,liabilities:stat.liabilities,reserved:stat.reserved,safeDaily:Math.max(0,stat.discretionaryRemaining)/cycle.daysRemaining,daysUntilSalary:cycle.daysRemaining};
 async function save(changes:Parameters<typeof saveProfile>[1]){if(!user)return;setError('');try{await saveProfile(user.uid,changes)}catch(e){setPending(null);setError((e as Error).message||'Pengaturan belum tersimpan.')}}
 function layout(ids:string[]){setPending(ids);void save({dashboardWidgets:ids,dashboardWidgetsVersion:LAYOUT_VERSION})}
 function move(from:string,to:string){layout(reorder(selected.map(id=>({id})),from,to).map(item=>item.id))}
 function setWidgetConfig(id:string,changes:{period?:PeriodPreset;categoryId?:string}){void save({dashboardWidgetConfig:{...(profile?.dashboardWidgetConfig||{}),[id]:{...(profile?.dashboardWidgetConfig?.[id]||{}),...changes}}})}
 function setPeriod(value:PeriodPreset){void save({dashboardPeriod:value})}
 function setCustom(value:DateRange){if(value.start<value.end)void save({dashboardCustom:value})}
 const label=(id:string)=>dashboardOptions.find(([key])=>key===id)?.[1]||id;
 // The main number lives in the hero card; money metrics only (days-to-payday already shows there).
 const heroId:WidgetId=metricIds.has((profile?.primaryMetric||'free') as WidgetId)&&!['daysUntilSalary','safeDaily'].includes(profile?.primaryMetric||'')?(profile?.primaryMetric as WidgetId)||'free':'free';
 const cycleTotal=Math.max(1,Math.round((new Date(`${cycle.end}T12:00:00`).getTime()-new Date(`${cycle.start}T12:00:00`).getTime())/86400000)),cyclePct=Math.min(100,Math.max(3,Math.round((cycleTotal-cycle.daysRemaining)/cycleTotal*100)));
 function widget(id:WidgetId){
  if(metricIds.has(id)){const target=cardTarget[id];return <button type="button" disabled={customize} className={'stat-card stat-link '+(id===(profile?.primaryMetric||'free')?'featured':'')} onClick={()=>target&&navigate(target[0],target[0]==='transactions'?`${target[1]||''}@${range.start}..${range.end}`:target[1])}><span className="stat-head"><span className="stat-label">{label(id)}</span>{(()=>{const Icon=metricIcons[id];return Icon?<span className={`metric-icon is-${id}`} aria-hidden="true"><Icon size={17}/></span>:null})()}</span><strong className="stat-value">{id==='daysUntilSalary'?amount[id]+' hari':history.loading&&['income','expenses','cashFlow'].includes(id)?'Memuat…':rupiah(amount[id]||0)}</strong><small>{['income','expenses','cashFlow'].includes(id)?periodLabel(range):id==='safeDaily'?'Dari sisa anggaran kebutuhan':'Kondisi saat ini'}</small>{compare[id]&&!history.loading&&!prevHistory.loading&&<Delta current={amount[id]||0} previous={compare[id]![0]} good={compare[id]![1]} basis={compare[id]![2]}/>}</button>;}
  if(id==='quickActions')return <div className="panel quick-panel"><QuickActions openTx={openTx} navigate={navigate} notify={notify}/></div>;
  if(id==='money')return <details className="panel widget-details" open={open}><summary><span><strong>Uang Tersedia</strong><small>Setelah komitmen</small></span><strong>{rupiah(after)}</strong></summary><div className="money-detail">{[['Total Aset',stat.assets],['Disimpan, kantong & tujuan dana',-stat.reserved],['Uang Bebas',stat.free],['Komitmen Belum Dibayar',-committed],...(profile?.freeMoneyBuffer?[['Cadangan Aman',-profile.freeMoneyBuffer] as [string,number]]:[]),['Uang Tersedia',after],['Utang (ditampilkan terpisah)',stat.liabilities],...(profile?.netWorthIncludesReceivables?[]:[['Piutang & klaim (tidak dihitung)',stat.receivables] as [string,number]]),['Aset Bersih',stat.netWorth]].map(([key,value])=><div key={key}><span>{key}</span><strong>{rupiah(value as number)}</strong></div>)}<small>Komitmen tidak mengubah saldo dompet.</small><button type="button" className="link-button" onClick={()=>navigate('wallets')}>Lihat dompet →</button></div></details>;
  if(id==='inbox')return <details className="panel widget-details" open={open}><summary><span><strong>Perlu Dikonfirmasi</strong><small>{inbox.length} transaksi</small></span><strong>{rupiah(inbox.reduce((n,item)=>n+item.amount,0))}</strong></summary><div className="widget-body">{inbox.slice(0,4).map(item=><button type="button" className="budget-line row-link" key={item.id} onClick={()=>navigate('inbox')}><span>{item.name}<small style={{display:'block'}}>{formatDate(item.plannedDate)}</small></span><strong>{rupiah(item.amount)}</strong></button>)}{!inbox.length&&<small>Belum ada yang menunggu konfirmasi.</small>}<button type="button" className="link-button" onClick={()=>navigate('inbox')}>Buka daftar konfirmasi →</button></div></details>;
  if(id==='upcoming')return <details className="panel widget-details" open={open}><summary><span><strong>7 Hari Mendatang</strong><small>Rencana · saldo belum berubah</small></span><strong>{rupiah(due.reduce((n,e)=>n+e.amount,0))}</strong></summary><div className="widget-body"><div className="budget-line"><span>Masuk {rupiah(due.reduce((n,e)=>n+Math.max(0,e.amount),0))}</span><span>Keluar {rupiah(due.reduce((n,e)=>n+Math.max(0,-e.amount),0))}</span></div>{due.slice(0,4).map(event=><button type="button" className="budget-line row-link" key={event.id} onClick={()=>navigate('upcoming')}><span>{event.title}<small style={{display:'block'}}>{formatDate(event.date,false)}</small></span><strong className={event.amount>=0?'amount-positive':'amount-negative'}>{event.amount>=0?'+':'−'}{rupiah(Math.abs(event.amount))}</strong></button>)}{!due.length&&<small>Tidak ada jadwal dalam 7 hari ke depan.</small>}<button type="button" className="link-button" onClick={()=>navigate('upcoming')}>Lihat jadwal →</button></div></details>;
  if(id==='budgets')return <details className="panel widget-details" open={open}><summary><span><strong>Anggaran Berjalan</strong>{!prevHistory.loading&&<small><Delta current={remaining} previous={compare.budget![0]} good="up" basis={compare.budget![2]}/></small>}</span><strong>{rupiah(remaining)}</strong></summary><div className="widget-body">{activeBudgets.slice(0,5).map(b=>{const s=budgetCurrent(b,data.transactions,data.categories,day,profile?.salaryCycleStartDay||24);const left=s.remaining-budgetCommitted(b,data,day,profile?.salaryCycleStartDay||24);const pct=s.available>0?Math.min(100,Math.round(s.spent/s.available*100)):0;const rawPct=s.available>0?Math.round(s.spent/s.available*100):0,tone=rawPct>=100?'over':rawPct>=(b.warningPercent||profile?.budgetWarningPercent||80)?'warn':'';return <button type="button" className="budget-line row-link budget-mini" key={b.id} onClick={()=>navigate('budgets')}><span><span className="bm-top"><span className="bm-name">{b.name}</span><b className={`bm-pct ${tone}`}>{rawPct}%</b></span><i className="mini-bar" aria-hidden="true"><b className={tone} style={{width:`${pct}%`}}/></i><small className="bm-meta">Terpakai {rupiah(s.spent)} dari {rupiah(s.available)}</small></span><strong className={left<0?'amount-negative':''}>{rupiah(left)}<small>{left<0?'lebih':'sisa'}</small></strong></button>})}{!activeBudgets.length&&<small>Belum ada anggaran aktif.</small>}<button type="button" className="link-button" onClick={()=>navigate('budgets')}>Lihat anggaran →</button></div></details>;
  if(id==='recent')return <section className="panel widget-details widget-static recent-widget"><div className="widget-head"><span><strong>Transaksi Terbaru</strong><small>Ketuk transaksi untuk melihat detail</small></span><button type="button" className="link-button" onClick={()=>navigate('transactions')}>Lihat semua →</button></div><div className="widget-body"><TxList items={data.transactions.slice(0,6)} onEdit={t=>openTx(undefined,t)}/></div></section>;
  if(id==='incomeExpense'){
   // Income and spending of the dashboard period per main category, each against the comparable previous period.
   const merge=(now:BookRow[],before:BookRow[])=>[...now.map(r=>({...r,previous:before.find(p=>p.id===r.id)?.amount||0})),...before.filter(p=>!now.some(r=>r.id===p.id)).map(p=>({...p,amount:0,previous:p.amount}))].sort((a,b)=>b.amount-a.amount||b.previous-a.previous);
   const net=summary.income-summary.expense,prevNet=prevSummary.income-prevSummary.expense,LIMIT=6;
   const section=(kind:'income'|'expense',title:string,total:number,prevTotal:number,rows:ReturnType<typeof merge>)=><section className={`book-section is-${kind}`}><header><span>{title}</span><b>{rupiah(total)}</b>{!prevHistory.loading&&(total||prevTotal)?<Delta current={total} previous={prevTotal} good={kind==='income'?'up':'down'} basis={flowBasis} compact/>:null}</header>{rows.length?<ul>{rows.slice(0,LIMIT).map(r=><li key={r.id}><button type="button" onClick={()=>navigate('transactions',kind==='income'?'type:income':`category:${r.id}@${range.start}..${range.end}`)}><span className="book-icon" style={identityStyle(r.color)}><AppIcon icon={r.icon} fallback={kind==='income'?'💰':'🗂️'}/></span><span className="book-name">{r.name}</span><span className="book-amount">{rupiah(r.amount)}</span><span className="book-delta">{!prevHistory.loading&&(r.amount||r.previous)?<Delta current={r.amount} previous={r.previous} good={kind==='income'?'up':'down'} basis={flowBasis} compact/>:<i>–</i>}</span></button></li>)}</ul>:<p className="book-empty">{history.loading?'Memuat…':kind==='income'?'Belum ada pemasukan di periode ini.':'Belum ada pengeluaran di periode ini.'}</p>}{rows.length>LIMIT&&<small className="book-more">+{rows.length-LIMIT} kategori lain di Laporan</small>}</section>;
   return <details className="panel widget-details book-widget" open><summary><span><strong>Pemasukan & Pengeluaran</strong><small>{periodLabel(range)}</small></span><strong className={net<0?'amount-negative':'amount-positive'}>{net>0?'+':''}{rupiah(net)}</strong></summary><div className="widget-body book-body">
    <div className="book-head"><div><small>Selisih periode ini</small><strong className={net<0?'amount-negative':''}>{net>0?'+':''}{rupiah(net)}</strong></div><div className="book-vs"><small>Periode lalu</small><b>{prevHistory.loading?'…':`${prevNet>0?'+':''}${rupiah(prevNet)}`}</b>{!prevHistory.loading&&(net||prevNet)?<Delta current={net} previous={prevNet} good="up" basis={flowBasis} compact/>:null}</div></div>
    {section('income','Pemasukan',summary.income,prevSummary.income,merge(incomeBreakdown(history.items,data.categories),incomeBreakdown(prevHistory.items,data.categories)))}
    {section('expense','Pengeluaran',summary.expense,prevSummary.expense,merge(categoryBreakdown(history.items,data.categories),categoryBreakdown(prevHistory.items,data.categories)))}
    <button type="button" className="book-link" onClick={()=>navigate('report')}>Tampilkan lebih banyak di Laporan <ArrowRight size={15}/></button>
   </div></details>;
  }
  if(id==='wallets')return <details className="panel widget-details" open={open}><summary><span><strong>Saldo Dompet</strong><small>{data.wallets.filter(w=>!w.isArchived).length} dompet{!history.loading&&<> · <Delta current={stat.assets} previous={stat.assets-summary.cashFlow} basis={startBasis}/></>}</small></span><strong>{rupiah(stat.assets)}</strong></summary><div className="widget-body">{walletGroups.map(group=>{const list=data.wallets.filter(w=>!w.isArchived&&walletGroup(w)===group.key).sort((a,b)=>(a.displayOrder??0)-(b.displayOrder??0));if(!list.length)return null;return <div key={group.key} className="widget-wallet-group"><div className="widget-group-head"><span>{group.label}</span><b>{rupiah(list.reduce((n,w)=>n+w.cachedBalance,0))}</b></div><div className="wallet-mini-list">{list.map(w=><button type="button" className="wallet-mini" style={identityStyle(w.color)} key={w.id} onClick={()=>navigate('wallets',w.id)} aria-label={`Buka dompet ${w.name}`}><span className="wallet-mini-icon" aria-hidden="true"><AppIcon icon={w.icon}/></span><span className="wallet-mini-name">{w.name}</span><strong className={w.cachedBalance<0?'amount-negative':''}>{rupiah(w.cachedBalance)}</strong></button>)}</div></div>})}<button type="button" className="link-button" onClick={()=>navigate('wallets')}>Semua dompet →</button></div></details>;
  if(id==='claims'||id==='receivables'||id==='funds'){const items=id==='claims'?data.claims.map(x=>({id:x.id,name:x.name,value:x.remainingAmount})):id==='receivables'?data.receivables.map(x=>({id:x.id,name:x.person,value:x.remainingAmount})):data.funds.filter(x=>!x.isArchived).map(x=>({id:x.id,name:x.name,value:x.currentAmount}));return <details className="panel widget-details" open={open}><summary><strong>{label(id)}</strong><strong>{rupiah(items.reduce((n,x)=>n+x.value,0))}</strong></summary><div className="widget-body">{items.slice(0,5).map(row=><button type="button" className="budget-line row-link" key={row.id} onClick={()=>navigate(id)}><span>{row.name}</span><strong>{rupiah(row.value)}</strong></button>)}{!items.length&&<small>Belum ada catatan.</small>}<button type="button" className="link-button" onClick={()=>navigate(id==='claims'?'claims':id==='funds'?'funds':'receivables')}>Lihat rincian →</button></div></details>;}
  if(id==='forecast')return <ForecastWidget navigate={navigate} open={wide}/>;
  return <AnalyticsWidget id={id as 'topCategories'|'categoryDonut'|'expenseTrend'} navigate={navigate} defaultPeriod={period} open={wide}/>;
 }
 return <><section className="home-hero" aria-label="Ringkasan uang">
  <div className="home-hero-top"><div className="home-hero-hello"><span>Halo, {profile?.displayName||profile?.username||'teman'} <Emoji e="👋"/></span><small>{label(heroId)}</small></div><button type="button" className={`home-hero-edit ${customize?'active':''}`} aria-pressed={customize} aria-label={customize?'Selesai mengatur Beranda':'Atur Beranda'} title={customize?'Selesai':'Atur Beranda'} onClick={()=>{setCustomize(x=>!x);setPicker(false)}}>{customize?<><X size={16}/> Selesai</>:<Settings2 size={18}/>}</button></div>
  <button type="button" className="home-hero-amount" onClick={()=>{const target=cardTarget[heroId];if(target)navigate(target[0],target[1])}}>{rupiah(amount[heroId]||0)}</button>
  {compare[heroId]&&<div className="home-hero-delta"><Delta current={amount[heroId]||0} previous={compare[heroId]![0]} good={compare[heroId]![1]} basis={compare[heroId]![2]}/></div>}
  <div className="home-hero-cycle"><div><span><CalendarDays size={15}/> Gajian {formatDate(cycle.end)}</span><strong>{cycle.daysRemaining} hari lagi</strong></div><span className="home-hero-bar" role="progressbar" aria-label="Siklus gaji berjalan" aria-valuemin={0} aria-valuemax={100} aria-valuenow={cyclePct}><i style={{width:`${cyclePct}%`}}/></span></div>
  <div className="home-hero-chips">{heroId!=='netWorth'&&<button type="button" onClick={()=>navigate('wallets')}><span>Aset bersih</span><b>{rupiah(stat.netWorth)}</b></button>}{heroId!=='reserved'&&<button type="button" onClick={()=>navigate('wallets')}><span>Disimpan</span><b>{rupiah(stat.reserved)}</b></button>}</div>
 </section>
 {customize&&<div className="dashboard-toolbar"><Button className="small" variant="secondary" onClick={()=>setPicker(x=>!x)}>+ Tambah kartu</Button><button type="button" className="link-button" onClick={()=>layout([...defaultLayout])}>Atur ulang</button></div>}
 {customize&&picker&&<div className="panel widget-picker"><div className="budget-line"><h3>Pilih kartu</h3><button className="icon-btn" aria-label="Tutup pilihan" onClick={()=>setPicker(false)}><X size={18}/></button></div><div className="widget-picker-grid">{dashboardOptions.filter(([id])=>!selected.includes(id)).map(([id,name])=><button key={id} onClick={()=>{layout([...selected,id]);setPicker(false)}}>+ {name}</button>)}</div>{selected.length===dashboardOptions.length&&<p>Semua kartu sudah ditampilkan.</p>}</div>}
 {error&&<p className="form-error" role="alert">{error}</p>}<details className="panel dashboard-period"><summary><span>Periode: <strong>{periodLabel(range)}</strong></span></summary><PeriodSelector value={period} onChange={setPeriod} custom={profile?.dashboardCustom} onCustomChange={setCustom}/>{history.error&&<p role="alert" className="form-error">{history.error}</p>}</details>
 {(()=>{const shownMetrics=selected.filter(x=>metricIds.has(x)&&(customize||x!==heroId)),wideMetric=shownMetrics.length%2===1?shownMetrics[shownMetrics.length-1]:null;const slot=(id:WidgetId)=>{if(!customize&&id===heroId)return null;const index=selected.indexOf(id);return <div key={id} data-sort-id={id} className={`widget-slot ${metricIds.has(id)?'metric-slot':''} ${id===wideMetric?'metric-wide':''} ${profile?.realisticMode&&id==='assets'?'deemphasized':''}`} onDragOver={e=>{if(customize){e.preventDefault();e.currentTarget.classList.add('sort-target')}}} onDragLeave={e=>e.currentTarget.classList.remove('sort-target')} onDrop={e=>{if(customize)dropRow(e,id,move)}}>{customize&&<div className="widget-controls"><ReorderHandle id={id} onMove={move}/><span>{label(id)}</span><button className="icon-btn" aria-label={`Naikkan ${label(id)}`} disabled={index===0} onClick={()=>move(id,selected[index-1])}><ArrowUp size={15}/></button><button className="icon-btn" aria-label={`Turunkan ${label(id)}`} disabled={index===selected.length-1} onClick={()=>move(id,selected[index+1])}><ArrowDown size={15}/></button>{['categoryDonut','topCategories','expenseTrend'].includes(id)&&<button className="icon-btn" aria-label={`Atur ${label(id)}`} onClick={()=>setConfigure(value=>value===id?null:id)}><Settings2 size={15}/></button>}<button className="icon-btn" aria-label={`Sembunyikan ${label(id)}`} disabled={selected.length===1} onClick={()=>layout(selected.filter(x=>x!==id))}><X size={15}/></button></div>}{customize&&configure===id&&<div className="panel widget-config"><strong>Atur {label(id)}</strong><div className="form-grid"><label>Periode<Select value={profile?.dashboardWidgetConfig?.[id]?.period||period} onChange={e=>setWidgetConfig(id,{period:e.target.value as PeriodPreset})}><option value="salary_cycle">Siklus gaji</option><option value="calendar_month">Bulan ini</option><option value="last_7_days">7 hari</option><option value="last_30_days">30 hari</option><option value="last_3_months">3 bulan</option></Select></label><label>Kategori<Select value={profile?.dashboardWidgetConfig?.[id]?.categoryId||''} onChange={e=>setWidgetConfig(id,{categoryId:e.target.value})}><option value="">Semua kategori</option>{data.categories.filter(c=>!c.isArchived&&c.type==='expense').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></label></div></div>}{widget(id)}</div>};const metrics=selected.filter(id=>metricIds.has(id)),rest=selected.filter(id=>!metricIds.has(id)&&id!=='quickActions'&&!pinned.has(id)),pinnedIds=selected.filter(id=>pinned.has(id));return <>{metrics.length>0&&<div className="widget-grid metric-grid">{metrics.map(slot)}</div>}{selected.includes('quickActions')&&<div className="quick-strip">{slot('quickActions')}</div>}{pinnedIds.length>0&&<div className="recent-strip">{pinnedIds.map(slot)}</div>}{rest.length>0&&<div className="widget-columns">{rest.map(slot)}</div>}</>})()}</>;
}
