'use client';
import { useMemo, useState } from 'react';
import { ArrowDown, ArrowUp, CalendarDays, Settings2, X } from 'lucide-react';
import { Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts';
import { useApp } from './app-provider';
import { Button } from './ui/button';
import { Empty, Select } from './fields';
import { TxList } from './dashboard';
import { QuickActions } from './quick-actions';
import { PeriodSelector, usePeriodTransactions } from './period-selector';
import { dropRow, ReorderHandle, reorder } from './reorder-handle';
import { IdentityBadge } from './visual-identity';
import { budgetCurrent, metrics, rupiah } from '@/lib/accounting';
import { budgetCommitted, commitments, upcomingEvents } from '@/lib/finance-control';
import { categoryBreakdown, transactionsForCategory } from '@/lib/category-analytics';
import { saveProfile } from '@/lib/firestore';
import { dateInTimeZone, groupTransactions, nextDate, periodLabel, resolvePeriodRange, summarizeTransactions, todayInTimeZone, type DateRange, type PeriodPreset } from '@/lib/period';
import type { LedgerTx } from '@/lib/types';

export const dashboardOptions=[
 ['free','Uang Bebas'],['budget','Sisa Anggaran'],['income','Pemasukan'],['expenses','Pengeluaran'],['cashFlow','Selisih Uang'],
 ['assets','Total Aset'],['netWorth','Aset Bersih'],['liabilities','Utang'],['reserved','Dana Dicadangkan'],['safeDaily','Aman per Hari'],
 ['daysUntilSalary','Hari Menuju Gajian'],['money','Uang Tersedia'],['quickActions','Catat Cepat'],['inbox','Perlu Dikonfirmasi'],
 ['upcoming','Uang Mendatang'],['budgets','Anggaran Berjalan'],['recent','Transaksi Terbaru'],['wallets','Saldo Dompet'],
 ['claims','Klaim Kantor'],['receivables','Piutang'],['funds','Dana Tujuan'],['topCategories','Kategori Teratas'],
 ['categoryDonut','Donat Kategori'],['expenseTrend','Tren Pengeluaran'],
] as const;
type WidgetId=typeof dashboardOptions[number][0];
const known=new Set<string>(dashboardOptions.map(([id])=>id));
const defaultLayout:WidgetId[]=['free','budget','income','expenses','money','quickActions','inbox','upcoming','budgets','recent'];
const metricIds=new Set<WidgetId>(['free','budget','income','expenses','cashFlow','assets','netWorth','liabilities','reserved','safeDaily','daysUntilSalary']);

function AnalyticsWidget({id,navigate,defaultPeriod}:{id:'topCategories'|'categoryDonut'|'expenseTrend';navigate:(view:string)=>void;defaultPeriod:PeriodPreset}){
 const {data,profile}=useApp(),config=profile?.dashboardWidgetConfig?.[id],period=config?.period||defaultPeriod,range=resolvePeriodRange(period,profile?.salaryCycleStartDay||24,dateInTimeZone(new Date(),profile?.timeZone),profile?.dashboardCustom),history=usePeriodTransactions(range);
 const items=useMemo(()=>transactionsForCategory(history.items,data.categories,config?.categoryId||''),[history.items,data.categories,config?.categoryId]);const categories=useMemo(()=>categoryBreakdown(items,data.categories),[items,data.categories]),trend=useMemo(()=>groupTransactions(items,range,'auto'),[items,range.start,range.end]);
 const title=id==='topCategories'?'Kategori Teratas':id==='categoryDonut'?'Donat Kategori':'Tren Pengeluaran';
 return <details className="panel widget-details"><summary><strong>{title}</strong><small>{periodLabel(range)}</small></summary><div className="widget-body">{history.error&&<p className="form-error" role="alert">{history.error}</p>}{id==='topCategories'?categories.slice(0,6).map(c=><div className="budget-line" key={c.id}><IdentityBadge icon={c.icon} color={c.color} label={c.name}/><strong>{rupiah(c.amount)}</strong></div>):id==='categoryDonut'&&categories.length?<div className="chart-box"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={categories.slice(0,7)} dataKey="amount" nameKey="name" innerRadius="55%" outerRadius="80%">{categories.slice(0,7).map((c,i)=><Cell key={c.id} fill={c.color||`var(--chart-${i%6+1})`}/>)}</Pie><Tooltip formatter={v=>rupiah(Number(v))}/></PieChart></ResponsiveContainer></div>:id==='expenseTrend'&&trend.length?<div className="chart-box"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><XAxis dataKey="label" tick={{fontSize:10,fill:'var(--muted)'}}/><Tooltip formatter={v=>rupiah(Number(v))}/><Line dataKey="expense" name="Pengeluaran" stroke="var(--accent)" strokeWidth={3}/></LineChart></ResponsiveContainer></div>:null}{!categories.length&&id!=='expenseTrend'&&<Empty message={history.loading?'Memuat…':'Belum ada pengeluaran.'}/>}<button className="link-button" onClick={()=>navigate('analytics')}>Buka analisis →</button></div></details>;
}

export function Dashboard({openTx,navigate,notify}:{openTx:(preset?:Partial<LedgerTx>)=>void;navigate:(view:string)=>void;notify:(message:string)=>void}){
 const {data,profile,cycle,user}=useApp();const [customize,setCustomize]=useState(false),[picker,setPicker]=useState(false),[configure,setConfigure]=useState<string|null>(null),[pending,setPending]=useState<string[]|null>(null),[error,setError]=useState('');
 const period=profile?.dashboardPeriod||'salary_cycle';const range=resolvePeriodRange(period,profile?.salaryCycleStartDay||24,dateInTimeZone(new Date(),profile?.timeZone),profile?.dashboardCustom);
 const history=usePeriodTransactions(range);const summary=useMemo(()=>summarizeTransactions(history.items),[history.items]);const day=dateInTimeZone(new Date(),profile?.timeZone),today=todayInTimeZone(profile?.timeZone);
 const stat=useMemo(()=>metrics(data,cycle.start,cycle.end,profile?.salaryCycleStartDay,day),[data,cycle.start,cycle.end,profile?.salaryCycleStartDay,profile?.timeZone]);
 const current=(pending||profile?.dashboardWidgets?.length?pending||profile!.dashboardWidgets:defaultLayout).filter((key):key is WidgetId=>known.has(key));
 const selected=current.length?current:defaultLayout;const inbox=data.drafts.filter(d=>d.status==='pending');let weekEnd=today;for(let i=0;i<7;i++)weekEnd=nextDate(weekEnd);
 const due=upcomingEvents(data,profile!,{start:today,end:weekEnd}).filter(e=>e.kind!=='note');const committed=commitments(data,{start:today,end:cycle.end}).reduce((n,x)=>n+x.amount,0)+commitments(data).filter(x=>x.date<today).reduce((n,x)=>n+x.amount,0);
 const after=stat.free-(profile?.excludeCommittedFromAvailable===false?0:committed);
 const activeBudgets=data.budgets.filter(b=>b.active);const uniqueBudgets=activeBudgets.filter(b=>!b.subcategoryId||!activeBudgets.some(parent=>parent.categoryId===b.categoryId&&!parent.subcategoryId));const remaining=uniqueBudgets.reduce((sum,b)=>{const row=budgetCurrent(b,data.transactions,data.categories,day,profile?.salaryCycleStartDay||24);return sum+row.remaining-budgetCommitted(b,data,day,profile?.salaryCycleStartDay||24)},0);
 const amount:Partial<Record<WidgetId,number>>={free:stat.free,budget:remaining,income:summary.income,expenses:summary.expense,cashFlow:summary.cashFlow,assets:stat.assets,netWorth:stat.netWorth,liabilities:stat.liabilities,reserved:stat.reserved,safeDaily:Math.max(0,stat.discretionaryRemaining)/cycle.daysRemaining,daysUntilSalary:cycle.daysRemaining};
 async function save(changes:Parameters<typeof saveProfile>[1]){if(!user)return;setError('');try{await saveProfile(user.uid,changes)}catch(e){setPending(null);setError((e as Error).message||'Pengaturan belum tersimpan.')}}
 function layout(ids:string[]){setPending(ids);void save({dashboardWidgets:ids})}
 function move(from:string,to:string){layout(reorder(selected.map(id=>({id})),from,to).map(item=>item.id))}
 function setWidgetConfig(id:string,changes:{period?:PeriodPreset;categoryId?:string}){void save({dashboardWidgetConfig:{...(profile?.dashboardWidgetConfig||{}),[id]:{...(profile?.dashboardWidgetConfig?.[id]||{}),...changes}}})}
 function setPeriod(value:PeriodPreset){void save({dashboardPeriod:value})}
 function setCustom(value:DateRange){if(value.start<value.end)void save({dashboardCustom:value})}
 const label=(id:string)=>dashboardOptions.find(([key])=>key===id)?.[1]||id;
 function widget(id:WidgetId){
  if(metricIds.has(id))return <div className={'stat-card '+(id===(profile?.primaryMetric||'free')?'featured':'')}><span className="stat-label">{label(id)}</span><strong className="stat-value">{id==='daysUntilSalary'?amount[id]+' hari':history.loading&&['income','expenses','cashFlow'].includes(id)?'Memuat…':rupiah(amount[id]||0)}</strong><small>{['income','expenses','cashFlow'].includes(id)?periodLabel(range):id==='safeDaily'?'Dari sisa anggaran kebutuhan':'Kondisi saat ini'}</small></div>;
  if(id==='quickActions')return <QuickActions openTx={openTx} navigate={navigate} notify={notify}/>;
  if(id==='money')return <details className="panel widget-details"><summary><span><strong>Uang Tersedia</strong><small>Setelah komitmen</small></span><strong>{rupiah(after)}</strong></summary><div className="money-detail">{[['Total Aset',stat.assets],['Dicadangkan',-stat.reserved],['Uang Bebas',stat.free],['Komitmen Belum Dibayar',-committed],['Uang Bebas Setelah Komitmen',after],['Utang (ditampilkan terpisah)',stat.liabilities],['Aset Bersih',stat.netWorth]].map(([key,value])=><div key={key}><span>{key}</span><strong>{rupiah(value as number)}</strong></div>)}<small>Komitmen tidak mengubah saldo dompet.</small></div></details>;
  if(id==='inbox')return <details className="panel widget-details"><summary><span><strong>Perlu Dikonfirmasi</strong><small>{inbox.length} transaksi</small></span><strong>{rupiah(inbox.reduce((n,item)=>n+item.amount,0))}</strong></summary><div className="widget-body">{inbox.slice(0,4).map(item=><div className="budget-line" key={item.id}><span>{item.name}</span><strong>{rupiah(item.amount)}</strong></div>)}<button className="link-button" onClick={()=>navigate('inbox')}>Buka inbox →</button></div></details>;
  if(id==='upcoming')return <details className="panel widget-details"><summary><span><strong>7 Hari Mendatang</strong><small>Rencana · saldo belum berubah</small></span><strong>{rupiah(due.reduce((n,e)=>n+e.amount,0))}</strong></summary><div className="widget-body"><div className="budget-line"><span>Masuk {rupiah(due.reduce((n,e)=>n+Math.max(0,e.amount),0))}</span><span>Keluar {rupiah(due.reduce((n,e)=>n+Math.max(0,-e.amount),0))}</span></div>{due.slice(0,4).map(event=><div className="budget-line" key={event.id}><span>{event.date} · {event.title}</span><strong>{event.amount>=0?'+':'−'}{rupiah(Math.abs(event.amount))}</strong></div>)}<button className="link-button" onClick={()=>navigate('upcoming')}>Lihat jadwal →</button></div></details>;
  if(id==='budgets')return <details className="panel widget-details"><summary><strong>Anggaran Berjalan</strong><strong>{rupiah(remaining)}</strong></summary><div className="widget-body">{activeBudgets.slice(0,5).map(b=>{const s=budgetCurrent(b,data.transactions,data.categories,day,profile?.salaryCycleStartDay||24);return <div className="budget-line" key={b.id}><span>{b.name}</span><strong>{rupiah(s.remaining-budgetCommitted(b,data,day,profile?.salaryCycleStartDay||24))}</strong></div>})}<button className="link-button" onClick={()=>navigate('budgets')}>Lihat anggaran →</button></div></details>;
  if(id==='recent')return <details className="panel widget-details"><summary><strong>Transaksi Terbaru</strong><small>{data.transactions.length} ditampilkan</small></summary><div className="widget-body"><TxList items={data.transactions.slice(0,5)}/><button className="link-button" onClick={()=>navigate('transactions')}>Lihat semua →</button></div></details>;
  if(id==='wallets')return <details className="panel widget-details"><summary><strong>Saldo Dompet</strong><strong>{data.wallets.filter(w=>!w.isArchived).length} dompet</strong></summary><div className="widget-body">{data.wallets.filter(w=>!w.isArchived).sort((a,b)=>(a.displayOrder??0)-(b.displayOrder??0)).map(w=><div className="budget-line" key={w.id}><IdentityBadge icon={w.icon} color={w.color} label={w.name}/><strong>{rupiah(w.cachedBalance)}</strong></div>)}</div></details>;
  if(id==='claims'||id==='receivables'||id==='funds'){const items=id==='claims'?data.claims.map(x=>({id:x.id,name:x.name,value:x.remainingAmount})):id==='receivables'?data.receivables.map(x=>({id:x.id,name:x.person,value:x.remainingAmount})):data.funds.map(x=>({id:x.id,name:x.name,value:x.currentAmount}));return <details className="panel widget-details"><summary><strong>{label(id)}</strong><strong>{rupiah(items.reduce((n,x)=>n+x.value,0))}</strong></summary><div className="widget-body">{items.slice(0,5).map(row=><div className="budget-line" key={row.id}><span>{row.name}</span><strong>{rupiah(row.value)}</strong></div>)}<button className="link-button" onClick={()=>navigate(id==='claims'?'claims':id==='funds'?'funds':'receivables')}>Lihat rincian →</button></div></details>;}
  return <AnalyticsWidget id={id as 'topCategories'|'categoryDonut'|'expenseTrend'} navigate={navigate} defaultPeriod={period}/>;
 }
 return <><div className="dashboard-welcome"><div><small className="eyebrow ink">RINGKASAN UANG</small><h1>Halo, {profile?.displayName||profile?.username||'teman'} 👋</h1><p className="muted">Uangmu hari ini, lebih mudah dibaca.</p></div><div className="cycle-bar"><CalendarDays size={17}/><span>Siklus gaji</span><strong>{cycle.daysRemaining} hari lagi</strong></div></div><div className="dashboard-toolbar"><Button variant={customize?'secondary':'primary'} onClick={()=>{setCustomize(x=>!x);setPicker(false)}}><Settings2 size={16}/> {customize?'Selesai':'Atur Dashboard'}</Button>{customize&&<><Button variant="secondary" onClick={()=>setPicker(x=>!x)}>+ Tambah kartu</Button><button className="link-button" onClick={()=>layout([...defaultLayout])}>Atur ulang</button></>}</div>
 {customize&&picker&&<div className="panel widget-picker"><div className="budget-line"><h3>Pilih kartu</h3><button className="icon-btn" aria-label="Tutup pilihan" onClick={()=>setPicker(false)}><X size={18}/></button></div><div className="widget-picker-grid">{dashboardOptions.filter(([id])=>!selected.includes(id)).map(([id,name])=><button key={id} onClick={()=>{layout([...selected,id]);setPicker(false)}}>+ {name}</button>)}</div>{selected.length===dashboardOptions.length&&<p>Semua kartu sudah ditampilkan.</p>}</div>}
 {error&&<p className="form-error" role="alert">{error}</p>}<details className="panel dashboard-period"><summary>Periode angka dan grafik: {periodLabel(range)}</summary><PeriodSelector value={period} onChange={setPeriod} custom={profile?.dashboardCustom} onCustomChange={setCustom}/>{history.error&&<p role="alert" className="form-error">{history.error}</p>}</details>
 <div className="widget-grid">{selected.map((id,index)=><div key={id} data-sort-id={id} className={`${metricIds.has(id)?'widget-slot metric-slot':'widget-slot'} ${profile?.realisticMode&&id==='assets'?'deemphasized':''}`} onDragOver={e=>{if(customize){e.preventDefault();e.currentTarget.classList.add('sort-target')}}} onDragLeave={e=>e.currentTarget.classList.remove('sort-target')} onDrop={e=>{if(customize)dropRow(e,id,move)}}>{customize&&<div className="widget-controls"><ReorderHandle id={id} onMove={move}/><span>{label(id)}</span><button className="icon-btn" aria-label={`Naikkan ${label(id)}`} disabled={index===0} onClick={()=>move(id,selected[index-1])}><ArrowUp size={15}/></button><button className="icon-btn" aria-label={`Turunkan ${label(id)}`} disabled={index===selected.length-1} onClick={()=>move(id,selected[index+1])}><ArrowDown size={15}/></button>{['categoryDonut','topCategories','expenseTrend'].includes(id)&&<button className="icon-btn" aria-label={`Atur ${label(id)}`} onClick={()=>setConfigure(value=>value===id?null:id)}><Settings2 size={15}/></button>}<button className="icon-btn" aria-label={`Sembunyikan ${label(id)}`} disabled={selected.length===1} onClick={()=>layout(selected.filter(x=>x!==id))}><X size={15}/></button></div>}{customize&&configure===id&&<div className="panel widget-config"><strong>Atur {label(id)}</strong><div className="form-grid"><label>Periode<Select value={profile?.dashboardWidgetConfig?.[id]?.period||period} onChange={e=>setWidgetConfig(id,{period:e.target.value as PeriodPreset})}><option value="salary_cycle">Siklus gaji</option><option value="calendar_month">Bulan ini</option><option value="last_7_days">7 hari</option><option value="last_30_days">30 hari</option><option value="last_3_months">3 bulan</option></Select></label><label>Kategori<Select value={profile?.dashboardWidgetConfig?.[id]?.categoryId||''} onChange={e=>setWidgetConfig(id,{categoryId:e.target.value})}><option value="">Semua kategori</option>{data.categories.filter(c=>!c.isArchived&&c.type==='expense').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></label></div></div>}{widget(id)}</div>)}</div></>;
}
