'use client';
import { useState } from 'react';
import { ArrowDownLeft, ArrowLeftRight, ArrowUpRight } from 'lucide-react';
import { useApp } from './app-provider';
import { IdentityBadge } from './visual-identity';
import { Empty } from './fields';
import { rupiah } from '@/lib/accounting';
import type { LedgerTx } from '@/lib/types';

export const typeLabels:Record<string,string>={expense:'Pengeluaran',income:'Pemasukan',transfer:'Transfer',adjustment:'Koreksi',borrowing:'Pinjaman',debt_payment:'Bayar utang',claim_advance:'Talangan kantor',claim_payment:'Klaim cair',claim_writeoff:'Klaim ditolak',receivable_issue:'Talangan personal',receivable_payment:'Piutang dibayar',fund_contribution:'Dana tujuan'};
const moves=new Set(['transfer','fund_contribution']);
const listDate=(date:string)=>{const day=new Date(`${date}T12:00:00`);return day.toLocaleDateString('id-ID',day.getFullYear()===new Date().getFullYear()?{day:'numeric',month:'short'}:{day:'numeric',month:'short',year:'numeric'});};
export function TxList({items,onEdit}:{items:LedgerTx[];onEdit?:(tx:LedgerTx)=>void}){const {data}=useApp(),[expanded,setExpanded]=useState<string[]>([]);if(!items.length)return <Empty message="Belum ada transaksi pada periode ini."/>;return <div>{items.map(t=>{const cat=data.categories.find(c=>c.id===t.subcategoryId||c.id===t.categoryId);const pos=['income','claim_payment','receivable_payment','borrowing'].includes(t.type)||t.type==='adjustment'&&t.adjustmentDirection==='in';const move=moves.has(t.type);const splits=t.splits||[];const destination=move?data.wallets.find(w=>w.id===t.destinationWalletId)?.name:'';return <div key={t.id} className="transaction-row"><div className="data-row"><div className="row-left"><span className={`row-icon ${pos?'in':move?'':'out'}`} aria-hidden="true">{pos?<ArrowDownLeft size={17}/>:move?<ArrowLeftRight size={17}/>:<ArrowUpRight size={17}/>}</span><div className="data-row-main"><strong>{t.description||t.merchant||cat?.name||typeLabels[t.type]}</strong><small>{listDate(t.date)} · {typeLabels[t.type]} · {data.wallets.find(w=>w.id===t.walletId)?.name||'Dompet'}{destination?` → ${destination}`:''}{splits.length?` · ${splits.length} kategori`:''}{t.reconciliationReason?' · Penyesuaian saldo':''}</small>{(cat||splits.length>0)&&<IdentityBadge icon={cat?.icon} color={cat?.color} label={cat?.name||`${splits.length} kategori`}/>}</div></div><div className="data-row-side"><strong className={pos?'amount-positive':move?'':'amount-negative'}>{pos?'+':move?'':'−'}{rupiah(t.amount)}</strong>{t.type==='transfer'&&Boolean(t.transferFee)&&<small>Biaya admin {rupiah(t.transferFee||0)}</small>}{(splits.length>0||onEdit)&&<div className="toolbar-row">{splits.length>0&&<button type="button" className="link-button" aria-expanded={expanded.includes(t.id)} onClick={()=>setExpanded(rows=>rows.includes(t.id)?rows.filter(id=>id!==t.id):[...rows,t.id])}>{expanded.includes(t.id)?'Tutup pembagian':'Lihat pembagian'}</button>}{onEdit&&<button type="button" className="link-button" onClick={()=>onEdit(t)}>Detail</button>}</div>}</div></div>{expanded.includes(t.id)&&<div className="split-details">{splits.map((line,i)=><div key={i}><span>{data.categories.find(c=>c.id===line.categoryId)?.name||'Kategori'}{line.subcategoryId?` → ${data.categories.find(c=>c.id===line.subcategoryId)?.name||'Subkategori'}`:''}</span><strong>{rupiah(line.amount)}</strong></div>)}</div>}</div>})}</div>}
