'use client';
import { useMemo, useState } from 'react';
import { ArrowDownLeft, ArrowLeftRight, ArrowUpRight, CalendarDays, CircleDollarSign, HandCoins, Landmark, LockKeyhole, TrendingUp, Wallet } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useApp } from './app-provider';
import { IdentityBadge } from './visual-identity';
import { Empty } from './fields';
import { budgetCurrent, expenseAllocations, metrics, rupiah } from '@/lib/accounting';
import { budgetCommitted, commitments, upcomingEvents } from '@/lib/finance-control';
import type { LedgerTx } from '@/lib/types';
import { QuickActions } from './quick-actions';
import { PeriodSelector, usePeriodTransactions } from './period-selector';
import { dateInTimeZone, nextDate, periodLabel, resolvePeriodRange, summarizeTransactions, todayInTimeZone, type DateRange, type PeriodPreset } from '@/lib/period';
import { saveProfile } from '@/lib/firestore';
const typeLabels:Record<string,string>={expense:'Pengeluaran',income:'Pemasukan',transfer:'Transfer',adjustment:'Koreksi',borrowing:'Pinjaman',debt_payment:'Bayar utang',claim_advance:'Talangan kantor',claim_payment:'Klaim cair',claim_writeoff:'Klaim ditolak',receivable_issue:'Talangan personal',receivable_payment:'Piutang dibayar',fund_contribution:'Dana tujuan'};
const colors=Array.from({length:6},(_,index)=>`var(--chart-${index+1})`);
export function TxList({items,onEdit}:{items:LedgerTx[];onEdit?:(tx:LedgerTx)=>void}){const {data}=useApp(),[expanded,setExpanded]=useState<string[]>([]);if(!items.length)return <Empty message="Belum ada transaksi pada periode ini."/>;return <div>{items.map(t=>{const cat=data.categories.find(c=>c.id===t.subcategoryId||c.id===t.categoryId);const pos=['income','claim_payment','receivable_payment','borrowing'].includes(t.type)||t.type==='adjustment'&&t.adjustmentDirection==='in';const splits=t.splits||[];return <div key={t.id} className="transaction-row"><div className="data-row"><div className="row-left"><span className="row-icon">{pos?<ArrowDownLeft size={17}/>:t.type==='transfer'?<ArrowLeftRight size={17}/>:<ArrowUpRight size={17}/>}</span><div className="data-row-main"><strong>{t.description||t.merchant||cat?.name||typeLabels[t.type]}</strong><small>{new Date(t.date+'T12:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'short'})} · {typeLabels[t.type]} · {data.wallets.find(w=>w.id===t.walletId)?.name||'Dompet'}{splits.length?` · ${splits.length} kategori`:''}{t.reconciliationReason?' · Penyesuaian saldo':''}</small>{(cat||splits.length>0)&&<IdentityBadge icon={cat?.icon} color={cat?.color} label={cat?.name||`${splits.length} kategori`}/>}</div></div><div className="data-row-side"><strong className={pos?'amount-positive':t.type==='transfer'?'':'amount-negative'}>{pos?'+':t.type==='transfer'?'':'−'}{rupiah(t.amount)}</strong>{t.type==='transfer'&&Boolean(t.transferFee)&&<small>Biaya admin {rupiah(t.transferFee||0)}</small>}<div className="toolbar-row">{splits.length>0&&<button className="link-button" aria-expanded={expanded.includes(t.id)} onClick={()=>setExpanded(rows=>rows.includes(t.id)?rows.filter(id=>id!==t.id):[...rows,t.id])}>{expanded.includes(t.id)?'Tutup pembagian':'Lihat pembagian'}</button>}{onEdit&&<button className="link-button" onClick={()=>onEdit(t)}>Detail</button>}</div></div></div>{expanded.includes(t.id)&&<div className="split-details">{splits.map((line,i)=><div key={i}><span>{data.categories.find(c=>c.id===line.categoryId)?.name||'Kategori'}{line.subcategoryId?` → ${data.categories.find(c=>c.id===line.subcategoryId)?.name||'Subkategori'}`:''}</span><strong>{rupiah(line.amount)}</strong></div>)}</div>}</div>})}</div>}
export function Dashboard({openTx,navigate,notify}:{openTx:(preset?:Partial<LedgerTx>)=>void;navigate:(view:string)=>void;notify:(message:string)=>void}){const {data,profile,cycle,user}=useApp();const period=profile?.dashboardPeriod||'salary_cycle';const range=resolvePeriodRange(period,profile?.salaryCycleStartDay||24,dateInTimeZone(new Date(),profile?.timeZone),profile?.dashboardCustom);const history=usePeriodTransactions(range);const summary=useMemo(()=>summarizeTransactions(history.items),[history.items]);const stat=useMemo(()=>metrics(data,cycle.start,cycle.end,profile?.salaryCycleStartDay,dateInTimeZone(new Date(),profile?.timeZone)),[data,cycle,profile?.salaryCycleStartDay,profile?.timeZone]);const budgetRows=data.budgets.filter(b=>b.active).map(b=>({...b,...budgetCurrent(b,data.transactions,data.categories,dateInTimeZone(new Date(),profile?.timeZone),profile?.salaryCycleStartDay||24)}));const warning=(profile?.budgetWarningPercent||80)/100;const balanceCards=[
 {key:'assets',label:'Total aset cair',value:stat.assets,icon:Landmark,foot:'Saldo semua dompet tercatat'},
 {key:'netWorth',label:'Aset bersih',value:stat.netWorth,icon:TrendingUp,foot:'Termasuk piutang, setelah utang'},
 {key:'free',label:'Uang bebas',value:stat.free,icon:Wallet,foot:'Di luar dana yang dicadangkan'},
 {key:'budget',label:'Sisa anggaran',value:stat.budgetRemaining,icon:CircleDollarSign,foot:'Siklus ini'},
 {key:'income',label:'Pemasukan',value:history.loading||history.error?null:summary.income,icon:ArrowDownLeft,foot:history.loading?'Memuat periode…':periodLabel(range)},
 {key:'expenses',label:'Pengeluaran',value:history.loading||history.error?null:summary.expense,icon:ArrowUpRight,foot:history.loading?'Memuat periode…':periodLabel(range)},
 {key:'reserved',label:'Dana tercadangkan',value:stat.reserved,icon:LockKeyhole,foot:'Sudah punya tujuan'},
 {key:'liabilities',label:'Total utang',value:stat.liabilities,icon:HandCoins,foot:'Sisa kewajiban'},
 ];const selected=(profile?.dashboardWidgets?.length?balanceCards.filter(c=>profile.dashboardWidgets.includes(c.key)).sort((a,b)=>profile.dashboardWidgets.indexOf(a.key)-profile.dashboardWidgets.indexOf(b.key)):balanceCards).filter(card=>!profile?.realisticMode||card.key!=='assets').sort((a,b)=>profile?.realisticMode?(['free','budget','reserved','liabilities'].indexOf(a.key)<0?99:['free','budget','reserved','liabilities'].indexOf(a.key))-(['free','budget','reserved','liabilities'].indexOf(b.key)<0?99:['free','budget','reserved','liabilities'].indexOf(b.key)):0);
 const today=todayInTimeZone(profile?.timeZone);let weekEnd=today;for(let i=0;i<7;i++)weekEnd=nextDate(weekEnd);
 const pending=data.drafts.filter(d=>d.status==='pending');
 const committed=commitments(data,{start:today,end:cycle.end}).reduce((n,item)=>n+item.amount,0)+commitments(data).filter(item=>item.date<today).reduce((n,item)=>n+item.amount,0);
 const due=upcomingEvents(data,profile!,{start:today,end:weekEnd}).filter(e=>e.kind!=='note');
 const moneyAfter=stat.free-(profile?.excludeCommittedFromAvailable===false?0:committed);
 const categorySpending=data.categories.filter(c=>c.type==='expense'&&!c.parentId).map(c=>({name:c.name,value:history.items.flatMap(expenseAllocations).filter(line=>line.categoryId===c.id||data.categories.find(child=>child.id===line.categoryId||child.id===line.subcategoryId)?.parentId===c.id).reduce((n,line)=>n+line.amount,0)})).filter(c=>c.value>0).sort((a,b)=>b.value-a.value).slice(0,6);
 function setPeriod(value:PeriodPreset){if(user)void saveProfile(user.uid,{dashboardPeriod:value}).catch(e=>notify((e as Error).message));}
 function setCustom(value:DateRange){if(user&&value.start<value.end)void saveProfile(user.uid,{dashboardCustom:value}).catch(e=>notify((e as Error).message));}
 return <><div className="dashboard-welcome"><div><div className="eyebrow ink">RINGKASAN KEUANGAN</div><h1>Halo, {profile?.displayName||profile?.username||'teman'} <span aria-hidden="true">👋</span></h1><p className="muted" style={{marginTop:6}}>Lihat kondisi uangmu hari ini, tanpa tebak-tebakan.</p></div><div className="cycle-bar"><CalendarDays size={17}/><span>Siklus {new Date(cycle.start+'T12:00').toLocaleDateString('id-ID',{day:'numeric',month:'short'})} – {new Date(new Date(cycle.end+'T12:00').getTime()-86400000).toLocaleDateString('id-ID',{day:'numeric',month:'short'})}</span><strong>{cycle.daysRemaining} hari menuju gajian</strong></div></div>
 <div className="panel dashboard-period"><PeriodSelector value={period} onChange={setPeriod} custom={profile?.dashboardCustom} onCustomChange={setCustom} label="Periode pemasukan & pengeluaran"/>{history.loading&&<small role="status">Memuat transaksi periode ini…</small>}{history.error&&<small role="alert" className="form-error">{history.error}</small>}<small>Saldo, uang bebas, dan anggaran selalu menampilkan kondisi saat ini.</small></div>
 <div className="card-grid">{selected.map((card,i)=><div key={card.key} className={`stat-card ${card.key===(profile?.primaryMetric||'free')?'featured':''}`}><div className="stat-top"><span className="stat-label">{card.label}</span><span className="stat-icon"><card.icon size={17}/></span></div><div className="stat-value" title={card.value===null?history.error?'Tidak tersedia':'Memuat…':rupiah(card.value)}>{card.value===null?history.error?'Tidak tersedia':'Memuat…':rupiah(card.value)}</div><div className="stat-foot">{card.foot}</div></div>)}</div>
 <div className="dashboard-split financial-snapshot"><details className="panel" open={Boolean(profile?.realisticMode)}><summary><span><strong>Uang Gue Sebenarnya</strong><small>Uang Bebas Setelah Komitmen</small></span><strong>{rupiah(moneyAfter)}</strong></summary><div className="money-detail"><div><span>Total aset</span><strong>{rupiah(stat.assets)}</strong></div><div><span>Dana reserved</span><strong>{rupiah(stat.reserved)}</strong></div><div><span>Uang Bebas</span><strong>{rupiah(stat.free)}</strong></div><div><span>Utang (ditampilkan terpisah)</span><strong>{rupiah(stat.liabilities)}</strong></div><div><span>Komitmen belum dibayar</span><strong>{rupiah(committed)}</strong></div><div><span>Uang Bebas Setelah Komitmen</span><strong>{rupiah(moneyAfter)}</strong></div><div><span>Net Worth</span><strong>{rupiah(stat.netWorth)}</strong></div><small>Komitmen belum mengurangi saldo aktual. Pilihan tampilannya ada di Pengaturan.</small></div></details><div className="panel"><div className="budget-line"><strong>Perlu Dikonfirmasi</strong><button className="link-button" onClick={()=>navigate('inbox')}>Buka inbox →</button></div><p>{pending.length} transaksi · {rupiah(pending.reduce((n,item)=>n+item.amount,0))}</p>{pending.slice(0,3).map(d=><div className="budget-line" key={d.id}><small>{d.name}</small><strong>{rupiah(d.amount)}</strong></div>)}{!pending.length&&<small>Belum ada yang menunggu konfirmasi.</small>}</div></div>
 <div className="panel" style={{marginTop:16}}><div className="budget-line"><div><h3>7 Hari Mendatang</h3><small>Perkiraan · belum mengubah saldo</small></div><button className="link-button" onClick={()=>navigate('upcoming')}>Lihat arus kas →</button></div><div className="kpi-strip" style={{marginTop:13}}><div><small>Estimasi masuk</small><strong>{rupiah(due.reduce((n,e)=>n+Math.max(e.amount,0),0))}</strong></div><div><small>Estimasi keluar</small><strong>{rupiah(due.reduce((n,e)=>n+Math.max(-e.amount,0),0))}</strong></div><div><small>Net</small><strong>{rupiah(due.reduce((n,e)=>n+e.amount,0))}</strong></div></div>{due.slice(0,4).map(event=><div className="budget-line" key={event.id}><small>{event.date} · {event.title} · {event.status==='pending'?'Menunggu Konfirmasi':'Rencana'}</small><strong>{event.amount>0?'+':'−'}{rupiah(Math.abs(event.amount))}</strong></div>)}</div>
 <QuickActions openTx={openTx} navigate={navigate} notify={notify}/>
 <div className="section-heading"><h2>Anggaran & aktivitas</h2><button className="link-button" onClick={()=>navigate('budgets')}>Lihat anggaran →</button></div><div className="dashboard-split"><div className="panel flush"><div className="panel-header"><div><h3>Anggaran berjalan</h3><small>Sisa aman per hari {rupiah(Math.max(0,stat.discretionaryRemaining)/cycle.daysRemaining)}</small></div><span className={`tag ${stat.budgetRemaining<0?'danger':stat.budgetRemaining<stat.totalBudget*(1-warning)?'warn':''}`}>{stat.budgetRemaining<0?'OVER BUDGET':stat.budgetRemaining<stat.totalBudget*(1-warning)?'WASPADA':'AMAN'}</span></div>{budgetRows.length?budgetRows.slice(0,5).map(b=><div className="data-row" key={b.id}><div className="data-row-main" style={{width:'100%'}}><div className="budget-line"><strong>{b.name}</strong><strong>{rupiah(b.remaining-budgetCommitted(b,data,dateInTimeZone(new Date(),profile?.timeZone),profile?.salaryCycleStartDay||24))}</strong></div><div className="progress-track budget-progress" style={{marginTop:9}}><div className={`progress-fill ${b.spent>b.amount?'over':b.spent/Math.max(1,b.available)>warning?'warn':''}`} style={{width:`${Math.min(100,b.spent/Math.max(1,b.available)*100)}%`}}/><div className="progress-fill committed" style={{width:`${Math.min(100,Math.max(0,100-b.spent/Math.max(1,b.available)*100),budgetCommitted(b,data,dateInTimeZone(new Date(),profile?.timeZone),profile?.salaryCycleStartDay||24)/Math.max(1,b.available)*100)}%`}}/></div><small>Aktual {rupiah(b.spent)} · Komitmen {rupiah(budgetCommitted(b,data,dateInTimeZone(new Date(),profile?.timeZone),profile?.salaryCycleStartDay||24))} · Budget {rupiah(b.available)}</small></div></div>):<Empty message="Buat anggaran pertama untuk memantau pengeluaran."/>}</div><div className="panel flush"><div className="panel-header"><div><h3>Transaksi terbaru</h3><small>Aktivitas yang baru tercatat</small></div><button className="link-button" onClick={()=>navigate('transactions')}>Semua →</button></div><TxList items={data.transactions.slice(0,5)}/></div></div>
 <div className="section-heading"><h2>Ke mana uang keluar?</h2><button className="link-button" onClick={()=>navigate('analytics')}>Lihat analisis →</button></div><div className="dashboard-split"><div className="panel"><h3>Pengeluaran per kategori</h3>{categorySpending.length?<div className="chart-box"><ResponsiveContainer width="100%" height="100%"><BarChart data={categorySpending} margin={{top:18,right:10,bottom:30,left:0}}><CartesianGrid vertical={false} stroke="var(--line)"/><XAxis dataKey="name" tick={{fill:'var(--muted)',fontSize:11}} angle={-14} textAnchor="end"/><YAxis tickFormatter={n=>`${Math.round(n/1000)}k`} tick={{fill:'var(--muted)',fontSize:11}}/><Tooltip formatter={v=>rupiah(Number(v))}/><Bar dataKey="value" radius={[6,6,0,0]}>{categorySpending.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Bar></BarChart></ResponsiveContainer></div>:<Empty message={history.error|| (history.loading?'Memuat grafik…':'Belum ada pengeluaran pada periode ini.')}/>}</div><div className="panel"><h3 style={{marginBottom:17}}>Dompetmu</h3><div className="mini-list">{data.wallets.filter(w=>!w.isArchived).slice(0,6).map(w=><div key={w.id}><span><strong>{w.name}</strong><small>{w.isReserved?'Dana tercadangkan':w.purpose||'Uang tersedia'}</small></span><strong>{rupiah(w.cachedBalance)}</strong></div>)}</div>{data.wallets.length===0&&<Empty message="Tambahkan dompet agar saldo mulai terlihat."/>}</div></div></>;
}
