'use client';
import { Summary } from './summary';
import { ListChecks as SumListChecks, ShieldCheck as SumShieldCheck, Wallet as SumWallet } from 'lucide-react';
import { useState } from 'react';
import { useApp } from './app-provider';
import { Button } from './ui/button';
import { Empty } from './fields';
import { WalletControls } from './wallet-controls';
import { scanData, type HealthIssue } from '@/lib/finance-control';
import { loadAllTransactions } from '@/lib/firestore';

export { CycleHistory } from './cycle-history';

export function DataHealth({notify}:{notify:(s:string)=>void}){const {data,profile,user}=useApp();const [issues,setIssues]=useState<HealthIssue[]|null>(null),[ledgerCount,setLedgerCount]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[wallet,setWallet]=useState<string|null>(null),[mode,setMode]=useState<'reconcile'|'recalculate'>('recalculate');async function scan(){if(!user||!profile)return;setBusy(true);setError('');try{const ledger=await loadAllTransactions(user.uid);setLedgerCount(ledger.length);setIssues(scanData(data,ledger,profile))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <><div className="page-heading"><div><h1>Periksa Data</h1><p>Periksa data tanpa mengubah transaksi atau saldo. Pilih perbaikan setelah melihat masalahnya.</p></div><div className="heading-actions"><Button onClick={()=>void scan()} disabled={busy}>{busy?'Memeriksa…':'Periksa Data'}</Button></div></div>{!issues&&!busy&&<div className="panel"><Empty message="Tekan “Periksa Data” untuk memeriksa saldo dompet, kategori, dan tautan catatan."/></div>}{issues&&<><Summary items={[{label:'Transaksi diperiksa',value:ledgerCount,icon:SumListChecks,tone:'accent'},{label:'Dompet diperiksa',value:data.wallets.length,icon:SumWallet,tone:'accent'},{label:'Status',value:issues.length?'Perlu Diperiksa':'Baik',icon:SumShieldCheck,tone:'accent'}]}/><div className="panel flush" style={{marginTop:17}}>{issues.length?issues.map(issue=><div className="data-row" key={issue.id}><div className="data-row-main"><strong>{issue.title}</strong><small>Dampak: {issue.impact}</small><small>Saran: {issue.action}</small></div>{issue.walletId&&<div className="data-row-side"><div className="toolbar-row"><button type="button" className="link-button" onClick={()=>{setWallet(issue.walletId!);setMode('recalculate')}}>Samakan saldo</button><button type="button" className="link-button" onClick={()=>{setWallet(issue.walletId!);setMode('reconcile')}}>Cocokkan saldo</button></div></div>}</div>):<Empty message="Semua pemeriksaan yang tersedia selesai tanpa masalah."/>}</div></>}{error&&<p role="alert" className="form-error">{error}</p>}<WalletControls walletId={wallet} mode={mode} onClose={()=>setWallet(null)} onDone={message=>{notify(message);void scan()}}/></>}
