'use client';
import { useMemo, useState, type FormEvent } from 'react';
import { Archive, ArrowDown, ArrowUp, Edit3, MoreHorizontal, Plus } from 'lucide-react';
import { useApp } from './app-provider';
import { Button } from './ui/button';
import { Confirm } from './ui/alert-dialog';
import { Dialog, DialogContent } from './ui/dialog';
import { Empty, Field, FormActions, Input, Money, Select } from './fields';
import { WalletControls } from './wallet-controls';
import { ContextNotes } from './context-notes';
import { archiveOrDelete, mergeCategory, saveDisplayOrder, saveRecord, saveWallet } from '@/lib/firestore';
import { rupiah } from '@/lib/accounting';
import type { Category, Wallet } from '@/lib/types';
import { IdentityBadge, VisualPicker, emojiOrFallback, identityStyle } from './visual-identity';
import { dropRow, ReorderHandle, reorder } from './reorder-handle';

type Props={notify:(message:string)=>void};
const types: [Category['type'],string][]=[['expense','Pengeluaran'],['income','Pemasukan'],['savings','Tabungan'],['debt','Utang'],['receivable','Piutang'],['reimbursement','Klaim kantor']];
export function WalletsView({notify}:Props){
 const {data,user}=useApp();const [editing,setEditing]=useState<Wallet|null>(null),[open,setOpen]=useState(false),[name,setName]=useState(''),[type,setType]=useState<Wallet['type']>('bank'),[opening,setOpening]=useState(0),[purpose,setPurpose]=useState(''),[icon,setIcon]=useState('💳'),[color,setColor]=useState('#267e73'),[style,setStyle]=useState<'soft'|'solid'>('soft'),[reserved,setReserved]=useState(false),[spendable,setSpendable]=useState(true),[include,setInclude]=useState(true),[canPay,setCanPay]=useState(true),[receive,setReceive]=useState(true),[out,setOut]=useState(true),[into,setInto]=useState(true),[order,setOrder]=useState<string[]>([]),[error,setError]=useState(''),[saving,setSaving]=useState(false),[control,setControl]=useState<{id:string;mode:'reconcile'|'recalculate'}|null>(null);
 const wallets=useMemo(()=>data.wallets.filter(w=>!w.isArchived).map((w,i)=>({...w,position:w.displayOrder??i})).sort((a,b)=>{const ai=order.indexOf(a.id),bi=order.indexOf(b.id);return ai>=0&&bi>=0?ai-bi:ai>=0?-1:bi>=0?1:a.position-b.position}),[data.wallets,order]);
 async function act(fn:()=>Promise<unknown>,message:string,close=false){setSaving(true);setError('');try{await fn();notify(message);if(close)setOpen(false)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 function edit(w?:Wallet){setEditing(w||null);setName(w?.name||'');setType(w?.type||'bank');setOpening(w?.openingBalance||0);setPurpose(w?.purpose||'');setIcon(emojiOrFallback(w?.icon,'💳'));setColor(w?.color||'#267e73');setStyle(w?.cardStyle||'soft');setReserved(w?.isReserved||false);setSpendable(w?.isSpendable??true);setInclude(w?.includeInNetWorth??true);setCanPay(w?.canPay??true);setReceive(w?.canReceive??true);setOut(w?.canTransferOut??true);setInto(w?.canTransferIn??true);setError('');setOpen(true)}
 function submit(event:FormEvent){event.preventDefault();if(!user)return;void act(()=>saveWallet(user.uid,{name,type,openingBalance:opening,purpose,icon,color,cardStyle:style,isReserved:reserved,isSpendable:spendable,includeInNetWorth:include,canPay,canReceive:receive,canTransferOut:out,canTransferIn:into,displayOrder:editing?.displayOrder??wallets.length},editing?.id),editing?'Dompet diperbarui.':'Dompet ditambahkan.',true)}
 function move(from:string,to:string){if(!user)return;const ids=reorder(wallets,from,to).map(w=>w.id);if(ids.join()===wallets.map(w=>w.id).join())return;setOrder(ids);void saveDisplayOrder(user.uid,'wallets',ids).then(()=>notify('Urutan dompet disimpan.')).catch(e=>{setOrder([]);setError(e.message)})}
 return <><div className="page-heading"><div><h1>Dompet & rekening</h1><p>Lihat saldo, atur tampilan, dan tentukan kegunaan setiap dompet.</p></div><Button onClick={()=>edit()}><Plus size={16}/> Tambah dompet</Button></div><div className="entity-grid wallet-grid">{wallets.map((w,index)=><div key={w.id} data-sort-id={w.id} className={'wallet-card identity-wallet '+(w.cardStyle==='solid'?'wallet-solid':'')} style={identityStyle(w.color)} onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add('sort-target')}} onDragLeave={e=>e.currentTarget.classList.remove('sort-target')} onDrop={e=>dropRow(e,w.id,move)}><div className="wallet-top"><span className="wallet-emoji" aria-hidden="true">{emojiOrFallback(w.icon,'💳')}</span><div className="row-actions"><ReorderHandle id={w.id} onMove={move}/><span className="tag">{w.isReserved?'Dicadangkan':w.type==='ewallet'?'E-wallet':w.type==='cash'?'Tunai':'Dompet'}</span></div></div><div><h3>{w.name}</h3>{w.purpose&&<small>{w.purpose}</small>}</div><div><div className="wallet-balance">{rupiah(w.cachedBalance)}</div><small>Saldo saat ini</small></div><div className="wallet-bottom"><button className="link-button" onClick={()=>edit(w)}><Edit3 size={14}/> Edit</button><details className="more-actions"><summary aria-label={`Pilihan untuk ${w.name}`}><MoreHorizontal size={19}/><span> Lainnya</span></summary><div className="more-menu"><button onClick={()=>setControl({id:w.id,mode:'reconcile'})}>Cocokkan saldo</button><button onClick={()=>setControl({id:w.id,mode:'recalculate'})}>Hitung ulang saldo</button><button disabled={index===0} onClick={()=>move(w.id,wallets[index-1].id)}>Naikkan urutan</button><button disabled={index===wallets.length-1} onClick={()=>move(w.id,wallets[index+1].id)}>Turunkan urutan</button><Confirm title="Arsipkan dompet?" description="Jika pernah dipakai, riwayat dompet tetap tersimpan." onConfirm={()=>user?act(()=>archiveOrDelete(user.uid,'wallets',w.id,data),'Dompet diarsipkan.'):undefined}><button><Archive size={14}/> Arsipkan</button></Confirm></div></details></div><ContextNotes kind="wallets" id={w.id} notes={w.contextNotes} notify={notify}/></div>)}</div>{!wallets.length&&<Empty message="Belum ada dompet. Tambahkan rekening atau uang tunai."/>}{error&&<p className="form-error" role="alert">{error}</p>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent title={editing?'Ubah dompet':'Tambah dompet'}><form className="form-stack" onSubmit={submit}><div className="form-grid"><Field label="Nama"><Input required value={name} onChange={e=>setName(e.target.value)} placeholder="Contoh: Jago"/></Field><Field label="Jenis"><Select value={type} onChange={e=>setType(e.target.value as Wallet['type'])}>{[['bank','Bank'],['cash','Tunai'],['ewallet','E-wallet'],['savings','Tabungan'],['credit','Kredit'],['investment','Investasi'],['other','Lainnya']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></Field><Field label="Saldo awal" hint="Jika diubah, saldo sekarang ikut disesuaikan."><Money value={opening} onChange={setOpening}/></Field><Field label="Tujuan (opsional)"><Input value={purpose} onChange={e=>setPurpose(e.target.value)}/></Field></div><VisualPicker kind="wallet" icon={icon} color={color} onIcon={setIcon} onColor={setColor}/><Field label="Tampilan kartu"><Select value={style} onChange={e=>setStyle(e.target.value as 'soft'|'solid')}><option value="soft">Lembut</option><option value="solid">Berwarna</option></Select></Field><details className="disclosure"><summary>Pengaturan kegunaan dompet</summary><div className="form-stack"><label className="check-row"><input type="checkbox" checked={canPay} onChange={e=>setCanPay(e.target.checked)}/> Bisa membayar</label><label className="check-row"><input type="checkbox" checked={receive} onChange={e=>setReceive(e.target.checked)}/> Bisa menerima uang</label><label className="check-row"><input type="checkbox" checked={out} onChange={e=>setOut(e.target.checked)}/> Bisa transfer keluar</label><label className="check-row"><input type="checkbox" checked={into} onChange={e=>setInto(e.target.checked)}/> Bisa menerima transfer</label><label className="check-row"><input type="checkbox" checked={spendable} onChange={e=>setSpendable(e.target.checked)}/> Hitung dalam uang bebas</label><label className="check-row"><input type="checkbox" checked={reserved} onChange={e=>setReserved(e.target.checked)}/> Dana dicadangkan</label><label className="check-row"><input type="checkbox" checked={include} onChange={e=>setInclude(e.target.checked)}/> Hitung dalam aset bersih</label></div></details>{error&&<p className="form-error" role="alert">{error}</p>}<FormActions saving={saving} onCancel={()=>setOpen(false)}/></form></DialogContent></Dialog><WalletControls walletId={control?.id||null} mode={control?.mode||'reconcile'} onClose={()=>setControl(null)} onDone={notify}/></>;
}

export function CategoriesView({notify}:Props){
 const {data,user}=useApp();const [open,setOpen]=useState(false),[editing,setEditing]=useState<Category|null>(null),[name,setName]=useState(''),[kind,setKind]=useState<Category['type']>('expense'),[parent,setParent]=useState(''),[icon,setIcon]=useState('🗂️'),[color,setColor]=useState('#267e73'),[merge,setMerge]=useState(''),[expanded,setExpanded]=useState<string[]>([]),[groups,setGroups]=useState<Category['type'][]>(['expense']),[order,setOrder]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const active=useMemo(()=>data.categories.filter(c=>!c.isArchived).sort((a,b)=>{const ai=order.indexOf(a.id),bi=order.indexOf(b.id);return ai>=0&&bi>=0?ai-bi:ai>=0?-1:bi>=0?1:(a.sortOrder??0)-(b.sortOrder??0)||a.name.localeCompare(b.name)}),[data.categories,order]);
 function edit(c?:Category){setEditing(c||null);setName(c?.name||'');setKind(c?.type||'expense');setParent(c?.parentId||'');setIcon(emojiOrFallback(c?.icon));setColor(c?.color||'#267e73');setMerge('');setError('');setOpen(true)}
 async function act(fn:()=>Promise<unknown>,message:string,close=false){setBusy(true);setError('');try{await fn();notify(message);if(close)setOpen(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function submit(event:FormEvent){event.preventDefault();if(!user)return;void act(()=>saveRecord(user.uid,'categories',{name:name.trim(),type:kind,parentId:parent||null,icon,color,isArchived:false,sortOrder:editing?.sortOrder??active.length},editing?.id),editing?'Kategori diperbarui.':'Kategori ditambahkan.',true)}
 function move(from:string,to:string){if(!user)return;const a=active.find(c=>c.id===from),b=active.find(c=>c.id===to);if(!a||!b||a.type!==b.type||a.parentId!==b.parentId)return;const ids=reorder(active.filter(c=>c.type===a.type&&c.parentId===a.parentId),from,to).map(c=>c.id);setOrder(reorder(active,from,to).map(c=>c.id));void saveDisplayOrder(user.uid,'categories',ids).then(()=>notify('Urutan kategori disimpan.')).catch(e=>{setOrder([]);setError(e.message)})}
 const parents=active.filter(c=>!c.parentId);function toggle(id:string){setExpanded(rows=>rows.includes(id)?rows.filter(x=>x!==id):[...rows,id])}
 function row(c:Category,siblings:Category[],index:number){const children=active.filter(child=>child.parentId===c.id),isOpen=expanded.includes(c.id);return <div key={c.id} className="category-tree-node" data-sort-id={c.id} onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add('sort-target')}} onDragLeave={e=>e.currentTarget.classList.remove('sort-target')} onDrop={e=>dropRow(e,c.id,move)}><div className="data-row category-row"><div className="row-left"><ReorderHandle id={c.id} onMove={move}/><span className="category-emoji" style={identityStyle(c.color)} aria-hidden="true">{emojiOrFallback(c.icon)}</span><div className="data-row-main"><strong>{c.name}</strong><small>{c.parentId?'Subkategori':children.length?`${children.length} subkategori`:'Kategori utama'}</small></div></div><div className="row-actions">{children.length>0&&<button className="icon-btn" aria-label={`${isOpen?'Tutup':'Buka'} ${c.name}`} aria-expanded={isOpen} onClick={()=>toggle(c.id)}>{isOpen?'−':'+'}</button>}<button className="icon-btn" aria-label={`Naikkan ${c.name}`} disabled={!index} onClick={()=>move(c.id,siblings[index-1].id)}><ArrowUp size={15}/></button><button className="icon-btn" aria-label={`Turunkan ${c.name}`} disabled={index===siblings.length-1} onClick={()=>move(c.id,siblings[index+1].id)}><ArrowDown size={15}/></button><button className="icon-btn" aria-label={`Edit ${c.name}`} onClick={()=>edit(c)}><Edit3 size={15}/></button></div></div>{isOpen&&children.length>0&&<div className="category-children">{children.map((child,i)=>row(child,children,i))}</div>}</div>}
 return <><div className="page-heading"><div><h1>Kategori</h1><p>Atur kategori dan subkategori sesuai kebutuhanmu.</p></div><Button onClick={()=>edit()}><Plus size={16}/> Tambah kategori</Button></div><div className="toolbar-row category-toolbar"><button className="link-button" onClick={()=>{setExpanded(parents.map(c=>c.id));setGroups(types.map(([key])=>key))}}>Buka semua</button><button className="link-button" onClick={()=>{setExpanded([]);setGroups([])}}>Tutup semua</button></div>{types.map(([key,label])=>{const list=parents.filter(c=>c.type===key);return list.length?<details className="panel category-group" key={key} open={groups.includes(key)}><summary onClick={event=>{event.preventDefault();setGroups(current=>current.includes(key)?current.filter(group=>group!==key):[...current,key])}}><strong>{label}</strong><span>{list.length} kategori</span></summary><div className="category-group-body">{list.map((c,i)=>row(c,list,i))}</div></details>:null})}{!active.length&&<Empty message="Belum ada kategori. Mulai dengan membuat kategori pengeluaran."/>}{error&&<p className="form-error" role="alert">{error}</p>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent title={editing?'Ubah kategori':'Tambah kategori'}><form className="form-stack" onSubmit={submit}><Field label="Nama"><Input required value={name} onChange={e=>setName(e.target.value)}/></Field><div className="form-grid"><Field label="Jenis"><Select value={kind} onChange={e=>{setKind(e.target.value as Category['type']);setParent('')}}>{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></Field><Field label="Di bawah kategori"><Select value={parent} onChange={e=>setParent(e.target.value)}><option value="">Kategori utama</option>{parents.filter(c=>c.type===kind&&c.id!==editing?.id).map(c=><option key={c.id} value={c.id}>{emojiOrFallback(c.icon)} {c.name}</option>)}</Select></Field></div><VisualPicker kind="category" icon={icon} color={color} onIcon={setIcon} onColor={setColor}/>{editing&&<details className="disclosure"><summary>Gabungkan kategori</summary><p className="muted">Pindahkan transaksi lama ke kategori lain. Periksa tujuan sebelum melanjutkan.</p><Select value={merge} onChange={e=>setMerge(e.target.value)}><option value="">Pilih kategori tujuan</option>{active.filter(c=>c.id!==editing.id&&c.type===editing.type&&Boolean(c.parentId)===Boolean(editing.parentId)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select>{merge&&<Confirm title="Gabungkan kategori?" description="Kategori pada transaksi lama dan anggaran akan dipindahkan." onConfirm={()=>user?act(()=>mergeCategory(user.uid,editing,active.find(c=>c.id===merge)!),'Kategori digabung.',true):undefined}><Button type="button" variant="secondary">Gabungkan</Button></Confirm>}<Confirm title="Arsipkan kategori?" description="Transaksi lama tidak akan dihapus." onConfirm={()=>user?act(()=>archiveOrDelete(user.uid,'categories',editing.id,data),'Kategori diarsipkan.',true):undefined}><button type="button" className="link-button">Arsipkan kategori</button></Confirm></details>}{error&&<p className="form-error" role="alert">{error}</p>}<FormActions saving={busy} onCancel={()=>setOpen(false)}/></form></DialogContent></Dialog></>;
}
