'use client';
import { isEmergencyFund, isKantong, kantongWallets, pocketEmoji } from '@/lib/pockets';
import { PocketSheet, type PocketStart } from './pockets';
import { Emoji, EmojiText } from './emoji';
import { Coins as SumCoins, CreditCard as SumCreditCard, Hourglass as SumHourglass } from 'lucide-react';
import { useEffect, useMemo, useRef, useState, type ChangeEvent, type FormEvent } from 'react';
import { Ban, CalendarDays, Check, ChevronRight, Download, Edit3, Hourglass, Layers, MoreHorizontal, Paperclip, Percent, Repeat, Trash2, Plus, Search, SlidersHorizontal, Upload, X } from 'lucide-react';
import { GlassHero, GlassRing, closeMenu, dueText } from './glass';
import { useApp } from './app-provider';
import { useNotify } from './notifications';
import { Empty, Field, FormActions, Input, Money, Select, categoryOptions } from './fields';
import { categoryTree, categoryTypesFor } from '@/lib/category-analytics';
import { Button } from './ui/button';
import { Dialog, DialogContent } from './ui/dialog';
import { Confirm } from './ui/alert-dialog';
import { TxList, typeLabels } from './dashboard';
import { emojiOrFallback } from './visual-identity';
import { ContextNotes } from './context-notes';
import { ManualPayments, SettleDialog, type SettleTarget } from './settle-dialog';
import { walletAllows } from '@/lib/wallet-capabilities';
import { PeriodSelector, usePeriodTransactions } from './period-selector';
import { dateInTimeZone, formatDate, periodLabel, resolvePeriodRange, summarizeTransactions, todayInTimeZone, type DateRange, type PeriodPreset } from '@/lib/period';
import { archiveOrDelete, createClaim, createDebt, saveRecord, editOpeningRecord, deleteOpeningRecord, attachClaimReceipt, claimReceiptUrl, rejectClaim, updateLinked, loadAllTransactions } from '@/lib/firestore';
import { newestFirst, rupiah, transactionExpense } from '@/lib/accounting';
import { savingsPlan, savingsStatusText } from '@/lib/savings';
import type { Claim, Debt, Fund, LedgerTx } from '@/lib/types';
type Props={notify:(text:string)=>void;openTx:(preset?:Partial<LedgerTx>,editing?:LedgerTx)=>void;revision?:number};
function Heading({title,detail,children}:{title:string;detail:string;children?:React.ReactNode}){return <div className="page-heading"><div><h1>{title}</h1><p>{detail}</p></div><div className="heading-actions">{children}</div></div>}
function useAction(notify:(message:string)=>void){const {track}=useNotify();const [saving,setSaving]=useState(false),[error,setError]=useState('');async function perform(action:()=>Promise<unknown>,success:string,after?:()=>void,reopen?:()=>void){if(after&&reopen){after();track(action(),{pending:'Menyimpan…',success,failure:'Belum tersimpan',retry:{label:'Buka lagi',run:reopen}});return;}setError('');setSaving(true);try{await action();notify(success);after?.();}catch(e){if((e as {committed?:boolean}).committed){notify((e as Error).message);after?.()}else setError((e as Error).message||'Tindakan gagal.');}finally{setSaving(false);}}return {saving,error,perform,setError};}
function Failure({message}:{message:string}){return message?<p role="alert" className="form-error">{message}</p>:null}
const PAGE=50;
const claimStatus:Record<Claim['status'],string>={draft:'Draf',submitted:'Diajukan',waiting:'Menunggu cair',approved:'Disetujui',paid:'Sudah cair',rejected:'Ditolak'};
const claimSteps:Claim['status'][]=['draft','submitted','waiting','approved','paid'];
const stepLabels:Partial<Record<Claim['status'],string>>={draft:'Draf',submitted:'Diajukan',waiting:'Menunggu',approved:'Disetujui',paid:'Cair'};
/** Tujuan dana cards cycle through these colours; dana darurat is always warm orange. */
const fundTones=['var(--accent)','#7a5bc9','#3a78d6','#2f9e6e','#d4568a','#c98a1c'];

export function TransactionsView({notify,openTx,revision,focus:rawFocus}:Props&{focus?:string}){
 const {data,user,profile}=useApp();
 // Links from Beranda look like `type:expense@2026-08-27..2026-09-26`: a filter plus the period that was shown.
 const [focus,focusRange]=(rawFocus||'').split('@'),[focusStart,focusEnd]=(focusRange||'').split('..');const linkedRange=focusStart&&focusEnd&&focusStart<focusEnd?{start:focusStart,end:focusEnd}:undefined;const [panel,setPanel]=useState<'period'|'filter'|null>(null);const searchRef=useRef<HTMLInputElement>(null);
 const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[type,setType]=useState(()=>focus?.startsWith('type:')?focus.slice(5):focus?.startsWith('category:')?'expense':'all'),[walletFilter,setWalletFilter]=useState(()=>focus?.startsWith('wallet:')?focus.slice(7):''),[categoryFilter,setCategoryFilter]=useState(()=>focus?.startsWith('category:')?focus.slice(9):''),[sort,setSort]=useState<'newest'|'oldest'|'highest'>('newest');
 useEffect(()=>{const timer=setTimeout(()=>setQuery(search.trim().toLocaleLowerCase('id-ID')),250);return()=>clearTimeout(timer)},[search]);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{const target=event.target as HTMLElement|null;if(event.key==='/'&&!target?.closest('input,textarea,[contenteditable="true"],[role="dialog"]')){event.preventDefault();searchRef.current?.focus()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 const [period,setPeriod]=useState<PeriodPreset>(linkedRange?'custom':'salary_cycle');
 const [custom,setCustom]=useState<DateRange|undefined>(linkedRange);
 const [allHistory,setAllHistory]=useState(false);
 const [error,setError]=useState('');
 const [all,setAll]=useState<{uid:string;items:LedgerTx[]}|null>(null),[loadingAll,setLoadingAll]=useState(false),[limit,setLimit]=useState(PAGE);
 const range=resolvePeriodRange(period,profile?.salaryCycleStartDay||24,dateInTimeZone(new Date(),profile?.timeZone),custom);
 const history=usePeriodTransactions(range);
 const complete=all?.uid===user?.uid?all?.items||null:null;
 useEffect(()=>{if(all&&user&&all.uid===user.uid){const uid=user.uid;void loadAllTransactions(uid).then(items=>setAll({uid,items})).catch(e=>setError(e.message));}},[revision]);
 const source=allHistory?(complete||[]):history.items;
 const filtered=useMemo(()=>source.filter(t=>{
  if(type!=='all'&&t.type!==type)return false;
  if(walletFilter&&t.walletId!==walletFilter&&t.destinationWalletId!==walletFilter)return false;
  if(categoryFilter==='uncategorized'?(transactionExpense(t)<=0||Boolean(t.categoryId)||(t.splits||[]).some(line=>line.categoryId)):categoryFilter&&!([t.categoryId,t.subcategoryId,t.transferFeeCategoryId,...(t.splits||[]).flatMap(line=>[line.categoryId,line.subcategoryId])].some(id=>id===categoryFilter||data.categories.find(c=>c.id===id)?.parentId===categoryFilter)))return false;
  const categoryNames=[t.categoryId,t.subcategoryId,t.transferFeeCategoryId,...(t.splits||[]).flatMap(line=>[line.categoryId,line.subcategoryId])].map(id=>data.categories.find(c=>c.id===id)?.name||'');
  const text=[t.description,t.merchant,t.notes,t.amount,t.tags?.join(' ')||'',data.wallets.find(w=>w.id===t.walletId)?.name,data.wallets.find(w=>w.id===t.destinationWalletId)?.name,...categoryNames].join(' ').toLocaleLowerCase('id-ID');
  return text.includes(query);
 }).sort((a,b)=>sort==='highest'?b.amount-a.amount||newestFirst(a,b):sort==='oldest'?newestFirst(b,a):newestFirst(a,b)),[data.categories,data.wallets,source,query,type,walletFilter,categoryFilter,sort]);
 useEffect(()=>setLimit(PAGE),[query,type,walletFilter,categoryFilter,sort,allHistory,period,custom?.start,custom?.end]);
 const shown=filtered.slice(0,limit);
 async function csv(){if(!user)return;try{const rows=(await loadAllTransactions(user.uid)).sort(newestFirst).map(t=>[t.date,typeLabels[t.type]||t.type,data.wallets.find(w=>w.id===t.walletId)?.name||'',data.wallets.find(w=>w.id===t.destinationWalletId)?.name||'',(t.splits?.length?t.splits.map(line=>`${data.categories.find(c=>c.id===line.categoryId)?.name||'Kategori'} ${line.amount}`).join(' + '):data.categories.find(c=>c.id===(t.subcategoryId||t.categoryId))?.name||data.categories.find(c=>c.id===t.categoryId)?.name||''),t.merchant,t.description,t.amount,t.notes,t.tags?.join('|')||'']);const safe=(v:unknown)=>`"${String(v??'').replace(/^[=+@\-]/,"'$&").replaceAll('"','""')}"`;const text=[['Tanggal','Jenis','Dompet','Tujuan','Kategori','Merchant','Keterangan','Nominal','Catatan','Tag'],...rows].map(row=>row.map(safe).join(',')).join('\r\n');const blob=new Blob(['\ufeff',text],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='dompet-ajaib-transaksi.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);notify('CSV berhasil diunduh.');}catch(e){setError((e as Error).message);}}

 async function loadHistory(){if(!user)return;setLoadingAll(true);setError('');try{const items=await loadAllTransactions(user.uid);setAll({uid:user.uid,items});setAllHistory(true);notify('Seluruh riwayat dimuat.')}catch(e){setError((e as Error).message)}finally{setLoadingAll(false)}}
 return <><Heading title="Transaksi" detail="Ketuk transaksi untuk melihat detail atau mengubahnya."><button type="button" className="icon-btn csv-button" onClick={()=>void csv()} aria-label="Unduh CSV seluruh riwayat" title="Unduh CSV seluruh riwayat"><Download size={17}/><span>CSV</span></button></Heading>
  {(()=>{const typeOptions=Object.entries(typeLabels);const activeCount=[type!=='all',Boolean(walletFilter),Boolean(categoryFilter)].filter(Boolean).length;const chips:[string,()=>void][]=[...(type!=='all'?[[typeLabels[type]||type,()=>setType('all')] as [string,()=>void]]:[]),...(walletFilter?[[`${emojiOrFallback(data.wallets.find(w=>w.id===walletFilter)?.icon,'👛')} ${data.wallets.find(w=>w.id===walletFilter)?.name||'Dompet'}`,()=>setWalletFilter('')] as [string,()=>void]]:[]),...(categoryFilter?[[`${emojiOrFallback(data.categories.find(c=>c.id===categoryFilter)?.icon)} ${data.categories.find(c=>c.id===categoryFilter)?.name||(categoryFilter==='uncategorized'?'Tanpa kategori':'Kategori')}`,()=>setCategoryFilter('')] as [string,()=>void]]:[])];const year=String(new Date().getFullYear()),full=periodLabel(range),shortLabel=range.start.startsWith(year)&&range.end.startsWith(year)?full.replace(new RegExp(` ${year}`,'g'),''):full;const toggle=(next:'period'|'filter')=>setPanel(current=>current===next?null:next);return <div className="tx-toolbar">
   <label className="search-box"><Search size={19} aria-hidden="true"/><input ref={searchRef} className="search-input" type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari nama, kategori, dompet, atau nominal" aria-label="Cari transaksi" autoComplete="off" enterKeyHint="search"/>{search?<button type="button" className="search-clear" aria-label="Hapus pencarian" onClick={()=>{setSearch('');setQuery('');searchRef.current?.focus()}}><X size={16}/></button>:<kbd className="search-kbd" aria-hidden="true">/</kbd>}</label>
   <div className="tx-toolbar-actions"><button type="button" className={`chip-button ${panel==='period'?'is-open':''}`} aria-expanded={panel==='period'} onClick={()=>toggle('period')}><CalendarDays size={16}/><span>{allHistory?'Seluruh riwayat':shortLabel}</span></button><button type="button" className={`chip-button filter-toggle ${panel==='filter'||activeCount?'is-open':''}`} aria-label="Filter transaksi" aria-expanded={panel==='filter'} onClick={()=>toggle('filter')}><SlidersHorizontal size={16}/><span>Filter</span>{activeCount>0&&<b className="chip-count">{activeCount}</b>}</button><Select value={sort} onChange={e=>setSort(e.target.value as 'newest'|'oldest'|'highest')} aria-label="Urutkan transaksi" className="sort-select" menuWidth={190}><option value="newest">Terbaru</option><option value="oldest">Terlama</option><option value="highest">Nominal terbesar</option></Select></div>
   {panel==='period'&&<div className="tx-panel"><div className="segmented" role="group" aria-label="Rentang riwayat"><button type="button" aria-pressed={!allHistory} className={!allHistory?'active':''} onClick={()=>setAllHistory(false)}>Per periode</button><button type="button" aria-pressed={allHistory} className={allHistory?'active':''} disabled={loadingAll} onClick={()=>complete?setAllHistory(true):void loadHistory()}>{loadingAll?'Memuat…':'Seluruh riwayat'}</button></div>{!allHistory&&<PeriodSelector value={period} onChange={setPeriod} custom={custom} onCustomChange={setCustom} label="Periode"/>}</div>}
   {panel==='filter'&&<div className="tx-panel tx-filter-panel"><Field label="Jenis"><Select value={type} onChange={e=>{const next=e.target.value,allowed=categoryTypesFor(next==='all'?'':next);setType(next);if(categoryFilter&&allowed&&!categoryTree(data.categories,allowed).some(row=>row.category.id===categoryFilter))setCategoryFilter('')}} aria-label="Jenis transaksi"><option value="all">Semua jenis</option>{typeOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></Field><Field label="Dompet"><Select value={walletFilter} onChange={e=>setWalletFilter(e.target.value)} aria-label="Filter dompet"><option value="">Semua dompet</option>{data.wallets.map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</Select></Field><Field label="Kategori"><Select value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)} aria-label="Filter kategori"><option value="">Semua kategori</option>{categoryOptions(data.categories,categoryTypesFor(type==='all'?'':type),true)}</Select></Field>{activeCount>0&&<button type="button" className="link-button" onClick={()=>{setType('all');setWalletFilter('');setCategoryFilter('')}}>Hapus filter</button>}</div>}
   {chips.length>0&&<div className="filter-chips">{chips.map(([label,clear])=><button type="button" key={label} className="filter-chip" onClick={clear} aria-label={`Hapus filter ${label}`}><EmojiText text={label}/><X size={13}/></button>)}</div>}
  </div>})()}
  {!(!allHistory&&history.loading)&&filtered.length>0&&(()=>{const total=summarizeTransactions(filtered);return <div className="tx-summary"><div><small>Masuk</small><strong className="amount-positive">{rupiah(total.income)}</strong></div><div><small>Keluar</small><strong className="amount-negative">{rupiah(total.expense)}</strong></div><div><small>Selisih</small><strong>{rupiah(total.cashFlow)}</strong></div><div><small>Transaksi</small><strong>{filtered.length}</strong></div></div>})()}
  {query&&<p className="search-summary" role="status">Hasil pencarian “{search.trim()}”: {source.length} transaksi → {filtered.length} hasil <button className="link-button" onClick={()=>{setSearch('');setQuery('')}}>Hapus pencarian</button></p>}
  {!allHistory&&history.loading?<div className="panel" role="status">Memuat transaksi periode ini…</div>:filtered.length?<div className={`tx-results ${sort==='highest'?'panel flush':''}`}><TxList items={shown} groupByDate={sort!=='highest'} onEdit={t=>openTx(undefined,t)}/>{filtered.length>shown.length&&<div className="list-more"><Button variant="secondary" onClick={()=>setLimit(n=>n+PAGE)}>Tampilkan {Math.min(PAGE,filtered.length-shown.length)} lagi</Button></div>}</div>:<div className="panel"><Empty message={query?`Tidak ada transaksi yang cocok dengan “${search.trim()}” pada filter ini.`:'Tidak ada transaksi pada filter ini.'} action={query&&<Button variant="secondary" onClick={()=>{setSearch('');setQuery('')}}>Hapus pencarian</Button>}/></div>}
  <Failure message={error||(!allHistory&&history.error)||''}/><small>{allHistory?`Pencarian mencakup seluruh transaksi · menampilkan ${shown.length} dari ${filtered.length}.`:`Menampilkan ${shown.length} dari ${filtered.length} transaksi sesuai filter. CSV mencakup seluruh riwayat.`}</small>
 </>;
}
export function ClaimsView({notify,openTx}:Props){const {track}=useNotify();const {data,user,profile}=useApp(),[open,setOpen]=useState(false),[name,setName]=useState(''),[amount,setAmount]=useState(0),[source,setSource]=useState(''),[date,setDate]=useState(''),[expected,setExpected]=useState(''),[description,setDescription]=useState(''),action=useAction(notify);const [editing,setEditing]=useState<Claim|null>(null);const outstanding=data.claims.filter(c=>c.status!=='rejected').reduce((n,c)=>n+c.remainingAmount,0);const active=data.claims.filter(c=>c.status!=='rejected'&&c.remainingAmount>0).length;
 const claims=useMemo(()=>[...data.claims].sort((a,b)=>Number(b.remainingAmount>0)-Number(a.remainingAmount>0)||b.submissionDate.localeCompare(a.submissionDate)),[data.claims]);
 function edit(c?:Claim){setEditing(c||null);setName(c?.name||'');setAmount(c?.amount||0);setSource(c?.sourceWalletId||'');setDate(c?.submissionDate||todayInTimeZone(profile?.timeZone));setExpected(c?.expectedPaymentDate||'');setDescription(c?.description||'');action.setError('');setOpen(true)}
 function submit(e:FormEvent){e.preventDefault();if(!user)return;void action.perform(()=>editing?editOpeningRecord(user.uid,'claims',editing.id,{name,expectedPaymentDate:expected,description},amount):createClaim(user.uid,{name,amount,sourceWalletId:source,submissionDate:date,expectedPaymentDate:expected,paidDate:'',status:'submitted',description,notes:''}),editing?`Klaim ${name} diperbarui.`:`Talangan kantor ${name} ${rupiah(amount)} dicatat.`,()=>setOpen(false),()=>setOpen(true));}
 function attach(c:Claim,e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(user&&file)void action.perform(()=>attachClaimReceipt(user.uid,c.id,file),'Lampiran tersimpan.')}
 return <><Heading title="Klaim kantor" detail="Uang yang kamu talangi dan menunggu penggantian dari kantor."><Button onClick={()=>edit()}><Plus size={16}/> Catat klaim</Button></Heading>{(()=>{const today=todayInTimeZone(profile?.timeZone),claimed=data.claims.filter(c=>c.status!=='rejected').reduce((n,c)=>n+c.amount,0);return <GlassHero tone="claim" icon={SumHourglass} label="Belum cair" value={rupiah(outstanding)} detail={active?`${active} klaim aktif · ${data.claims.length} catatan`:data.claims.length?'Semua klaim sudah selesai.':'Belum ada klaim kantor.'} progress={claimed?(claimed-outstanding)/claimed*100:undefined} progressLabel={claimed?`Sudah cair ${rupiah(claimed-outstanding)} dari ${rupiah(claimed)}`:undefined}/>})()}<div className="section-heading"><h2>Daftar klaim</h2></div><Failure message={open?'':action.error}/>{claims.length?<div className="gl-list">{claims.map(c=>{const today=todayInTimeZone(profile?.timeZone),rejected=c.status==='rejected',done=!rejected&&c.remainingAmount<=0,current=claimSteps.indexOf(done?'paid':c.status),due=c.expectedPaymentDate?dueText(c.expectedPaymentDate,today):null;return <article className={`gl-card tone-claim ${rejected?'is-rejected':done?'is-done':''}`} key={c.id}>
  <header className="gl-card-head"><span className="gl-avatar" aria-hidden="true"><Emoji e="🧾"/></span><div className="gl-card-title"><strong>{c.name}</strong><small>{c.description||`Diajukan ${formatDate(c.submissionDate)}`}</small></div><span className={`gl-pill ${rejected?'is-bad':done?'is-done':c.status==='waiting'?'is-warn':c.status==='draft'?'is-muted':''}`}>{claimStatus[done?'paid':c.status]}</span></header>
  <div className="gl-amount"><div><small>{rejected?'Ditolak, jadi pengeluaranmu':done?'Sudah cair':'Belum cair'}</small><strong>{rupiah(rejected||done?c.amount:c.remainingAmount)}</strong></div>{!rejected&&!done&&c.remainingAmount!==c.amount&&<span>dari {rupiah(c.amount)}</span>}</div>
  {!rejected&&<ol className="gl-steps" aria-label="Status klaim">{claimSteps.map((step,i)=><li key={step} className={i<current?'done':i===current?'now':''}><button type="button" disabled={!user||done||step==='paid'||i===current} aria-current={i===current?'step':undefined} title={step==='paid'?'Tercatat otomatis saat pencairan dicatat':`Tandai ${stepLabels[step]?.toLowerCase()}`} onClick={()=>{if(user)void action.perform(()=>updateLinked(user.uid,'claims',c.id,{status:step}),`Klaim ${c.name}: ${stepLabels[step]}.`)}}><i aria-hidden="true">{i<current&&<Check size={11}/>}</i>{stepLabels[step]}</button></li>)}</ol>}
  <div className="gl-chips"><span><CalendarDays size={13}/> Diajukan {formatDate(c.submissionDate)}</span>{c.expectedPaymentDate&&!done&&!rejected&&<span className={due&&due.days<0?'is-late':''}><Hourglass size={13}/> Perkiraan cair {formatDate(c.expectedPaymentDate)}{due?` · ${due.text}`:''}</span>}{c.attachmentPath&&<button type="button" className="gl-chip-link" onClick={()=>void action.perform(async()=>{const url=await claimReceiptUrl(c.attachmentPath!);window.open(url,'_blank','noopener,noreferrer')},'Lampiran dibuka.')}><Paperclip size={13}/> Lihat lampiran</button>}</div>
  <div className="gl-actions">{!done&&!rejected?<Button type="button" className="small" onClick={()=>openTx({type:'claim_payment',claimId:c.id,amount:c.remainingAmount,description:`Klaim ${c.name} cair`})}>Catat pencairan</Button>:<span className="gl-actions-note">{rejected?'Klaim ditolak':'Klaim sudah selesai'}</span>}<details className="more-actions"><summary aria-label={`Pilihan untuk ${c.name}`}><MoreHorizontal size={18}/><span> Lainnya</span></summary><div className="more-menu"><button type="button" onClick={e=>{closeMenu(e);edit(c)}}><Edit3 size={14}/> Ubah klaim</button><label><Upload size={14}/> {c.attachmentPath?'Ganti lampiran':'Unggah lampiran'}<input type="file" accept=".pdf,image/png,image/jpeg,image/webp" hidden onChange={e=>{e.currentTarget.closest('details')?.removeAttribute('open');attach(c,e)}}/></label>{!done&&!rejected&&<Confirm title="Tolak klaim ini?" description="Sisa klaim dicatat sebagai pengeluaranmu sendiri. Saldo dompet tidak berkurang lagi." onConfirm={()=>{if(user)void action.perform(()=>rejectClaim(user.uid,c.id),'Klaim ditolak dan dicatat sebagai pengeluaran.')}}><button type="button" onClick={closeMenu}><Ban size={14}/> Tolak klaim</button></Confirm>}<Confirm title="Hapus klaim?" description="Hanya klaim yang belum pernah cair yang bisa dihapus." onConfirm={()=>{if(user)track(deleteOpeningRecord(user.uid,'claims',c.id),{pending:'Menghapus klaim…',success:'Klaim dihapus.',failure:'Klaim belum terhapus'})}}><button type="button" onClick={closeMenu}><Trash2 size={14}/> Hapus klaim</button></Confirm></div></details></div>
  <ContextNotes kind="claims" id={c.id} notes={c.contextNotes} legacy={c.notes} notify={notify}/>
 </article>})}</div>:<div className="panel"><Empty message="Belum ada klaim kantor."/></div>}<Dialog open={open} onOpenChange={setOpen}><DialogContent title={editing?'Ubah klaim':'Catat klaim kantor'}><form className="form-stack" onSubmit={submit}><div className="notice">Uang keluar dari dompet asal dan menunggu diganti kantor. Saat klaim cair, catat pencairannya sekali saja.</div><Field label="Nama klaim"><Input required value={name} onChange={e=>setName(e.target.value)} placeholder="Contoh: Perjalanan dinas"/></Field><div className="form-grid"><Field label="Nominal"><Money value={amount} onChange={setAmount} required/></Field><Field label="Dompet asal"><Select required disabled={!!editing} value={source} onChange={e=>setSource(e.target.value)}><option value="">Pilih dompet</option>{data.wallets.filter(w=>walletAllows(w,'pay')||editing?.sourceWalletId===w.id).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select></Field><Field label="Tanggal pengajuan"><Input type="date" required disabled={!!editing} value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Perkiraan cair"><Input type="date" value={expected} onChange={e=>setExpected(e.target.value)}/></Field></div><Field label="Keterangan"><Input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Opsional"/></Field><Failure message={action.error}/><FormActions saving={action.saving} onCancel={()=>setOpen(false)}/></form></DialogContent></Dialog></>;
}
export function DebtsView({notify,openTx}:Props){const {track}=useNotify();const {data,user,profile}=useApp(),[open,setOpen]=useState(false),[name,setName]=useState(''),[provider,setProvider]=useState(''),[amount,setAmount]=useState(0),[due,setDue]=useState(''),[interest,setInterest]=useState(0),[installment,setInstallment]=useState(0),[creditWallet,setCreditWallet]=useState(''),action=useAction(notify),[editing,setEditing]=useState<Debt|null>(null),[settle,setSettle]=useState<SettleTarget|null>(null);
 function edit(d?:Debt){setEditing(d||null);setName(d?.name||'');setProvider(d?.provider||'');setAmount(d?.originalAmount||0);setDue(d?.dueDate||'');setInterest(d?.interestRate||0);setInstallment(d?.installmentAmount||0);setCreditWallet('');action.setError('');setOpen(true)}
 function submit(e:FormEvent){e.preventDefault();if(!user)return;const rate=Number.isFinite(interest)&&interest>=0?interest:0;void action.perform(()=>editing?editOpeningRecord(user.uid,'debts',editing.id,{name,provider,dueDate:due,interestRate:rate,installmentAmount:installment},amount):createDebt(user.uid,{name,provider,originalAmount:amount,dueDate:due,interestRate:rate,installmentAmount:installment,notes:''},creditWallet||undefined),editing?`Utang ${name} diperbarui.`:`Utang ${name} ${rupiah(amount)} dicatat.`,()=>setOpen(false),()=>setOpen(true));}
 return <><Heading title="Utang & cicilan" detail="Catat utang dan cicilannya. Pembayaran bisa lewat dompet atau dicatat tanpa dompet."><Button onClick={()=>edit()}><Plus size={16}/> Catat utang</Button></Heading>{(()=>{const active=data.debts.filter(d=>d.outstandingAmount>0),owed=data.debts.reduce((n,d)=>n+d.outstandingAmount,0),borrowed=data.debts.reduce((n,d)=>n+d.originalAmount,0),monthly=active.reduce((n,d)=>n+Math.min(d.installmentAmount||0,d.outstandingAmount),0);return <GlassHero tone="debt" icon={SumCreditCard} label="Total sisa utang" value={rupiah(owed)} detail={active.length?`${active.length} utang aktif${monthly?` · cicilan ${rupiah(monthly)}/bulan`:''}`:data.debts.length?'Semua utang sudah lunas.':'Belum ada utang.'} progress={borrowed?(borrowed-owed)/borrowed*100:undefined} progressLabel={borrowed?`Sudah dibayar ${rupiah(borrowed-owed)} dari ${rupiah(borrowed)}`:undefined}/>})()}<div className="section-heading"><h2>Daftar utang</h2></div><Failure message={open?'':action.error}/>{data.debts.length?<div className="gl-list">{[...data.debts].sort((a,b)=>Number(b.outstandingAmount>0)-Number(a.outstandingAmount>0)||(a.dueDate||'9999').localeCompare(b.dueDate||'9999')).map(d=>{const done=d.outstandingAmount<=0,paid=d.originalAmount?Math.min(100,(d.originalAmount-d.outstandingAmount)/d.originalAmount*100):0,due=d.dueDate?dueText(d.dueDate,todayInTimeZone(profile?.timeZone)):null;return <article className={`gl-card tone-debt ${done?'is-done':''}`} key={d.id}>
  <header className="gl-card-head"><span className="gl-avatar" aria-hidden="true"><Emoji e="💳"/></span><div className="gl-card-title"><strong>{d.name}</strong><small>{d.provider||'Utang'}</small></div><span className={`gl-pill ${done?'is-done':''}`}>{done?'Lunas':'Aktif'}</span></header>
  <div className="gl-amount"><div><small>{done?'Sudah lunas':'Sisa utang'}</small><strong>{rupiah(d.outstandingAmount)}</strong></div><span>dari {rupiah(d.originalAmount)}</span></div>
  <div className="gl-progress"><div className="gl-bar" aria-hidden="true"><i style={{width:`${paid}%`}}/></div><small>Terbayar {Math.round(paid)}% · {rupiah(d.originalAmount-d.outstandingAmount)}</small></div>
  {(d.dueDate||d.installmentAmount>0||d.interestRate>0)&&<div className="gl-chips">{d.dueDate&&<span className={!done&&due&&due.days<0?'is-late':''}><CalendarDays size={13}/> Jatuh tempo {formatDate(d.dueDate)}{!done&&due?` · ${due.text}`:''}</span>}{d.installmentAmount>0&&<span><Repeat size={13}/> Cicilan {rupiah(d.installmentAmount)}</span>}{d.interestRate>0&&<span><Percent size={13}/> Bunga {d.interestRate}%/tahun</span>}</div>}
  <div className="gl-actions">{done?<span className="gl-actions-note">Utang ini sudah lunas</span>:<Button type="button" className="small" onClick={()=>setSettle({kind:'debts',id:d.id,name:d.name,remaining:d.outstandingAmount,suggested:Math.min(d.installmentAmount||d.outstandingAmount,d.outstandingAmount)})}>Bayar cicilan</Button>}<details className="more-actions"><summary aria-label={`Pilihan untuk ${d.name}`}><MoreHorizontal size={18}/><span> Lainnya</span></summary><div className="more-menu"><button type="button" onClick={e=>{closeMenu(e);edit(d)}}><Edit3 size={14}/> Ubah utang</button><Confirm title="Hapus utang?" description="Hanya utang tanpa pembayaran dapat dihapus." onConfirm={()=>{if(user)track(deleteOpeningRecord(user.uid,'debts',d.id),{pending:'Menghapus utang…',success:'Utang dihapus.',failure:'Utang belum terhapus'})}}><button type="button" onClick={closeMenu}><Trash2 size={14}/> Hapus utang</button></Confirm></div></details></div>
  <ManualPayments kind="debts" id={d.id} payments={d.manualPayments}/>
  <ContextNotes kind="debts" id={d.id} notes={d.contextNotes} legacy={d.notes} notify={notify}/>
 </article>})}</div>:<div className="panel"><Empty message="Belum ada utang yang dicatat."/></div>}<SettleDialog target={settle} onClose={()=>setSettle(null)}/><Dialog open={open} onOpenChange={setOpen}><DialogContent title={editing?'Ubah utang':'Catat utang'}><form className="form-stack" onSubmit={submit}><div className="form-grid"><Field label="Nama utang"><Input required value={name} onChange={e=>setName(e.target.value)} placeholder="Contoh: Cicilan laptop"/></Field><Field label="Penyedia"><Input value={provider} onChange={e=>setProvider(e.target.value)} placeholder="Opsional"/></Field><Field label="Nominal"><Money value={amount} onChange={setAmount} required/></Field><Field label="Jatuh tempo"><Input type="date" value={due} onChange={e=>setDue(e.target.value)}/></Field><Field label="Bunga tahunan (%)"><Input type="number" min="0" step="0.01" inputMode="decimal" value={interest} onChange={e=>setInterest(Number(e.target.value))}/></Field><Field label="Cicilan"><Money value={installment} onChange={setInstallment}/></Field>{!editing&&<Field label="Dana pinjaman masuk ke dompet"><Select value={creditWallet} onChange={e=>setCreditWallet(e.target.value)}><option value="">Tanpa dompet (catat utangnya saja)</option>{data.wallets.filter(w=>walletAllows(w,'receive')).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select></Field>}</div><Failure message={action.error}/><FormActions saving={action.saving} onCancel={()=>setOpen(false)}/></form></DialogContent></Dialog></>;
}
export function FundsView({notify,openTx}:Props){const {data,user,profile}=useApp(),{track}=useNotify(),[pocket,setPocket]=useState<PocketStart|null>(null),funds=data.funds.filter(f=>!f.isArchived),today=todayInTimeZone(profile?.timeZone),[open,setOpen]=useState(false),[editing,setEditing]=useState<Fund|null>(null),[name,setName]=useState(''),[target,setTarget]=useState(0),[monthly,setMonthly]=useState(0),[linked,setLinked]=useState(''),[date,setDate]=useState(''),[kind,setKind]=useState<'emergency'|'goal'>('goal'),action=useAction(notify);function edit(f?:Fund){setEditing(f||null);setName(f?.name||'');setTarget(f?.targetAmount||0);setMonthly(f?.monthlyContribution||0);setLinked(f?.linkedWalletId||'');setDate(f?.targetDate||'');setKind(f&&isEmergencyFund(f)?'emergency':'goal');action.setError('');setOpen(true)}function submit(e:FormEvent){e.preventDefault();if(!user)return;void action.perform(()=>saveRecord(user.uid,'funds',{name,kind,targetAmount:target,...(editing?{}:{currentAmount:0}),monthlyContribution:monthly,targetDate:date,linkedWalletId:linked,notes:editing?.notes||''},editing?.id),editing?`Tujuan dana ${name} diperbarui.`:`Tujuan dana ${name} dibuat.`,()=>setOpen(false),()=>setOpen(true));}
 return <><Heading title="Tujuan dana & target tabungan" detail="Tentukan target dan tenggatnya. Aplikasi menghitung setoran yang perlu per bulan dan per minggu."><Button onClick={()=>edit()}><Plus size={16}/> Buat target</Button></Heading><PocketSheet open={Boolean(pocket)} start={pocket||undefined} onOpenChange={v=>{if(!v)setPocket(null)}}/>{funds.length>0&&(()=>{const plans=funds.map(f=>savingsPlan(f,today)),saved=funds.reduce((n,f)=>n+f.currentAmount,0),goal=funds.reduce((n,f)=>n+f.targetAmount,0);return <GlassHero tone="fund" icon={SumCoins} label="Terkumpul" value={rupiah(saved)} detail={`${funds.length} tujuan · target total ${rupiah(goal)}`} progress={goal?saved/goal*100:undefined} progressLabel={goal?`${Math.round(Math.min(100,saved/goal*100))}% dari semua target`:undefined} stats={[['Sisa menuju target',rupiah(plans.reduce((n,p)=>n+p.remaining,0))],['Perlu disetor per bulan',rupiah(plans.reduce((n,p)=>n+(p.status==='reached'||p.status==='overdue'?0:p.perMonth),0))]]}/>})()}<div className="pocket-hint gl-note"><span className="pocket-hint-icon"><Layers size={18}/></span><div><strong>Kantong</strong><small>Kelompokkan dompet untuk satu tujuan, misalnya <b>Dana darurat = Mandiri + BRI</b>. Saldo kantong otomatis mengikuti saldo dompet di dalamnya.</small><div className="pocket-hint-wallets"><button type="button" onClick={()=>setPocket({mode:'list'})}>Lihat kantong<ChevronRight size={14}/></button><button type="button" onClick={()=>setPocket({mode:'form'})}><Plus size={14}/>Kantong baru</button></div></div></div><Failure message={open?'':action.error}/>{funds.length?<div className="gl-list">{funds.map((f,index)=>{const progress=f.targetAmount?Math.min(100,f.currentAmount/f.targetAmount*100):0,wallet=data.wallets.find(w=>w.id===f.linkedWalletId),plan=savingsPlan(f,today),[label,tone]=savingsStatusText[plan.status],emergency=isEmergencyFund(f),kantong=isKantong(f);return <article className={`gl-card gl-fund ${emergency?'is-emergency':''}`} style={{'--tone':emergency?'#e0603a':fundTones[index%fundTones.length]} as React.CSSProperties} key={f.id}>
  <header className="gl-card-head"><span className="gl-avatar is-big" aria-hidden="true"><Emoji e={pocketEmoji(f)}/></span><div className="gl-card-title"><strong>{f.name}</strong><small>{emergency&&<em className="gl-tag">Dana darurat</em>}{kantong?`Kantong: ${kantongWallets(f,data.wallets).map(w=>w.name).join(' + ')}`:wallet?`Disetor ke ${wallet.name}`:'Belum ada dompet tujuan'}</small></div><span className="row-actions"><button type="button" className="icon-btn" aria-label={`Ubah ${f.name}`} onClick={()=>kantong?setPocket({mode:'form',fundId:f.id}):edit(f)}><Edit3 size={16}/></button><Confirm title={`Hapus ${f.name}?`} description={f.currentAmount>0?'Riwayat setoran tetap tersimpan. Uangnya tetap ada di dompet, tapi tidak lagi dihitung sebagai dana yang disimpan.':'Tujuan dana ini akan dihapus. Saldo dompet tidak berubah.'} confirmLabel="Ya, hapus" onConfirm={()=>{if(user)track(archiveOrDelete(user.uid,'funds',f.id,data),{pending:'Menghapus tujuan dana…',success:'Tujuan dana dihapus.',failure:'Tujuan dana belum terhapus'})}}><button type="button" className="icon-btn" aria-label={`Hapus ${f.name}`}><Trash2 size={16}/></button></Confirm></span></header>
  <div className="gl-fund-body"><GlassRing value={progress}/><div className="gl-fund-amounts"><small>Terkumpul</small><strong>{rupiah(f.currentAmount)}</strong><span>dari target {rupiah(f.targetAmount)}</span>{f.targetDate&&<span>Tenggat {formatDate(f.targetDate)}</span>}</div></div>
  <div className="gl-plan"><div className="gl-plan-head"><span className={`gl-pill ${tone==='good'?'is-done':tone==='warn'?'is-warn':tone==='bad'?'is-bad':'is-muted'}`}>{label}</span>{plan.daysLeft!==null&&plan.status!=='reached'&&<small>{plan.daysLeft>=0?`${plan.daysLeft} hari lagi`:'Tenggat sudah lewat'}</small>}</div>{plan.status!=='reached'&&plan.monthsLeft&&plan.daysLeft!>=0?<div className="gl-need"><div><small>Perlu per bulan</small><strong>{rupiah(plan.perMonth)}</strong></div><div><small>Perlu per minggu</small><strong>{rupiah(plan.perWeek)}</strong></div></div>:null}<p>{plan.status==='reached'?'Target sudah tercapai. Mantap!':f.monthlyContribution>0?<>Rencana {rupiah(f.monthlyContribution)}/bulan → tercapai ±{plan.finish?formatDate(plan.finish):'–'}{plan.lateMonths>0?`, ${plan.lateMonths} bulan setelah tenggat`:''}.</>:'Belum ada rencana setoran per bulan.'}</p></div>
  {kantong&&<p className="gl-fund-note"><Layers size={14} aria-hidden="true"/> Saldonya mengikuti dompet di kantong ini.</p>}
  {(!kantong||plan.status==='behind')&&<div className="gl-actions">{!kantong&&<Button type="button" className="small" disabled={!f.linkedWalletId} onClick={()=>openTx({type:'fund_contribution',fundId:f.id,destinationWalletId:f.linkedWalletId,amount:f.monthlyContribution||0,description:`Isi ${f.name}`})}>Isi dana</Button>}{plan.status==='behind'&&user&&<button type="button" className="link-button" onClick={()=>void action.perform(()=>saveRecord(user.uid,'funds',{monthlyContribution:plan.perMonth},f.id),'Rencana setoran disesuaikan.')}>Pakai {rupiah(plan.perMonth)}/bulan</button>}</div>}
  <ContextNotes kind="funds" id={f.id} notes={f.contextNotes} legacy={f.notes} notify={notify}/>
 </article>})}</div>:<div className="panel"><Empty message="Belum ada tujuan dana."/></div>}<Dialog open={open} onOpenChange={setOpen}><DialogContent title={editing?'Ubah dana':'Tujuan dana baru'}><form className="form-stack" onSubmit={submit}><div className="ip-seg"><button type="button" className={kind==='emergency'?'active':''} onClick={()=>setKind('emergency')}>🛟 Dana darurat</button><button type="button" className={kind==='goal'?'active':''} onClick={()=>setKind('goal')}>🎯 Tabungan / tujuan</button></div><Field label="Nama dana"><Input required value={name} onChange={e=>setName(e.target.value)} placeholder="Contoh: Dana darurat"/></Field>{editing&&<button type="button" className="notice pocket-convert" onClick={()=>{setOpen(false);setPocket({mode:'form',fundId:editing.id})}}><Layers size={16}/><span>Mau saldonya otomatis mengikuti dompet tertentu? <b>Jadikan kantong</b></span></button>}<div className="form-grid"><Field label="Target"><Money value={target} onChange={setTarget} required/></Field><Field label="Rencana per bulan"><Money value={monthly} onChange={setMonthly}/></Field><Field label="Dompet tujuan" hint="Dompet yang menerima setoran dana ini."><Select required disabled={!!editing&&editing.currentAmount>0} value={linked} onChange={e=>setLinked(e.target.value)}><option value="">Pilih dompet</option>{data.wallets.filter(w=>walletAllows(w,'transferIn')||w.id===editing?.linkedWalletId).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select></Field><Field label="Tenggat (tanggal target)"><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field></div>{target>0&&date&&(()=>{const plan=savingsPlan({targetAmount:target,currentAmount:editing?.currentAmount||0,monthlyContribution:monthly,targetDate:date},today);return plan.daysLeft!==null&&plan.daysLeft>=0?<div className="notice">Perlu <strong>{rupiah(plan.perMonth)}</strong>/bulan atau <strong>{rupiah(plan.perWeek)}</strong>/minggu selama {plan.monthsLeft} bulan. {monthly>0&&monthly<plan.perMonth?`Rencanamu ${rupiah(monthly)} masih kurang.`:''}{monthly!==plan.perMonth&&<button type="button" className="link-button" style={{marginLeft:8}} onClick={()=>setMonthly(plan.perMonth)}>Pakai angka ini</button>}</div>:<div className="notice">Tanggal target sudah lewat.</div>})()}<Failure message={action.error}/><FormActions saving={action.saving} onCancel={()=>setOpen(false)}/></form></DialogContent></Dialog></>;
}
