'use client';
import { HandCoins as SumHandCoins } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { CalendarDays, Edit3, MoreHorizontal, Plus, Trash2, Wallet as WalletIcon } from 'lucide-react';
import { GlassHero, closeMenu, dueText } from './glass';
import { useApp } from './app-provider';
import { useNotify } from './notifications';
import { Button } from './ui/button';
import { Confirm } from './ui/alert-dialog';
import { Dialog, DialogContent } from './ui/dialog';
import { ContextNotes } from './context-notes';
import { ManualPayments, SettleDialog, type SettleTarget } from './settle-dialog';
import { Empty, Field, FormActions, Input, Money, Select } from './fields';
import { createReceivable, deleteOpeningRecord, editOpeningRecord, subscribeRelatedTransactions } from '@/lib/firestore';
import { rupiah } from '@/lib/accounting';
import { walletAllows } from '@/lib/wallet-capabilities';
import { formatDate, todayInTimeZone } from '@/lib/period';
import type { LedgerTx, Receivable } from '@/lib/types';
function PaymentHistory({receivableId}:{receivableId:string}){const {user}=useApp(),[items,setItems]=useState<LedgerTx[]|null>(null),[error,setError]=useState('');useEffect(()=>{if(!user)return;setItems(null);return subscribeRelatedTransactions(user.uid,'receivableId',receivableId,setItems,e=>setError(e.message))},[user?.uid,receivableId]);const paid=(items||[]).filter(tx=>tx.type==='receivable_payment');return <div className="gl-history-list">{error&&<p className="form-error" role="alert">{error}</p>}{items===null?<p role="status" className="muted">Memuat riwayat…</p>:paid.length?paid.map(tx=><div className="budget-line" key={tx.id}><span>{formatDate(tx.date)}</span><strong>{rupiah(tx.amount)}</strong></div>):<p className="muted">Belum ada pelunasan lewat dompet.</p>}</div>}
export function ReceivablesView({notify,openTx}:{notify:(message:string)=>void;openTx:(preset?:Partial<LedgerTx>,editing?:LedgerTx)=>void}){
 const {data,user,profile}=useApp();const {track}=useNotify();const [open,setOpen]=useState(false),[selected,setSelected]=useState(''),[editing,setEditing]=useState<Receivable|null>(null),[person,setPerson]=useState(''),[amount,setAmount]=useState(0),[source,setSource]=useState(''),[date,setDate]=useState(''),[due,setDue]=useState(''),[description,setDescription]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[settle,setSettle]=useState<SettleTarget|null>(null);
 function edit(row?:Receivable){setEditing(row||null);setPerson(row?.person||'');setAmount(row?.originalAmount||0);setSource(row?.sourceWalletId||'');setDate(row?.date||todayInTimeZone(profile?.timeZone));setDue(row?.dueDate||'');setDescription(row?.description||'');setError('');setOpen(true)}
 async function act(fn:()=>Promise<unknown>,message:string,close=false){if(close){setOpen(false);track(fn(),{pending:'Menyimpan…',success:message,failure:'Belum tersimpan',retry:{label:'Buka lagi',run:()=>setOpen(true)}});return;}setBusy(true);setError('');try{await fn();notify(message);if(close)setOpen(false)}catch(e){setError((e as Error).message||'Belum berhasil. Coba lagi.')}finally{setBusy(false)}}
 function submit(event:FormEvent){event.preventDefault();if(!user)return;void act(()=>editing?editOpeningRecord(user.uid,'receivables',editing.id,{person,description,dueDate:due},amount):createReceivable(user.uid,{person,description,originalAmount:amount,sourceWalletId:source,date,dueDate:due,status:'open'}),editing?'Piutang diperbarui.':'Piutang dicatat.',true)}
 return <><div className="page-heading"><div><h1>Piutang</h1><p>Uang yang kamu pinjamkan ke orang lain dan belum kembali.</p></div><div className="heading-actions"><Button onClick={()=>edit()}><Plus size={16}/> Tambah piutang</Button></div></div>{(()=>{const unpaid=data.receivables.reduce((n,r)=>n+r.remainingAmount,0),lent=data.receivables.reduce((n,r)=>n+r.originalAmount,0),people=new Set(data.receivables.filter(r=>r.remainingAmount>0).map(r=>r.person.trim().toLowerCase())).size;return <GlassHero tone="receivable" icon={SumHandCoins} label="Belum kembali" value={rupiah(unpaid)} detail={people?`Dipinjam ${people} orang · ${data.receivables.length} catatan`:data.receivables.length?'Semua piutang sudah kembali.':'Belum ada piutang.'} progress={lent?(lent-unpaid)/lent*100:undefined} progressLabel={lent?`Sudah kembali ${rupiah(lent-unpaid)} dari ${rupiah(lent)}`:undefined}/>})()}{data.receivables.length?<div className="gl-list">{[...data.receivables].sort((a,b)=>Number(b.remainingAmount>0)-Number(a.remainingAmount>0)||(a.dueDate||'9999').localeCompare(b.dueDate||'9999')).map(row=>{const done=row.remainingAmount<=0,partial=!done&&row.remainingAmount<row.originalAmount,back=row.originalAmount?Math.min(100,(row.originalAmount-row.remainingAmount)/row.originalAmount*100):0,due=row.dueDate?dueText(row.dueDate,todayInTimeZone(profile?.timeZone)):null,wallet=row.sourceWalletId?data.wallets.find(w=>w.id===row.sourceWalletId)?.name||'dompet lama':'';return <article className={`gl-card tone-receivable ${done?'is-done':''}`} key={row.id}>
  <header className="gl-card-head"><span className="gl-avatar is-letter" aria-hidden="true">{row.person.trim().charAt(0).toUpperCase()||'?'}</span><div className="gl-card-title"><strong>{row.person}</strong><small>{row.description||`Dipinjam ${formatDate(row.date)}`}</small></div><span className={`gl-pill ${done?'is-done':partial?'is-warn':''}`}>{done?'Lunas':partial?'Dibayar sebagian':'Belum dibayar'}</span></header>
  <div className="gl-amount"><div><small>{done?'Sudah kembali semua':'Belum kembali'}</small><strong>{rupiah(row.remainingAmount)}</strong></div><span>dari {rupiah(row.originalAmount)}</span></div>
  <div className="gl-progress"><div className="gl-bar" aria-hidden="true"><i style={{width:`${back}%`}}/></div><small>Kembali {Math.round(back)}% · {rupiah(row.originalAmount-row.remainingAmount)}</small></div>
  <div className="gl-chips"><span className={!done&&due&&due.days<0?'is-late':''}><CalendarDays size={13}/> {row.dueDate?`Jatuh tempo ${formatDate(row.dueDate)}${!done&&due?` · ${due.text}`:''}`:'Tanpa jatuh tempo'}</span><span><WalletIcon size={13}/> {wallet?`Dari ${wallet}`:'Tanpa dompet'}</span>{row.description&&<span>Dipinjam {formatDate(row.date)}</span>}</div>
  <div className="gl-actions">{done?<span className="gl-actions-note">Piutang ini sudah lunas</span>:<Button type="button" className="small" onClick={()=>setSettle({kind:'receivables',id:row.id,name:row.person,remaining:row.remainingAmount})}>Catat pelunasan</Button>}<details className="more-actions"><summary aria-label={`Pilihan untuk ${row.person}`}><MoreHorizontal size={18}/><span> Lainnya</span></summary><div className="more-menu"><button type="button" onClick={e=>{closeMenu(e);edit(row)}}><Edit3 size={14}/> Ubah piutang</button><Confirm title="Hapus piutang?" description="Hanya piutang tanpa pembayaran yang bisa dihapus. Saldo dompet akan dikembalikan." onConfirm={()=>{if(user)track(deleteOpeningRecord(user.uid,'receivables',row.id),{pending:'Menghapus piutang…',success:'Piutang dihapus.',failure:'Piutang belum terhapus'})}}><button type="button" onClick={closeMenu}><Trash2 size={14}/> Hapus piutang</button></Confirm></div></details></div>
  <details className="gl-history" onToggle={event=>{if(event.currentTarget.open)setSelected(row.id);else setSelected(current=>current===row.id?'':current)}}><summary>Riwayat pelunasan</summary>{selected===row.id&&<PaymentHistory receivableId={row.id}/>}<ManualPayments kind="receivables" id={row.id} payments={row.manualPayments}/></details>
  <ContextNotes kind="receivables" id={row.id} notes={row.contextNotes} notify={notify}/>
 </article>})}</div>:<div className="panel"><Empty message="Belum ada piutang. Tambahkan piutang saat menalangi seseorang."/></div>}{error&&<p className="form-error" role="alert">{error}</p>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent title={editing?'Ubah piutang':'Piutang baru'}><form className="form-stack" onSubmit={submit}><p className="notice">Pilih dompet asal jika uangnya keluar dari dompet (saldo berkurang). Pilih “Tanpa dompet” jika hanya ingin mencatat piutangnya.</p><Field label="Nama orang"><Input required value={person} onChange={e=>setPerson(e.target.value)}/></Field><div className="form-grid"><Field label="Jumlah"><Money value={amount} onChange={setAmount} required/></Field><Field label="Dompet asal"><Select disabled={!!editing} value={source} onChange={e=>setSource(e.target.value)}><option value="">Tanpa dompet (catat piutangnya saja)</option>{data.wallets.filter(w=>walletAllows(w,'pay')||editing?.sourceWalletId===w.id).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select></Field><Field label="Tanggal"><Input type="date" required disabled={!!editing} value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Jatuh tempo"><Input type="date" value={due} onChange={e=>setDue(e.target.value)}/></Field></div><details className="disclosure" open={Boolean(description)||undefined}><summary>Keterangan tambahan</summary><Field label="Keterangan"><Input value={description} onChange={e=>setDescription(e.target.value)}/></Field></details>{error&&<p className="form-error" role="alert">{error}</p>}<FormActions saving={busy} onCancel={()=>setOpen(false)}/></form></DialogContent></Dialog><SettleDialog target={settle} onClose={()=>setSettle(null)}/></>;
}
