'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { SuggestInput, rememberTyped, useTypedSuggestions, type Suggestion } from './suggest-input';
import { useApp } from './app-provider';
import { emojiOrFallback } from './visual-identity';
import { CategoryPicker } from './category-picker';
import { Field, FormActions, Input, Money, Select } from './fields';
import { newTx, upsertTransaction, validateTx } from '@/lib/firestore';
import { rupiah } from '@/lib/accounting';
import { isCycleClosed } from '@/lib/finance-control';
import { walletActions, walletAllows } from '@/lib/wallet-capabilities';
import { timeInTimeZone, todayInTimeZone } from '@/lib/period';
import type { LedgerTx, SplitLine, TxType } from '@/lib/types';
const labels:Record<TxType,string>={expense:'Pengeluaran',income:'Pemasukan',transfer:'Transfer dompet',adjustment:'Koreksi saldo',borrowing:'Dana pinjaman',debt_payment:'Bayar utang',claim_advance:'Talangan kantor',claim_payment:'Klaim cair',claim_writeoff:'Klaim ditolak',receivable_issue:'Talangan teman',receivable_payment:'Piutang dibayar',fund_contribution:'Isi tujuan dana'};
const visible:TxType[]=['expense','income','transfer','debt_payment','claim_payment','receivable_payment','fund_contribution','adjustment'];
export function TransactionForm({onDone,onCancel,preset,editing,background}:{onDone:(message:string)=>void;onCancel:()=>void;preset?:Partial<LedgerTx>;editing?:LedgerTx|null;background?:(run:()=>Promise<unknown>,info:{message:string;retry:{preset?:Partial<LedgerTx>;editing?:LedgerTx}})=>void}){
 const {data,user,profile}=useApp();const initial=editing||preset;const [type,setType]=useState<TxType>(initial?.type||'expense'),[amount,setAmount]=useState(initial?.amount||0),[walletId,setWallet]=useState(initial?.walletId||''),[destination,setDest]=useState(initial?.destinationWalletId||''),[categoryId,setCategory]=useState(initial?.categoryId||(initial?.type==='income'?profile?.salaryIncomeCategoryId:'')||''),[subcategoryId,setSubcategory]=useState(initial?.subcategoryId||''),[date,setDate]=useState(initial?.date||todayInTimeZone(profile?.timeZone)),[time,setTime]=useState(editing?editing.time||'':initial?.time||timeInTimeZone(profile?.timeZone)),[merchant,setMerchant]=useState(initial?.merchant||''),[description,setDescription]=useState(initial?.description||''),[notes,setNotes]=useState(initial?.notes||''),[tags,setTags]=useState((initial?.tags||[]).join(', ')),[direction,setDirection]=useState(initial?.adjustmentDirection||'in'),[claimId,setClaim]=useState(initial?.claimId||''),[receivableId,setReceivable]=useState(initial?.receivableId||''),[debtId,setDebt]=useState(initial?.debtId||''),[fundId,setFund]=useState(initial?.fundId||''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const [splits,setSplits]=useState<SplitLine[]>(initial?.splits||[]),[fee,setFee]=useState(initial?.transferFee||0),[feeCategory,setFeeCategory]=useState(initial?.transferFeeCategoryId||''),[closedAcknowledged,setClosedAcknowledged]=useState(false);
 const splitTotal=splits.reduce((sum,line)=>sum+line.amount,0),splitDifference=amount-splitTotal;
 const closed=isCycleClosed(editing?.date||date,data.cycleSnapshots||[])||isCycleClosed(date,data.cycleSnapshots||[]);
 function updateSplit(index:number,change:Partial<SplitLine>){setSplits(rows=>rows.map((row,i)=>i===index?{...row,...change}:row));}
 useEffect(()=>{if(!walletId&&data.wallets.length){const preferred=type==='income'?profile?.defaultIncomeWalletId:profile?.defaultExpenseWalletId;setWallet(data.wallets.find(w=>w.id===preferred&&walletAllows(w,walletActions({type,adjustmentDirection:direction}).source))?.id||data.wallets.find(w=>walletAllows(w,walletActions({type,adjustmentDirection:direction}).source))?.id||'');}},[data.wallets,walletId,type,profile?.defaultExpenseWalletId,profile?.defaultIncomeWalletId,direction]);
 useEffect(()=>{if(type==='fund_contribution'&&fundId){const linked=data.funds.find(f=>f.id===fundId)?.linkedWalletId;if(linked)setDest(linked);const f=data.funds.find(x=>x.id===fundId);const match=data.categories.find(c=>c.name.toLowerCase()===f?.name.toLowerCase());if(match)setCategory(match.id);}},[fundId,type,data.funds]);
 const cats=data.categories.filter(c=>!c.isArchived&&c.type===(type==='income'?'income':'expense')&&!c.parentId);
 const children=data.categories.filter(c=>!c.isArchived&&c.parentId===categoryId);
 const actions=walletActions({type,adjustmentDirection:direction});
 const activeWallets=data.wallets.filter(w=>walletAllows(w,actions.source)||editing?.walletId===w.id&&editing.type===type);
 const targetWallets=data.wallets.filter(w=>w.id!==walletId&&(walletAllows(w,actions.destination||'transferIn')||editing?.destinationWalletId===w.id));
 const descriptionHints=useTypedSuggestions(user?.uid,'description',data.transactions),merchantHints=useTypedSuggestions(user?.uid,'merchant',data.transactions);
 /** Picking a past text also fills in what was used last time, if still empty. */
 function fillFromPast(item:Suggestion){const last=item.last;if(!last||last.type!==type)return;if(!categoryId&&last.categoryId){setCategory(last.categoryId);setSubcategory(last.subcategoryId||'')}if(!merchant&&last.merchant&&last.merchant!==item.text)setMerchant(last.merchant);if(!description&&last.description&&last.description!==item.text)setDescription(last.description)}
 async function submit(e:FormEvent){e.preventDefault();if(!user)return;rememberTyped(user.uid,'description',description);rememberTyped(user.uid,'merchant',merchant);setError('');if(closed&&!closedAcknowledged){setError('Transaksi ini berada dalam siklus yang sudah ditutup. Centang persetujuan sebelum melanjutkan.');return;}if(type==='expense'&&splits.length&&splitDifference){setError(splitDifference>0?`Pembagian masih kurang ${rupiah(splitDifference)}.`:`Pembagian melebihi total transaksi ${rupiah(-splitDifference)}.`);return;}setSaving(true);try{const tx=newTx({type,amount,walletId,destinationWalletId:destination||null,categoryId:type==='expense'&&splits.length?null:categoryId||null,subcategoryId:type==='expense'&&splits.length?null:subcategoryId||null,date,time,merchant,description,notes,tags:tags.split(',').map(t=>t.trim()).filter(Boolean),adjustmentDirection:direction,claimId:claimId||null,receivableId:receivableId||null,debtId:debtId||null,fundId:fundId||null,draftId:initial?.draftId||null,recurringTransactionId:initial?.recurringTransactionId||null,plannedId:initial?.plannedId||null,splits:type==='expense'?splits:[],transferFee:type==='transfer'?fee:0,transferFeeCategoryId:type==='transfer'?feeCategory||null:null,reconciliationReason:editing?.reconciliationReason||''});if(['debt_payment','claim_payment','receivable_payment','fund_contribution'].includes(type)&&!({debt_payment:debtId,claim_payment:claimId,receivable_payment:receivableId,fund_contribution:fundId} as Record<string,string>)[type])throw Error('Pilih catatan yang berkaitan.');if(background){validateTx(tx);const uid=user.uid,editId=editing?.id;background(()=>upsertTransaction(uid,tx,editId),{message:editing?'Transaksi diperbarui.':'Transaksi tersimpan.',retry:editing?{editing:{...editing,...tx,id:editing.id}}:{preset:tx}});return;}await upsertTransaction(user.uid,tx,editing?.id);onDone(editing?'Transaksi diperbarui.':navigator.onLine?'Transaksi tersimpan.':'Transaksi tersimpan di perangkat dan dikirim saat online.');}catch(e){if((e as {committed?:boolean}).committed)onDone((e as Error).message);else setError((e as Error).message||'Transaksi gagal disimpan.');}finally{setSaving(false);}}
 return <form className="form-stack" onSubmit={submit}>{closed&&<div className="notice"><strong>Transaksi ini berada dalam siklus yang sudah ditutup.</strong><p>Mengubahnya akan menghitung ulang laporan siklus terkait.</p><label className="check-row"><input type="checkbox" checked={closedAcknowledged} onChange={e=>setClosedAcknowledged(e.target.checked)}/> Saya ingin melanjutkan perubahan</label></div>}<div className="form-grid"><Field label="Jenis transaksi"><Select value={type} disabled={!!editing&&['borrowing','claim_advance','receivable_issue'].includes(editing.type)} onChange={e=>{setType(e.target.value as TxType);setCategory(e.target.value==='income'?profile?.salaryIncomeCategoryId||'':'');setSubcategory('');setWallet('');setDest('');}}>{(editing&&!visible.includes(editing.type)?[editing.type]:visible).map(t=><option key={t} value={t}>{labels[t]}</option>)}</Select></Field><Field label={type==='transfer'?'Jumlah transfer':'Nominal'}><Money value={amount} onChange={setAmount} required/></Field>
 <Field label={['income','claim_payment','receivable_payment','borrowing'].includes(type)?'Dompet penerima':'Dompet asal'}><Select required value={walletId} onChange={e=>setWallet(e.target.value)}><option value="">Pilih dompet</option>{activeWallets.map(w=><option key={w.id} value={w.id}>{w.name} · {rupiah(w.cachedBalance)}</option>)}</Select></Field>
 {['transfer','fund_contribution'].includes(type)&&<Field label="Dompet tujuan"><Select required value={destination} onChange={e=>setDest(e.target.value)}><option value="">Pilih dompet</option>{targetWallets.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</Select></Field>}
 {type==='transfer'&&<><Field label="Biaya admin"><Money value={fee} onChange={setFee}/></Field>{fee>0&&<Field label="Kategori biaya"><Select required value={feeCategory} onChange={e=>setFeeCategory(e.target.value)}><option value="">Pilih kategori</option>{data.categories.filter(c=>!c.isArchived&&c.type==='expense'&&!c.parentId).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field>}<div className="notice">Total keluar {rupiah(amount+fee)} · Dompet tujuan menerima {rupiah(amount)}. Hanya biaya admin yang dihitung pengeluaran.</div></>}
 {(type==='expense'||type==='income')&&(!splits.length||type==='income')&&<Field label="Kategori"><CategoryPicker type={type} required={type==='expense'} categoryId={categoryId} subcategoryId={subcategoryId} onChange={value=>{setCategory(value.categoryId);setSubcategory(value.subcategoryId)}}/></Field>}
 {type==='debt_payment'&&<Field label="Utang"><Select required value={debtId} onChange={e=>setDebt(e.target.value)}><option value="">Pilih utang</option>{data.debts.filter(d=>d.outstandingAmount>0).map(d=><option key={d.id} value={d.id}>{d.name} · sisa {rupiah(d.outstandingAmount)}</option>)}</Select></Field>}
 {type==='claim_payment'&&<Field label="Klaim kantor"><Select required value={claimId} onChange={e=>setClaim(e.target.value)}><option value="">Pilih klaim</option>{data.claims.filter(c=>c.remainingAmount>0).map(c=><option key={c.id} value={c.id}>{c.name} · sisa {rupiah(c.remainingAmount)}</option>)}</Select></Field>}
 {type==='receivable_payment'&&<Field label="Piutang"><Select required value={receivableId} onChange={e=>setReceivable(e.target.value)}><option value="">Pilih piutang</option>{data.receivables.filter(c=>c.remainingAmount>0).map(c=><option key={c.id} value={c.id}>{c.person} · sisa {rupiah(c.remainingAmount)}</option>)}</Select></Field>}
 {type==='fund_contribution'&&<Field label="Kategori dana (untuk anggaran)"><Select value={categoryId} onChange={e=>setCategory(e.target.value)}><option value="">Tanpa anggaran terkait</option>{data.categories.filter(c=>!c.isArchived&&!c.parentId&&['expense','savings'].includes(c.type)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field>}{type==='fund_contribution'&&<Field label="Tujuan dana"><Select required value={fundId} onChange={e=>setFund(e.target.value)}><option value="">Pilih dana</option>{data.funds.filter(f=>!f.isArchived||f.id===fundId).map(f=><option key={f.id} value={f.id}>{f.name} · {rupiah(f.currentAmount)}</option>)}</Select></Field>}
 {type==='adjustment'&&<Field label="Arah koreksi"><Select value={direction} onChange={e=>{setDirection(e.target.value as 'in'|'out');setWallet('')}}><option value="in">Menambah saldo</option><option value="out">Mengurangi saldo</option></Select></Field>}
 <Field label="Tanggal"><Input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></Field></div><details className="disclosure advanced-form"><summary>Opsi tambahan: waktu, tempat, label, catatan</summary><div className="form-grid"><Field label="Waktu"><Input type="time" value={time} onChange={e=>setTime(e.target.value)}/></Field>
 <Field label={type==='income'?'Sumber':'Tempat / penerima'}><SuggestInput value={merchant} onValue={setMerchant} suggestions={merchantHints} onPick={fillFromPast} placeholder="Opsional"/></Field><Field label="Keterangan"><SuggestInput value={description} onValue={setDescription} suggestions={descriptionHints} onPick={fillFromPast} placeholder="Misalnya makan siang"/></Field><Field label="Label (pisahkan dengan koma)"><Input value={tags} onChange={e=>setTags(e.target.value)} placeholder="kantor, rutin"/></Field><Field label="Catatan"><Input value={notes} onChange={e=>setNotes(e.target.value)}/></Field></div></details>{type==='expense'&&<details className="disclosure split-editor" open={splits.length>0||undefined}><summary>Pembagian kategori {splits.length?(`(${splits.length}) ${splitDifference?'· selisih '+rupiah(Math.abs(splitDifference)):''}`):'(opsional)'}</summary><div className="budget-line"><strong>Bagi ke beberapa kategori</strong><button className="link-button" type="button" onClick={()=>setSplits(rows=>[...rows,{categoryId:categoryId||'',subcategoryId:subcategoryId||null,amount:rows.length?0:amount}])}>+ Tambah pembagian</button></div>{splits.map((line,index)=><div className="split-line" key={index}><Field label={`Kategori ${index+1}`}><Select required value={line.categoryId} onChange={e=>updateSplit(index,{categoryId:e.target.value,subcategoryId:null})}><option value="">Pilih kategori</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field><Field label="Subkategori"><Select value={line.subcategoryId||''} onChange={e=>updateSplit(index,{subcategoryId:e.target.value||null})}><option value="">Tanpa subkategori</option>{data.categories.filter(c=>!c.isArchived&&c.parentId===line.categoryId).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field><Field label="Nominal"><Money value={line.amount} onChange={value=>updateSplit(index,{amount:value})} required/></Field><button className="link-button" type="button" onClick={()=>setSplits(rows=>rows.filter((_,i)=>i!==index))}>Hapus</button></div>)}{splits.length>0&&<div className="notice" role="status">Total dibagi {rupiah(splitTotal)} dari {rupiah(amount)}. {splitDifference===0?'Sisa Rp0 · siap disimpan.':splitDifference>0?`Pembagian masih kurang ${rupiah(splitDifference)}.`:`Pembagian melebihi total transaksi ${rupiah(-splitDifference)}.`}</div>}</details>}{error&&<p role="alert" className="form-error">{error}</p>}<FormActions saving={saving} disabled={type==='expense'&&splits.length>0&&splitDifference!==0} onCancel={onCancel} label={editing?'Simpan perubahan':'Simpan transaksi'}/></form>;
}
