'use client';
import { useEffect, useState } from 'react';
import { useApp } from './app-provider';
import { Field, Input, Money } from './fields';
import { Button } from './ui/button';
import { Dialog, DialogContent } from './ui/dialog';
import { rupiah } from '@/lib/accounting';
import { todayInTimeZone } from '@/lib/period';
import { reconcileWallet, repairWalletCache, walletBalancePreview } from '@/lib/finance-store';

type Preview=Awaited<ReturnType<typeof walletBalancePreview>>;
export function WalletControls({walletId,mode,onClose,onDone}:{walletId:string|null;mode:'reconcile'|'recalculate';onClose:()=>void;onDone:(message:string)=>void}){
 const {user,profile}=useApp();const [preview,setPreview]=useState<Preview|null>(null),[actual,setActual]=useState(0),[notes,setNotes]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setPreview(null);setConfirm(false);setError('');if(!walletId||!user)return;let active=true;walletBalancePreview(user.uid,walletId).then(result=>{if(active){setPreview(result);setActual(result.calculated)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[walletId,user]);
 async function execute(){if(!user||!walletId||!preview)return;setBusy(true);setError('');try{if(mode==='recalculate'){const result=await repairWalletCache(user.uid,walletId,preview.cached);onDone(result.warning||'Saldo tersimpan diperbaiki berdasarkan ledger. Riwayat transaksi tidak diubah.');}else{const result=await reconcileWallet(user.uid,walletId,preview.cached,actual,notes,todayInTimeZone(profile?.timeZone));onDone(result.warning||'Penyesuaian saldo dicatat sebagai transaksi di riwayat.');}onClose()}catch(e){setError((e as Error).message||'Penyesuaian gagal.');setConfirm(false);}finally{setBusy(false)}}
 const diff=actual-(preview?.calculated||0);
 return <Dialog open={Boolean(walletId)} onOpenChange={open=>{if(!open)onClose()}}><DialogContent title={mode==='reconcile'?'Cocokkan Saldo':'Hitung Ulang Saldo'}><div className="form-stack">{!preview&&!error&&<p role="status">Menghitung saldo dari seluruh transaksi…</p>}{preview&&<><div className="panel money-detail"><strong>{preview.wallet.name}</strong><div><span>Saldo berdasarkan transaksi</span><strong>{rupiah(preview.calculated)}</strong></div><div><span>Saldo tersimpan di aplikasi</span><strong>{rupiah(preview.cached)}</strong></div><div><span>Selisih</span><strong>{rupiah(preview.difference)}</strong></div><small>{preview.transactions} transaksi terkait · saldo awal {rupiah(preview.wallet.openingBalance)}</small></div>{mode==='reconcile'&&<><Field label="Saldo aktual di bank / e-wallet"><Money value={actual} onChange={value=>{setActual(value);setConfirm(false)}}/></Field><div className="notice">{diff===0?'Saldo aktual sama dengan saldo berdasarkan transaksi.':`Saldo aktual ${diff<0?'lebih rendah':'lebih tinggi'} ${rupiah(Math.abs(diff))}. Penyesuaian ${diff<0?'mengurangi':'menambah'} saldo ${preview.wallet.name}.`}</div><Field label="Catatan opsional"><Input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Misalnya biaya yang lupa dicatat"/></Field></>}{preview.difference!==0&&mode==='reconcile'&&<div className="notice">Saldo tersimpan dan transaksi belum cocok. Samakan saldo lewat Hitung Ulang Saldo sebelum mencocokkan saldo aktual.</div>}{mode==='recalculate'&&preview.difference!==0&&<div className="notice">Perbaikan hanya memperbarui saldo tersimpan menjadi {rupiah(preview.calculated)}. Tidak ada transaksi lama yang diubah.</div>}{!confirm&&(mode==='recalculate'?preview.difference!==0:diff!==0&&preview.difference===0)&&<Button onClick={()=>setConfirm(true)}>{mode==='reconcile'?'Buat Penyesuaian':'Samakan saldo'}</Button>}{confirm&&<div className="panel"><strong>Konfirmasi {mode==='reconcile'?'Penyesuaian':'Penyamaan saldo'}</strong><p className="muted">Dompet: {preview.wallet.name} · saldo terhitung {rupiah(preview.calculated)} · {mode==='reconcile'?`saldo aktual ${rupiah(actual)} · penyesuaian ${diff<0?'-':'+'}${rupiah(Math.abs(diff))}`:`saldo tersimpan ${rupiah(preview.cached)} → ${rupiah(preview.calculated)}`}{notes?` · ${notes}`:''}</p><div className="toolbar-row" style={{marginTop:14}}><Button variant="secondary" onClick={()=>setConfirm(false)} disabled={busy}>Batal</Button><Button onClick={()=>void execute()} disabled={busy}>{busy?'Memproses…':'Konfirmasi Penyesuaian'}</Button></div></div>}</>}{error&&<p role="alert" className="form-error">{error}</p>}<Button variant="secondary" onClick={onClose}>Tutup</Button></div></DialogContent></Dialog>
}
