/** "Apa yang baru" (Pengaturan → Info aplikasi), newest first. Emoji must be in lib/emoji-set.ts. */
export type Release = { version: string; date: string; title: string; items: [emoji: string, text: string][] };

export const releases: Release[] = [
  { version: '87', date: '27 Sep 2026', title: 'Hapus transaksi otomatis tidak muncul lagi, tampilan lebih rapi', items: [
    ['✅', 'Menghapus transaksi dari jadwal rutin “Catat otomatis” kini benar-benar menghapusnya: jadwal hari itu ditandai dilewati, jadi tidak dicatat ulang. Sebelumnya transaksinya langsung muncul kembali.'],
    ['🔒', 'Transaksi yang sudah terhapus juga langsung hilang dari salinan data di perangkat, dan baris yang dihapus hanya muncul lagi bila penghapusannya gagal.'],
    ['📝', 'Wish list tidak lagi melebar keluar layar di HP. Menu “Lainnya” di kartu utang dan piutang tidak lagi terpotong di sisi kiri layar.'],
    ['💡', 'Beranda lebih ringkas di HP: tanggal periode tidak diulang di setiap kartu, dan kartu terakhir yang sendirian dibuat melebar. Tombol Dompet, nama anggaran yang panjang, dan label grafik Proyeksi tidak lagi terpotong atau bertumpuk.'],
  ] },
  { version: '86', date: '27 Sep 2026', title: 'Mengetik di Catat otomatis lebih ringan', items: [
    ['✅', 'Huruf yang kamu ketik di Catat otomatis langsung muncul; pembacaan kalimat dan kartunya menyusul sesaat kemudian, jadi tidak lagi terasa tersendat di HP. Kartu yang tidak berubah tidak digambar ulang.'],
    ['🔒', 'Menekan Enter tepat setelah mengetik tetap menyimpan kalimat yang lengkap, bukan potongan yang belum selesai dibaca.'],
  ] },
  { version: '85', date: '27 Sep 2026', title: 'Tentukan area struk dulu, lensa kamera, dan biaya tambahan yang seragam', items: [
    ['📷', 'Setelah foto diambil atau dipilih, kamu menentukan area struknya dulu: geser titik atau sisi ke tepi struk, putar bila perlu, lalu “Baca struk”. Hanya bagian di dalam garis yang dibaca. Peringatan foto (buram, gelap, pudar) muncul di langkah ini, dengan pilihan “Ambil ulang”.'],
    ['🔒', 'Kamera tidak lagi mengingat lensa ultra-wide. Nama kamera berbahasa Indonesia (mis. “Kamera Ultra Lebar Belakang”) kini dikenali, lensa yang tidak bisa dibedakan dari namanya dicek dari kemampuannya (fokus otomatis, ukuran sensor), dan ada tombol “Ganti lensa” yang pilihannya diingat.'],
    ['✅', 'Tambahan & diskon di Split Bill tidak lagi macet saat dibuka-tutup. Pilihan jenis biaya muncul sebagai tombol di tempat, bukan menu melayang.'],
    ['💸', 'Nominal manual dan Persentase di Split Bill lebih rapi: nama di kiri, isian di kanan, total per orang di bawah nama, dan “Terisi … dari …” untuk melihat sisa yang belum dibagi.'],
    ['🧾', 'Biaya tambahan di Scan struk (pengeluaran dan pemasukan) kini tampil seperti di Split Bill: satu baris per biaya dengan ikon, ketuk untuk mengubah nominal, pilih 10%/11% cepat, tandai “Sudah termasuk harga”, atau hapus. “+ Tambah” untuk diskon, pajak, service, ongkir, biaya lain, atau pembulatan.'],
  ] },
  { version: '84', date: '27 Sep 2026', title: 'Split Bill lebih ringkas, scan struknya selengkap Scan struk', items: [
    ['🧾', 'Scan struk dari Split Bill kini memakai pemeriksaan struk yang sama dengan Scan struk: atur sudut, baca ulang, lihat di foto, foto lanjutan, ubah item, diskon, dan biaya. Tombolnya “Gunakan di Split Bill”, dan tidak ada transaksi yang tersimpan dari sana.'],
    ['✅', 'Yang sudah kamu perbaiki ikut masuk ke Split Bill. Diskon item tetap menempel di itemnya, jadi yang dibagi adalah harga bersihnya (Burger Rp50.000 − Rp10.000 → Rp40.000). Voucher, pajak, service, ongkir, dan biaya admin masuk sebagai biaya tambahan.'],
    ['💡', 'Split Bill jadi satu halaman: orang, item (ketuk untuk memilih siapa yang pesan), tambahan & diskon, total per orang (ketuk untuk rinciannya), dan “Cocok” atau selisihnya dengan total struk. Satu tombol “Selesai membagi”.'],
    ['📷', 'Kamera scan memilih kamera belakang utama (1×), bukan ultra-wide, bila browser memberi tahu lensanya, dan mengingat pilihan itu. Fokus otomatis terus-menerus dipakai bila didukung, dan ketuk-untuk-fokus hanya muncul di kamera yang benar-benar mendukungnya. Kamera bawaan tetap bisa dipakai.'],
  ] },
  { version: '83', date: '27 Sep 2026', title: 'Scan struk dan Catat otomatis lebih ringkas', items: [
    ['🧾', 'Hasil scan dimulai dari yang penting: tempat, tanggal, cara bayar, total besar, jumlah item, dan “Total cocok dengan rincian” atau berapa bagian yang perlu dicek. Yang perlu dicek langsung di bawahnya, lengkap dengan “Gunakan …” dan “Baca ulang”.'],
    ['💡', 'Item jadi baris sederhana (diskon item di bawahnya), biaya dan pajak dalam satu rincian, dan tombol foto (atur sudut, baca ulang, foto lanjutan, Split Bill, dll.) dikumpulkan di menu ⋯. Satu tombol Simpan yang jelas.'],
    ['📷', 'Atur sudut seperti aplikasi pemindai: bagian luar digelapkan, titik sudut besar, sisi bisa digeser, kaca pembesar saat menggeser, pratinjau struk yang sudah diluruskan, lalu Ulangi atau Gunakan.'],
    ['📝', 'Rincian struk ikut tersimpan: buka transaksinya nanti untuk melihat item, diskon, pajak, cara bayar, dan nomor struk. Catatan transaksi tidak lagi dipenuhi teks struk, dan struk tetap utuh walau nominal transaksinya diubah.'],
    ['✅', 'Catat otomatis lebih tenang: empat pilihan jenis dulu (sisanya di “Lainnya”), tiga contoh, pratinjau berupa ringkasan dengan tombol Simpan dan Ubah, dan hanya isian yang belum jelas yang ditandai.'],
  ] },
  { version: '82', date: '27 Sep 2026', title: 'Catat otomatis 2.0: satu pesan, banyak catatan', items: [
    ['📝', 'Satu pesan bisa berisi beberapa hal berbeda sekaligus: “besok bayar kos 1,5jt, ingetin perpanjang stnk tanggal 20, sama budget makan bulan depan 2jt” jadi rencana, pengingat, dan anggaran. Tiap catatan bisa diubah, dilewati, atau dibaca ulang sebagai jenis lain sebelum “Simpan semua”.'],
    ['💡', 'Mengerti koreksi dan rujukan: “makan 30rb eh 35rb”, “pakai gopay, bukan bca”, “kemarin, eh tadi pagi”, “dua-duanya pakai gopay”, “yang bensin pakai bca”, “sisanya pakai gopay”. Tanggal atau dompet yang disebut di satu bagian tidak menimpa yang disebut sendiri di bagian lain.'],
    ['✅', 'Tiap isian punya status: Terverifikasi, Kemungkinan benar, Perlu dicek, atau Belum terbaca. Hanya yang ragu yang ditandai, dan ketuk “Kenapa?” untuk melihat alasannya.'],
    ['🔒', 'Tidak menebak data keuangan: transfer tanpa dompet asal, dua nominal, dua dompet, dua tanggal, atau utang yang hanya mirip sebagian (“cicilan motor” bukan “Cicilan laptop”) diminta dipilih dulu, bukan diisi sendiri.'],
    ['💸', 'Lebih paham tulisan sehari-hari: kemaren, trf, go pay, 350rbu, 1.5jt, akhir bulan, awal bulan depan, pas gajian berikutnya, senin kemarin, jam 7 pagi. Nomor kamar, meja, atau rekening tidak lagi dibaca sebagai uang.'],
  ] },
  { version: '81', date: '27 Sep 2026', title: 'Konfirmasi struk lebih rapi', items: [
    ['📝', 'Tanggal, jam, tempat, dompet, kategori, keterangan, dan catatan kini dalam satu kartu ringkas: label di kiri, isian di kanan.'],
    ['🧾', 'Biaya tambahan jadi bagian yang bisa dibuka-tutup (tertutup dulu), dengan jumlah dan hasil hitungnya terlihat di judul.'],
    ['💡', 'Kotak isian lebih kecil dan membulat penuh, jadi layar tidak cepat penuh.'],
  ] },
  { version: '80', date: '27 Sep 2026', title: 'Hasil Scan struk lebih ringkas', items: [
    ['🧾', 'Item di struk kini satu baris per item (nama, jumlah, kategori, dan harga); ketuk item untuk mengubahnya.'],
    ['📝', 'Tombol foto (putar, sudut, baca ulang, foto lanjutan, ganti) jadi satu baris kecil, tanggal dan jam berdampingan, dan kolom isian lebih ringkas.'],
    ['💡', 'Bagian yang jarang dipakai dilipat: biaya & diskon (terbuka otomatis bila total belum cocok), pembayaran, catatan, dan detail hasil baca. Pilihan nominal lain cukup satu baris yang bisa digeser.'],
  ] },
  { version: '79', date: '27 Sep 2026', title: 'Scan struk 2.0: memahami struk, bukan sekadar membaca', items: [
    ['📷', 'Struk dicari keempat sudutnya lalu diluruskan penuh, jadi foto yang miring atau diambil dari samping tetap terbaca. Bayangan diratakan, dan struk yang terpotong bayangan tidak lagi kehilangan sisinya. Ada kamera dengan panduan (“Dekatkan kamera”, “Struk ditemukan”) dan foto otomatis bila mau.'],
    ['✅', 'Beberapa pembacaan digabungkan angka demi angka. Yang sama dipercaya, yang berbeda disimpan sebagai pilihan, dan hitungan dipakai hanya bila ada satu-satunya cara struk cocok. Hasilnya: Terverifikasi, Kemungkinan benar, Perlu dicek, atau Belum terbaca.'],
    ['🧾', 'Hasil scan hanya meminta kamu memeriksa yang ragu. Ketuk ikon mata untuk melihat di bagian mana struk angka itu dibaca, baca ulang satu bagian saja, atau atur sudut struk tanpa foto ulang.'],
    ['💡', 'Lebih paham isi struk: nama item dua baris, catatan item (NO ICE), tambahan berbayar, diskon per item, voucher, diskon ongkir, asuransi pengiriman, cashback (tidak mengurangi yang dibayar), BBM (liter × harga), parkir, nomor struk, dan cara bayar dari bagian pembayaran (promo GoPay di bawah tidak dianggap cara bayar).'],
    ['🔒', 'Struk panjang bisa difoto beberapa kali (Foto lanjutan) tanpa item ganda, dan struk yang mirip transaksi lama diberi peringatan sebelum disimpan. Semua tetap dibaca di perangkat ini.'],
  ] },
  { version: '78', date: '27 Sep 2026', title: 'Hasil Scan struk lebih rapi', items: [
    ['🧾', 'Layar hasil scan dirapikan untuk HP: foto jadi kecil (ketuk untuk memperbesar), tombolnya di samping foto, rincian biaya tidak berdempetan, dan tombol Simpan lebih ramping sambil menampilkan nominalnya.'],
    ['💡', 'Kategori kini dipilih dari daftar per kategori utama yang bisa dibuka-tutup, lengkap dengan pencarian, untuk kategori transaksi, tiap item, dan biaya yang dicatat terpisah.'],
    ['📝', 'Tiap item menampilkan total barisnya (jumlah × harga), dan kategori item tidak lagi terpotong.'],
  ] },
  { version: '77', date: '27 Sep 2026', title: 'Catat otomatis paling bisa diandalkan', items: [
    ['📝', 'Beberapa catatan sekaligus: “kemarin makan 25rb, parkir goceng, bensin 30rb pakai gopay” atau satu baris per catatan. Tanggal atau dompet yang disebut sekali berlaku untuk semuanya; baris bisa dilewati sebelum “Simpan semua”.'],
    ['💡', 'Anggaran bisa memilih subkategori: “budget makan 2jt untuk sarapan, makan siang dan kopi”, “kecuali delivery”, “selain bioskop”, “khusus sarapan”, “makan siang dan malam”. Pratinjau menampilkan chip subkategori yang bisa diketuk.'],
    ['💰', 'Nominal dalam kata dan bahasa gaul: dua puluh lima ribu, satu setengah juta, sejuta setengah, setengah juta, goceng, ceban, gocap, cepek. Tanggal “3/9” juga dikenali.'],
    ['💸', 'Arah uang selalu benar: top up GoPay dari BCA, isi GoPay pakai BCA, tarik tunai (bank ke Tunai), dan setor tunai (Tunai ke bank).'],
    ['✅', 'Konteks lebih pintar: freelance dan proyek jadi pemasukan, transferan dari orang tua jadi Hadiah Uang, dan grab/gojek masuk Taxi / Online.'],
  ] },
  { version: '76', date: '27 Sep 2026', title: 'Scan struk membaca semua biaya, Catat otomatis lebih cerdas', items: [
    ['🧾', 'Scan struk membaca diskon dan potongan (termasuk persen, voucher, promo ongkir), pajak (PB1, PPN, PBJT), service, ongkir, biaya lain (admin, kemasan, aplikasi, tip), dan pembulatan, dari struk resto, minimarket, GoFood/GrabFood, sampai marketplace.'],
    ['📝', 'Pengeluaran dari struk kini punya Rincian biaya yang bisa diubah, dengan hasil hitung yang langsung dicocokkan. Biaya bisa digabung ke belanja atau dicatat terpisah dengan kategorinya sendiri, dan rinciannya tersimpan di catatan transaksi.'],
    ['✅', 'Tanggal dan jam lebih tepat: tanggal kedaluwarsa voucher dan kode kasir tidak lagi terbaca sebagai tanggal, dan format AM/PM, WIB, serta tanggal gaya Amerika dikenali. PPN yang sudah termasuk harga tidak dihitung dua kali.'],
    ['💡', 'Catat otomatis lebih cerdas: “budget makan 2jt” masuk Makan & Minum, sedangkan “budget makan traveling” masuk Travel › Makan. Kata seperti ngopi, groceries, ortu, dan “pulsa dan kuota” dikenali.'],
    ['💰', 'Pengeluaran saat liburan atau dinas masuk ke subkategori yang pas, misalnya “makan pas liburan” ke Travel › Makan dan “grab waktu liburan” ke Transport Lokal.'],
  ] },
  { version: '75', date: '27 Sep 2026', title: 'Tambah/kurangi utang & piutang, Scan struk lebih pintar', items: [
    ['💸', 'Utang dan piutang kini bisa ditambah atau dikurangi. Pinjam atau meminjamkan lagi bisa langsung lewat dompet; potongan dan diskon cukup dikurangi. Ada juga Atur sisa, dan perubahan terakhir bisa dibatalkan dari Riwayat.'],
    ['📷', 'Scan struk mencari struk di foto, meluruskan foto miring, meratakan bayangan, dan membaca ulang dengan cara lain bila belum cocok. Foto yang diambil menyamping diputar otomatis.'],
    ['✅', 'Grand total tidak lagi masuk ke daftar item. Angka di bawah total (nomor kartu, kode approval, kembalian) tidak dianggap belanjaan.'],
    ['💡', 'Lebih pintar membaca struk minimarket (PPN sudah termasuk, DPP), kata yang salah baca (T0TAL, GRAND TOTAI), dan teks yang tersalin per kolom. Nama toko besar dikenali.'],
    ['📝', 'Angka yang salah baca dibetulkan hanya bila hasilnya pas dengan subtotal atau total (misalnya 6.920 jadi 6.900), dan setiap koreksi ditampilkan untuk kamu periksa.'],
  ] },
  { version: '74', date: '27 Sep 2026', title: 'Scan struk', items: [
    ['📷', 'Foto struk atau nota, lalu nominal, tanggal, jam, tempat, item, pajak, service, diskon, dan cara bayar dibaca otomatis. Ada di tombol + (Catat cepat) dan di formulir Catat transaksi.'],
    ['✅', 'Selalu dikonfirmasi dulu: periksa dan ubah semuanya sebelum disimpan. Aplikasi mencocokkan total, item, dan uang bayar dikurangi kembalian, lalu memberi tahu kalau ada yang belum pas.'],
    ['💡', 'Dompet ditebak dari cara bayar (tunai, QRIS, GoPay, OVO, dan lainnya) dan kategori dari tempat serta item. Belanja campuran bisa dipisah per kategori.'],
    ['🧾', 'Split Bill kini memakai pembaca yang sama, dan hasil scan bisa langsung dijadikan Split Bill.'],
    ['🔒', 'Foto dibaca di perangkat ini, tidak diunggah untuk dibaca, dan gratis. Bisa juga tempel teks struk.'],
  ] },
  { version: '73', date: '27 Sep 2026', title: 'Perbarui saldo utang & piutang, Arsip, dan privasi', items: [
    ['✏️', 'Utang dan piutang kini punya “Perbarui saldo” untuk bunga, denda, potongan, atau salah catat, tanpa mengubah saldo dompet.'],
    ['📝', 'Riwayat lengkap tiap utang dan piutang: pembayaran lewat dompet, pelunasan tanpa dompet, dan setiap perubahan saldo.'],
    ['🗂️', 'Mode Ringkas satu baris per catatan, dan yang sudah lunas pindah ke tab Arsip, dikelompokkan per bulan dan hari yang bisa dilipat.'],
    ['🔒', 'Pengaturan → Tampilan: “Selalu sembunyikan nominal” setiap aplikasi dibuka.'],
    ['🧾', 'Biaya tambahan Split Bill kini dipilih dari menu yang rapi, dan tiap biaya bisa dilipat.'],
  ] },
  { version: '72', date: '27 Sep 2026', title: 'Split Bill', items: [
    ['🧾', 'Menu baru Split Bill: bagi rata, sesuai pesanan (item berbagi dan per porsi), nominal manual, atau persentase, lengkap dengan pajak, service, diskon, ongkir, pembulatan, dan biaya bersama. Pembagian selalu pas sampai Rupiah terakhir.'],
    ['💳', 'Uang keluar dan pengeluaranmu dibedakan: bayar Rp600rb untuk berempat, saldo dompet berkurang Rp600rb tapi anggaran dan analisis hanya menghitung bagianmu. Bagian teman jadi piutang yang tertaut.'],
    ['🤝', 'Teman membayar balik tidak dihitung pemasukan; kalau orang lain yang bayar, bagianmu jadi pengeluaran dan utang, dan melunasinya tidak dihitung pengeluaran lagi.'],
    ['📷', 'Bisa dari transaksi yang sudah ada, dari foto struk (teks dibaca bila perangkat mendukung, atau tempel teks struk), atau dihitung manual; hasil baca selalu diperiksa dulu.'],
    ['📝', 'Status tiap orang, pembayaran sebagian, orang tersimpan dan grup, bagikan teks atau gambar ke WhatsApp, dan pengingat yang bisa kamu ubah sebelum dikirim.'],
    ['📊', 'Terhubung ke Beranda, Insight, Laporan, Periksa Data, Piutang, dan Utang.'],
  ] },
  { version: '71', date: '27 Sep 2026', title: 'Kategori yang membaca konteks', items: [
    ['💡', 'Kata yang punya banyak arti dibaca dari konteksnya: “beli air 5rb di alfa” jadi minuman, “bayar air 150rb” jadi tagihan air; “tiket kereta” masuk transportasi, “tiket konser” masuk hiburan; “grabfood” masuk makanan.'],
    ['✅', 'Arah uang ikut dibaca: “gaji art”, “thr art”, dan “tiket masuk” tetap pengeluaran; “bunga deposito”, “komisi”, dan “dapat hadiah” jadi pemasukan.'],
    ['🔄', 'Belajar dari kebiasaanmu: barang, tempat, dan kata yang biasa kamu catat di satu kategori ikut diperhitungkan.'],
    ['📝', 'Alasan pilihan kategori ditampilkan, dan formulir transaksi kini menyarankan kategori dari keterangan yang kamu ketik.'],
  ] },
  { version: '70', date: '26 Sep 2026', title: 'Catat otomatis untuk semua menu', items: [
    ['🚀', 'Satu kalimat kini bisa membuat anggaran, tujuan dana, wish list, dompet, kategori, jadwal rutin, rencana, dan pengingat, contohnya “anggaran makan 2jt” atau “langganan netflix 54rb tiap tanggal 5”.'],
    ['💰', 'Perbarui saldo cukup dengan “saldo bca sekarang 12jt”; selisihnya dicatat sebagai penyesuaian.'],
    ['🧭', 'Ketik “buka laporan”, “lihat utang”, atau “pengingat” untuk langsung pindah ke menunya.'],
    ['📝', 'Tanggal bisa ditulis bebas: besok, lusa, tgl 5, 17 agustus, minggu depan. Pengeluaran yang masih akan datang disimpan sebagai rencana.'],
    ['✅', 'Dompet default dan pilihan dompet kini mengikuti urutan di halaman Dompet.'],
  ] },
  { version: '69', date: '26 Sep 2026', title: 'Catat otomatis lebih jelas', items: [
    ['📝', 'Teks Catat otomatis dirapikan, dan contoh kalimat tampil sebagai kartu yang tinggal diketuk, lengkap dengan hasilnya.'],
  ] },
  { version: '68', date: '26 Sep 2026', title: 'Tombol Catat otomatis', items: [
    ['🚀', 'Tombol khusus “Catat otomatis” di atas Pengeluaran dan Pemasukan: ketik, cek pratinjau, lalu “Sesuai, simpan”.'],
  ] },
  { version: '67', date: '26 Sep 2026', title: 'Ketik cepat makin pintar', items: [
    ['🚀', 'Ketik cepat kini paham utang, piutang, klaim kantor, target, dan wish list, bukan hanya masuk dan keluar.'],
    ['✅', 'Pratinjau langsung saat mengetik, lalu Simpan sekali ketuk. Salah tebak? Ketuk “Bukan?” atau pilih jenisnya.'],
  ] },
  { version: '66', date: '26 Sep 2026', title: 'Ketik cepat', items: [
    ['🚀', 'Tulis “beli pocari 8rb di alfa”, formulir transaksi langsung terisi: nominal, tempat, kategori, dompet, dan tanggal.'],
  ] },
  { version: '65', date: '26 Sep 2026', title: 'Utang, piutang, dan grafik pemasukan', items: [
    ['💳', 'Bayar utang dan pelunasan piutang bisa diberi kategori dan masuk ke laporan.'],
    ['📊', 'Grafik kategori untuk pemasukan, di Beranda dan Analisis.'],
  ] },
  { version: '64', date: '26 Sep 2026', title: 'Privasi dan hemat kuota', items: [
    ['🔒', 'Ikon mata di sebelah lonceng: sembunyikan semua nominal sekali ketuk.'],
    ['📝', 'Transaksi, utang, piutang, dan klaim yang disimpan tercatat di notifikasi.'],
    ['🔄', 'Hemat kuota: data disimpan di perangkat, hanya perubahan yang diunduh.'],
    ['⚡', 'Laporan, riwayat siklus, dan pindah tab tidak memakai kuota baca.'],
    ['✅', 'Riwayat siklus hanya menandai siklus yang punya transaksi sebagai siap ditutup.'],
    ['📌', 'Tempat belanja di Laporan tidak lagi tercampur kategori atau keterangan.'],
    ['📊', 'Kartu Pemasukan & Pengeluaran di Beranda lebih ringkas dan muat lebih banyak.'],
  ] },
  { version: '63', date: '26 Sep 2026', title: 'Lebih ringkas, lebih mulus', items: [
    ['📱', 'Geser antartab, misalnya di Laporan, kini mulus tanpa kedipan.'],
    ['🚀', 'Halaman yang sudah siap langsung tampil, tanpa layar memuat sesaat.'],
    ['🛠️', 'Tombol Urutkan, Rentang, dan Periode lebih ringkas dan proporsional.'],
  ] },
  { version: '62', date: '26 Sep 2026', title: 'Lebih halus, lebih kaca', items: [
    ['🌙', 'Pindah ke mode gelap tanpa kedipan terang.'],
    ['⚡', 'Dari tombol Tambah ke formulir transaksi tanpa jeda.'],
    ['💳', 'Menu Lainnya di Dompet membuka ke atas bila dekat bilah bawah.'],
    ['🎨', 'Ukuran teks dan tampilan SS (super kecil); teks S jadi bawaan.'],
    ['🧾', 'Subkategori anggaran dipilih lewat dropdown.'],
    ['🤝', 'Utang & Piutang serta Tujuan dana tampil baru bergaya kaca.'],
    ['📱', 'Info aplikasi di Pengaturan: versi dan apa yang baru.'],
  ] },
  { version: '61', date: '26 Sep 2026', title: 'Kendali akun penuh', items: [
    ['🧹', 'Reset semua data untuk mulai dari awal, akun tetap ada.'],
    ['🛡️', 'Hapus akun permanen beserta semua datanya.'],
    ['🔒', 'Lupa dan ganti password versi baru, lengkap dengan meter kekuatan.'],
    ['🗂️', 'Tambah kartu Beranda dalam 9 kategori dropdown dan pencarian.'],
  ] },
  { version: '60', date: '26 Sep 2026', title: 'Beranda makin kaya', items: [
    ['📊', '15 kartu Beranda baru, misalnya Rasio Menabung dan Belanja 7 Hari.'],
    ['📝', 'Pilihan jenis huruf: Bawaan, Inter, Google Sans, Plus Jakarta Sans.'],
    ['📌', 'Kategori tampil ringkas; ketuk untuk membuka subkategori.'],
    ['💰', 'Saldo Dompet dan Komposisi Aset selalu cocok dengan Aset bersih.'],
  ] },
  { version: '59', date: '26 Sep 2026', title: 'Anggaran dan kategori baru', items: [
    ['🎯', 'Satu anggaran bisa mencakup beberapa subkategori.'],
    ['🎉', 'Tampilan baru untuk Anggaran, Kategori, dan panduan awal.'],
    ['💎', 'Kartu kantong bergaya kaca.'],
    ['📈', 'Perkiraan return investasi di Insight dibuat realistis.'],
  ] },
  { version: '56–58', date: '26 Sep 2026', title: 'Riwayat dan bantuan', items: [
    ['📉', 'Riwayat siklus dengan ringkasan setiap bulan gaji.'],
    ['🧭', 'Kontrol keuangan lebih fleksibel, lengkap dengan penjelasan.'],
    ['❓', 'Menu Tanya Jawab: istilah, fungsi menu, dan cara pakai.'],
  ] },
  { version: '52–55', date: '25 Sep 2026', title: 'Dompet ringkas', items: [
    ['👛', 'Tampilan Dompet Ringkas dengan warna kartu tiap dompet.'],
    ['📥', 'Kartu Pemasukan & Pengeluaran di Beranda.'],
    ['⌨️', 'Lembar isian naik di atas keyboard HP.'],
    ['🔁', 'Jadwal rutin tetap di tanggal yang sama tiap bulan.'],
  ] },
  { version: '42–51', date: '25 Sep 2026', title: 'Kantong dan formulir baru', items: [
    ['🪙', 'Kantong tabungan yang mengelompokkan beberapa dompet.'],
    ['🏦', 'Logo bank, e-money, dan kartu; cari emoji di semua pilihan ikon.'],
    ['💸', 'Formulir transaksi dan pop-up yang baru.'],
    ['✅', 'Audit menyeluruh: satu rumus Uang bebas di semua halaman.'],
  ] },
  { version: '25–41', date: '25 Sep 2026', title: 'Insight hadir', items: [
    ['💡', 'Insight: skor kesehatan, temuan, dan rencana aksi dari datamu sendiri.'],
    ['🎁', 'Wish list untuk barang impian.'],
    ['📱', 'Buka kunci dengan sidik jari atau wajah.'],
    ['🚀', 'Layar pembuka baru dan notifikasi mengambang.'],
  ] },
];
