/** "Apa yang baru" (Pengaturan → Info aplikasi), newest first. Emoji must be in lib/emoji-set.ts. */
export type Release = { version: string; date: string; title: string; items: [emoji: string, text: string][] };

export const releases: Release[] = [
  { version: '3.10', date: '2 Okt 2026', title: 'Buka aplikasi lebih cepat', items: [
    ['💡', 'Aplikasi kini langsung terbuka dari salinan di HP tanpa menunggu internet. Saat sinyal lambat, Beranda siap dalam kurang dari 1 detik (sebelumnya bisa 4 detik).'],
    ['✅', 'Versi baru tetap masuk sendiri: dicek diam-diam saat aplikasi dibuka, lalu dipakai otomatis begitu siap.'],
  ] },
  { version: '3.9', date: '2 Okt 2026', title: 'Transaksi Terbaru lebih tegas', items: [
    ['💡', 'Transaksi Terbaru di Beranda kini seragam: kiri berisi nama, kategori, dan dompet; kanan berisi nominal dan tanggal. Tidak ada lagi label berwarna yang bikin ramai, dan semua nominal sejajar.'],
  ] },
  { version: '3.8', date: '2 Okt 2026', title: 'Beranda lebih rapi', items: [
    ['💡', 'Transaksi Terbaru di Beranda lebih lega dan tegas: judul satu baris, nominal jelas di kanan, dan tanda “Belum dicek” untuk bunga pindah ke bawah nominal.'],
    ['💡', 'Kartu angka seperti Jatah aman per hari kembali tersusun rapi di tempatnya, tidak perlu digeser lagi.'],
    ['💰', 'Saldo Dompet di Beranda kembali jadi daftar ke bawah per kelompok (Operasional, Tabungan, Investasi), lengkap dengan totalnya.'],
  ] },
  { version: '3.7', date: '2 Okt 2026', title: 'Bunga bisa dihapus', items: [
    ['💰', 'Bunga yang salah kini bisa dihapus (dari detailnya atau geser barisnya). Saldo dompet ikut turun, dan bunga untuk tanggal itu tidak dibuat lagi.'],
  ] },
  { version: '3.6', date: '2 Okt 2026', title: 'Beranda baru yang lebih segar', items: [
    ['💡', 'Kartu atas Beranda baru: sapaan dengan hari dan tanggal, angka utama lebih besar, dan lingkaran hitung mundur ke gajian.'],
    ['💡', 'Beranda dirombak: tiap kartu punya warna sendiri, angka ringkas bisa digeser di HP, dan pemilih periode jadi tombol kecil.'],
    ['📝', 'Catat cepat kini berupa ikon bulat kecil berwarna, dan Transaksi Terbaru menampilkan 5 transaksi terakhir dengan ringkas.'],
    ['💰', 'Anggaran tampil sebagai ubin dengan lingkaran pemakaian, dan Saldo Dompet sebagai kartu berwarna yang bisa digeser.'],
  ] },
  { version: '3.5', date: '2 Okt 2026', title: 'Bunga saldo otomatis', items: [
    ['💰', 'Bunga otomatis per dompet: isi bunga per tahun (boleh desimal, mis. 4,5%), pajak bunga bisa dinyalakan dengan tarif bebas, lalu pilih bunga cair tiap hari, tiap minggu, atau tiap bulan di tanggal pilihanmu.'],
    ['💡', 'Bunga dihitung dari saldo akhir tiap hari dan dibulatkan biasa saat cair (Rp10,77 → Rp11), lengkap dengan simulasi sebelum disimpan. Hari yang terlewat dihitung satu per satu saat aplikasi dibuka, tanpa dobel walau dibuka di dua HP.'],
    ['✅', 'Setiap bunga yang cair bisa dicocokkan dengan bank langsung di menu Transaksi: ketuk “Sesuai”, atau “Ubah” untuk memakai nominal dari bank. Saldo ikut disesuaikan.'],
    ['📝', 'Bagian atas detail dompet kini lebih ringkas: saldo, status bunga, dan tombol aksi dalam satu baris.'],
    ['📷', 'Garis pemindai di Scan struk kini terus bergerak selama struk dibaca.'],
  ] },
  { version: '3.4', date: '2 Okt 2026', title: 'Perbaikan: pembaca struk tidak bisa dimuat', items: [
    ['✅', 'Memperbaiki pesan “Pembaca struk belum bisa dimuat” setelah update 3.3. File pembaca lama yang tersimpan di HP kini diperbarui otomatis, tanpa perlu menghapus data aplikasi.'],
    ['✅', 'Kalau salah satu dari dua pembaca struk gagal dimulai, yang lain tetap membaca. Pesan gagal hanya muncul kalau keduanya tidak bisa.'],
    ['📷', 'HP yang tidak sanggup membaca dengan beberapa inti prosesor sekaligus otomatis memakai mode biasa di scan berikutnya.'],
  ] },
  { version: '3.3', date: '1 Okt 2026', title: 'Scan struk jauh lebih cepat', items: [
    ['📷', 'Scan struk kini sekitar 2–3 kali lebih cepat: pembaca struk memakai beberapa inti prosesor HP sekaligus, dengan hasil baca yang sama.'],
    ['📷', 'Bahan pembaca mulai disiapkan begitu layar Scan struk dibuka, jadi tidak perlu menunggu lagi setelah foto diambil.'],
    ['🔒', 'Pembaca struk tersimpan di HP setelah unduhan pertama dan tidak diunduh ulang. Pesan “Mengunduh pembaca struk” kini hanya muncul saat memang mengunduh; setelah itu langsung membaca, dan pembaca tetap siap selama 10 menit setelah dipakai.'],
    ['💡', 'Struk yang sudah terbaca lengkap tidak dibaca ulang. Bacaan tambahan hanya dipakai kalau ada yang kurang.'],
    ['✅', 'HP dengan RAM 4 GB ke atas (dan iPhone) kini memakai pembaca yang lebih teliti: total dan tanggal lebih sering benar.'],
    ['🧾', 'Struk dengan subtotal sebelum diskon (mis. Alfamart) langsung dianggap cocok, dan jam kirim seperti “07:00 - 22:00” tidak lagi dikira jam belanja.'],
  ] },
  { version: '3.2', date: '1 Okt 2026', title: 'Pembaca struk baru: PP-OCRv6', items: [
    ['📷', 'Scan struk kini memakai pembaca tulisan baru (PP-OCRv6) di HP-mu sendiri. Struk yang miring, pudar, atau difoto di meja lebih sering terbaca benar. Pembaca lama tetap jadi cadangan.'],
    ['🔒', 'Semua tetap dibaca di perangkat: tidak ada foto atau teks yang diunggah. Bahan pembaca diunduh sekali (± 20 MB), setelah itu bisa dipakai offline.'],
    ['🧾', 'Screenshot struk digital (mis. Alfamart, Shopee) langsung dibaca tanpa perlu mengatur sudut, dan tidak lagi diberi peringatan foto terang.'],
    ['🧾', 'Halaman pesanan e-commerce: nama toko dipisahkan dari platform, harga coret ditampilkan sebagai “Harga coret · tidak dihitung”, dan ongkir, voucher, serta biaya layanan masuk ke rincian biaya.'],
    ['✅', 'Alamat, nomor HP, NPWP, nomor pesanan, “Delivered at”, dan cara bayar tidak lagi terbaca sebagai item. “Total Diskon” tidak dihitung dua kali.'],
    ['💰', '“Total Incl. PPN” dikenali sebagai total, dan nama barang dengan kode ukuran (mis. 535MM*8K) tetap terbaca sebagai item.'],
  ] },
  { version: '3.1', date: '1 Okt 2026', title: 'Catat otomatis lebih paham maksudmu', items: [
    ['📝', '“ga jadi”, “batal”, atau “yang parkir ga jadi” kini membatalkan yang dimaksud, jadi tidak ada yang tersimpan untuknya.'],
    ['📝', 'Koreksi untuk satu catatan saja: “yang bensin 75 ternyata”, “eh parkirnya 4rb”, “tapi makan cash”, atau “eh bukan, pake mandiri”.'],
    ['💸', 'Talangan yang diikuti “jadi dia utang ke gue” dicatat sekali sebagai piutang, tidak dobel. “kasih pinjem Budi” = Budi berutang padamu.'],
    ['✅', 'Kalau ada yang kurang, Catat otomatis cukup bertanya satu hal, misalnya “Rp100.000 ke Jago dari dompet mana?”, lengkap dengan pilihan sekali ketuk.'],
    ['💡', '“bayar servis motor” tidak lagi dianggap membayar Utang Motor, dan “yang tadi” yang bisa merujuk ke dua catatan akan ditanyakan.'],
    ['💰', 'Paham “2jt200”, “2 kopi masing-masing 20rb”, “saldo 500rb”, “mau bayar …” (rencana), dan biaya admin transfer yang dicatat terpisah.'],
  ] },
  { version: '3.0', date: '1 Okt 2026', title: 'Scan struk lebih paham isi struk', items: [
    ['🧾', 'Catatan di bawah item (mis. “1 hangat 2 ice”, “less sugar”, “springkle”) kini menempel ke item di atasnya, tampil kecil di bawah nama item, dan tidak lagi tercampur ke nama item berikutnya.'],
    ['🧾', 'Nama item dua baris, diskon member di bawah satu item, dan voucher setelah subtotal kini dibedakan: diskon item mengurangi item itu saja, voucher mengurangi tagihan.'],
    ['🧾', 'Struk toko ritel: nama toko, nama perusahaan (PT/CV), dan cabang dipisahkan; kode varian dan SKU di bawah nama barang ikut tersimpan; PPN yang sudah termasuk harga tidak ditambahkan lagi.'],
    ['✅', 'Yang belum pasti ditanya sekali: “Catatan ini untuk item ini?” atau “Kode terbaca kurang jelas”, cukup ketuk Ya/Bukan.'],
    ['💡', 'Ikon mata kini juga menjelaskan asal nilainya: terbaca langsung dari struk, dihitung, atau diedit manual.'],
    ['📷', 'Tulisan kecil dibaca lebih dekat secara otomatis, dan pembacaan berhenti begitu struk sudah cocok, jadi rata-rata lebih cepat.'],
    ['💸', 'Catatan item ikut terbawa ke Split Bill dan ke Rincian struk di transaksi.'],
  ] },
  { version: '2.10', date: '1 Okt 2026', title: 'Scan struk dibantu Gemini', items: [
    ['🧾', 'Scan struk kini bisa dibantu Gemini (3.5 Flash Lite) untuk membaca tempat, tanggal, item, pajak, diskon, total, dan cara bayar. Hasilnya tetap dicek dulu sebelum disimpan.'],
    ['🔒', 'Hanya potongan struk yang dikirim ke Gemini, bukan foto utuh, dan tidak disimpan di akunmu. Bisa dimatikan di layar Scan struk (“Bantu baca dengan Gemini”). Saat mati, offline, atau Gemini sedang penuh, struk dibaca di perangkat seperti biasa.'],
  ] },
  { version: '2.9', date: '28 Sep 2026', title: 'Detail dompet lebih terbaca di mode gelap', items: [
    ['📝', 'Di detail dompet, teks kecil (jenis dompet, saldo awal) dan nomor rekening kini jelas terbaca di mode gelap maupun di warna dompet yang terang seperti biru Jenius.'],
  ] },
  { version: '2.8', date: '28 Sep 2026', title: 'Nomor rekening hanya di detail dompet', items: [
    ['🔒', 'Nomor rekening tidak lagi tampil di daftar dompet (kartu maupun Ringkas). Nomornya ada di dalam, saat dompet diketuk, tetap tersamar dengan ikon mata dan salin.'],
  ] },
  { version: '2.7', date: '28 Sep 2026', title: 'Nomor rekening disamarkan', items: [
    ['🔒', 'Nomor rekening kini tampil disamarkan (•••• 7890). Ketuk ikon mata untuk melihat nomor lengkap; setelah 5 detik otomatis disamarkan lagi. Ikon salin tetap menyalin nomor lengkap.'],
    ['💰', 'Tampilan nomor rekening diperbarui: chip kaca kecil dengan lencana bank. Di tampilan Ringkas, nomornya tampil di baris sendiri di bawah nama dompet supaya tidak terpotong.'],
  ] },
  { version: '2.6', date: '28 Sep 2026', title: 'Nomor rekening di dompet', items: [
    ['💰', 'Dompet kini bisa diberi nomor rekening (atau nomor e-wallet) lewat Ubah dompet. Nomornya tampil kecil di kartu, di tampilan Ringkas, dan di detail dompet, dengan ikon salin. Yang disalin hanya angkanya, tanpa spasi.'],
  ] },
  { version: '2.5', date: '28 Sep 2026', title: 'Pilih layar pembuka', items: [
    ['💡', 'Di Pengaturan → Tampilan → Layar pembuka, pilih “Sapaan nama” (Halo, namamu! dengan kartu kaca) atau “Standar” (logo aplikasi seperti sebelumnya). Pilihan tersimpan di akun dan diingat di HP, jadi langsung dipakai saat aplikasi dibuka.'],
  ] },
  { version: '2.4', date: '28 Sep 2026', title: 'Sapaan baru saat membuka aplikasi', items: [
    ['💡', 'Saat aplikasi dibuka kini muncul sapaan “Halo, (namamu)! Selamat datang kembali” dengan tangan melambai, di kartu kaca buram di tengah layar dengan latar warna yang bergerak lembut. Tampil rapi di mode terang dan gelap.'],
  ] },
  { version: '2.3', date: '28 Sep 2026', title: 'Yang dihapus benar-benar hilang dari cloud, foto struk tampil terpotong', items: [
    ['🔒', 'Yang dihapus di aplikasi kini juga terhapus di Firestore. Draf rutin yang dilewati dan kategori yang digabung langsung dihapus (dulu hanya ditandai). Dompet, kategori, atau kantong yang tersembunyi karena masih punya riwayat ikut terhapus otomatis begitu transaksinya dihapus.'],
    ['🔒', 'Catatan penghapusan untuk sinkron antar-HP dibersihkan sendiri setelah seminggu, dan ikut terhapus saat Reset semua data atau Hapus akun.'],
    ['📷', 'Setelah area struk ditentukan, foto yang tampil (saat membaca, gambar kecil di atas, Seluruh struk, penanda letak angka, dan yang dibawa ke Split Bill) kini potongan struk yang sudah diluruskan. Foto utuh hanya muncul saat mengubah area lewat Atur sudut.'],
  ] },
  { version: '2.2', date: '28 Sep 2026', title: 'Split Bill dibagikan sebagai nota', items: [
    ['🧾', 'Bagikan Split Bill kini berupa nota seperti struk: nama tagihan, tempat, tanggal, lalu per orang semua item beserta pajak/service, diskon, dan totalnya, ditutup total tagihan dan “Bayar ke”. Tanda lunas atau sisa ikut tampil.'],
    ['🧾', 'Nota bisa dibagikan sebagai gambar struk atau sebagai teks rapi berkolom untuk grup WhatsApp. Bisa juga dibuat untuk satu orang saja.'],
    ['📝', 'Kotak dan tulisan saat mengubah item Split Bill dibuat lebih kecil supaya proporsional.'],
  ] },
  { version: '2.1', date: '28 Sep 2026', title: 'Magnet saat menentukan area struk', items: [
    ['📷', 'Saat menentukan area struk, titik sudut yang diseret kini menempel ke sudut kertas terdekat, dan sisi yang diseret menempel ke tepi kertas (termasuk yang miring). Garis berubah hijau dan muncul “Menempel ke tepi struk”. Magnet bisa dimatikan.'],
    ['📷', 'Tombol “Rapikan” meluruskan keempat sisi ke tepi struk sekaligus.'],
    ['📝', 'Tombol di layar area struk dirombak: Magnet, Rapikan, Putar, dan Ulangi dalam satu baris ringkas, tombol kamera bulat untuk ambil ulang, dan satu tombol besar “Baca struk”.'],
  ] },
  { version: '2.0', date: '28 Sep 2026', title: 'Versi 2.0: tanpa unggahan sama sekali, item bisa diubah saat membagi', items: [
    ['🔒', 'Aplikasi tidak lagi mengunggah file apa pun. Foto struk hanya dibaca di HP ini lalu dibuang. Data disimpan di Firestore seperti biasa, dan Firebase Storage tidak dipakai lagi (termasuk lampiran klaim).'],
    ['🧾', 'Split Bill: saat membagi item, nama, jumlah, dan harganya bisa langsung diubah di kartu yang sama. Tidak perlu membuka “Atur item” lagi.'],
    ['📝', 'Kartu item Split Bill dirapikan: pilihan Rata / Per porsi / Nominal di satu baris, diskon dan kategori dilipat dalam “Diskon & kategori”, lalu tombol Hapus dan Selesai di bawah.'],
    ['💡', 'Penomoran versi baru: 2.0, 2.1, sampai 2.10, lalu 3.0, dan seterusnya.'],
  ] },
  { version: '99', date: '28 Sep 2026', title: 'Kartu hari yang dilipat lebih rapi', items: [
    ['📝', 'Di Transaksi dan Beranda, hari yang dilipat kini menumpuk nominal masuk dan keluar di kanan, dengan jumlah transaksi di bawahnya. Nama hari tetap satu baris dan kotak tanggal tidak lagi menyempit.'],
  ] },
  { version: '98', date: '28 Sep 2026', title: 'Kamera scan rapi, ketuk untuk fokus, notifikasi “Sudah habis”', items: [
    ['📷', 'Tombol “Ganti lensa” tidak lagi bertumpuk dengan ikonnya. Di layar kecil, petunjuk kamera tidak menutupi tombol tutup dan “Kamera bawaan” tetap di dalam layar.'],
    ['📷', 'Ketuk struk di layar kamera untuk fokus: titik yang diketuk kini tepat (walau gambar terpotong di layar) dan fokus tetap di titik itu, tidak kembali ke tengah. Kalau HP tidak mengizinkan, muncul keterangan “Fokus diatur otomatis oleh HP ini”.'],
    ['💰', 'Notifikasi anggaran yang terpakai pas di batas kini “Anggaran … sudah habis”, bukan “terlewati”. Laporan juga tidak lagi menandainya merah.'],
  ] },
  { version: '97', date: '28 Sep 2026', title: 'Laporan utang lebih terbaca, anggaran “Sudah habis”, bulatkan ringkas', items: [
    ['📝', 'Laporan utang & piutang: teks di kartu atas kini jelas terbaca (juga di mode gelap), rincian tersusun rapi per baris, dan kartu ringkasan sama tinggi dengan label yang lebih singkat.'],
    ['💰', 'Anggaran yang terpakai pas sama dengan batasnya kini ditulis “Sudah habis”, bukan “terlewati”. “Terlewati” hanya muncul kalau benar-benar lebih dari batas.'],
    ['🧾', 'Menu bulatkan di Split Bill kini satu baris ringkas: pilih 34rb / 35rb / 40rb, ikon pensil untuk isi sendiri, dan ikon kembalikan ke angka asli.'],
  ] },
  { version: '96', date: '28 Sep 2026', title: 'Split Bill: pilih yang bayar, bulatkan per orang, kelola teman', items: [
    ['💰', 'Siapa yang bayar kini langsung dipilih di bagian Orang: ketuk nama orangnya (termasuk “Saya” walau tidak ikut patungan).'],
    ['🧾', 'Di rincian per orang, total seseorang bisa dibulatkan (↑ Rp35.000, ↑ Rp40.000, ↓ Rp34.000) atau diisi sendiri. Selisihnya ditanggung yang bayar, jadi total tetap sama dengan struk. Bisa dikembalikan ke angka asli.'],
    ['📝', 'Orang tersimpan tampil sebagai daftar rapi (urut A–Z, bisa dicari, berapa tagihan yang diikuti, grupnya) dan bisa diubah atau dihapus, juga langsung dari dalam Split Bill lewat “Kelola orang tersimpan”.'],
  ] },
  { version: '95', date: '28 Sep 2026', title: 'Laporan utang & piutang, Keluar/Masuk ikut arus uang', items: [
    ['💸', 'Di menu Transaksi, Keluar kini termasuk bayar utang, talangan ke teman, dan talangan kantor; Masuk termasuk piutang yang dibayar, uang pinjaman (ngutang), dan klaim yang cair. Ringkasan dan total per hari mengikuti arus uang yang sama.'],
    ['📝', 'Laporan utang & piutang baru (menu Utang & Piutang → Laporan): posisi bersih sekarang, pergerakan per periode, tren 6 bulan, jatuh tempo 30 hari, piutang per orang, utang aktif dengan perkiraan lunas, klaim kantor yang menunggu, dan riwayat pergerakannya.'],
  ] },
  { version: '94', date: '27 Sep 2026', title: 'Hapus dengan konfirmasi, langsung diproses', items: [
    ['✅', 'Menghapus kini meminta konfirmasi sekali (“Hapus transaksi?”), lalu langsung dihapus dengan kartu progres sampai “terhapus dari cloud”. Pemberitahuan “Batalkan” yang mengambang dihilangkan. Berlaku juga untuk geser-untuk-hapus, anggaran, jadwal rutin, dan wish list.'],
  ] },
  { version: '93', date: '27 Sep 2026', title: 'Hapus yang pasti sampai ke cloud, nominal terlihat saat mengisi', items: [
    ['🔒', 'Saat nominal disembunyikan, angka di formulir, Scan struk, dan jendela ubah lainnya tetap terlihat supaya mudah dicek. Saldo dompet di dalamnya tetap disamarkan, begitu juga seluruh halaman lain.'],
    ['✅', 'Setelah menghapus, kamu diberi tahu statusnya: “terhapus dari cloud”, atau saat offline “terhapus di perangkat” lalu “terhapus dari cloud” begitu online.'],
    ['💡', 'Kalau aplikasi ditutup sebelum penghapusan terkirim (bahkan masih di jendela Batalkan), transaksinya tetap tersembunyi dan dihapus dari cloud otomatis saat aplikasi dibuka lagi atau kembali online. Hanya penghapusan yang ditolak server yang membuatnya muncul lagi.'],
  ] },
  { version: '92', date: '27 Sep 2026', title: 'Hapus transaksi tidak lagi butuh koneksi', items: [
    ['✅', 'Menghapus transaksi biasa kini langsung tercatat di perangkat dan dikirim otomatis ke cloud, walau sedang offline, sinyal lemah, atau aplikasi langsung ditutup. Sebelumnya penghapusan harus menunggu server dan bisa batal di tengah jalan.'],
    ['🔒', 'Kalau server menolak penghapusan, transaksinya tampil lagi dengan pesan alasannya di lonceng notifikasi.'],
  ] },
  { version: '91', date: '27 Sep 2026', title: 'Hapus transaksi lebih andal, formulir rapi lagi', items: [
    ['🔒', 'Transaksi yang kamu hapus dicatat di perangkat ini dan tidak ditampilkan atau dihitung lagi, walau salinan lamanya masih tertinggal. Saat aplikasi dibuka, server ditanya sekali untuk memastikan; kalau ternyata masih ada di server, transaksinya ditampilkan lagi apa adanya.'],
    ['✅', 'Pilihan Keluar · Masuk · Transfer di formulir transaksi tampil normal lagi (sempat menyempit).'],
    ['💡', 'Transaksi bagian dari Split Bill menjelaskan cara menghapusnya: buka Split Bill lalu pilih Batalkan.'],
    ['📷', 'Langkah Tentukan area struk: foto sedikit lebih pendek dan tombol di bawah diberi jarak dari tepi layar.'],
    ['📝', 'Versi baru aplikasi langsung dipakai saat aplikasi dibuka, tanpa menunggu kamu mengetuk pemberitahuan pembaruan.'],
  ] },
  { version: '90', date: '27 Sep 2026', title: 'Satu kartu per hari', items: [
    ['✅', 'Judul hari kini menyatu di kartu hari itu, ditulis tebal, dan total pengeluaran hari itu berwarna merah. Ketuk judulnya untuk melipat.'],
    ['💡', 'Isi kartu lebih modern: kategori tampil sebagai pil berwarna, dompet di sebelahnya, dan jam dalam pil kecil di bawah nominal.'],
    ['📝', 'Ringkasan di atas daftar cukup “Selisih · 134 transaksi”.'],
  ] },
  { version: '89', date: '27 Sep 2026', title: 'Kartu transaksi bergaya kaca, hari bisa dilipat', items: [
    ['💡', 'Setiap hari di daftar transaksi bisa dilipat: ketuk judul harinya. Hari yang dilipat menampilkan jumlah transaksi dan totalnya, dan tetap terlipat saat aplikasi dibuka lagi di perangkat ini.'],
    ['✅', 'Kartu transaksi bergaya kaca: tepi bergradien, kilau lembut, ikon kategori kaca berwarna, dan cahaya latar yang halus. Judul hari menempel sebagai pil kaca saat digulir.'],
    ['📝', 'Transaksi Terbaru di Beranda memakai tampilan yang sama, dikelompokkan per hari.'],
    ['📷', 'Saat menentukan area struk, foto dibuat sedikit lebih pendek dan tombol “Ambil ulang” dan “Baca struk” selalu terlihat di bawah layar.'],
  ] },
  { version: '88', date: '27 Sep 2026', title: 'Halaman Transaksi baru, grafik tanpa kotak', items: [
    ['💸', 'Halaman Transaksi dirombak: satu kartu ringkasan (selisih besar, bar masuk dan keluar, jumlah transaksi), pilihan cepat Semua · Keluar · Masuk · Transfer, dan setiap hari punya judul bertanggal (24 · Kamis, “Hari ini”, “Kemarin”) di atas kartunya sendiri.'],
    ['✅', 'Baris transaksi lebih tenang: titik warna kategori, dompet, dan jam; pengeluaran ditulis dengan warna teks biasa, pemasukan hijau.'],
    ['📝', 'Mengetuk grafik tidak lagi memunculkan kotak di sekeliling grafik, dan titik warna di keterangan grafik kini sesuai warna datanya.'],
  ] },
  { version: '87', date: '27 Sep 2026', title: 'Hapus transaksi otomatis tidak muncul lagi, tampilan lebih rapi', items: [
    ['✅', 'Menghapus transaksi dari jadwal rutin “Catat otomatis” kini benar-benar menghapusnya: jadwal hari itu ditandai dilewati, jadi tidak dicatat ulang. Sebelumnya transaksinya langsung muncul kembali.'],
    ['🔒', 'Transaksi yang sudah terhapus juga langsung hilang dari salinan data di perangkat, dan baris yang dihapus hanya muncul lagi bila penghapusannya gagal.'],
    ['📝', 'Wish list tidak lagi melebar keluar layar di HP. Menu “Lainnya” di kartu utang dan piutang tidak lagi terpotong di sisi kiri layar.'],
    ['💡', 'Beranda lebih ringkas di HP: tanggal periode tidak diulang di setiap kartu, dan kartu terakhir yang sendirian dibuat melebar. Tombol Dompet, nama anggaran yang panjang, dan label grafik Proyeksi tidak lagi terpotong atau bertumpuk.'],
  ] },
  { version: '86', date: '27 Sep 2026', title: 'Mengetik di Catat otomatis lebih ringan', items: [
    ['✅', 'Huruf yang kamu ketik di Catat otomatis langsung muncul; pembacaan kalimat dan kartunya menyusul sesaat kemudian, jadi tidak lagi terasa tersendat di HP. Kartu yang tidak berubah tidak digambar ulang.'],
    ['🔒', 'Menekan Enter tepat setelah mengetik tetap menyimpan kalimat yang lengkap, bukan potongan yang belum selesai dibaca.'],
  ] },
  { version: '85', date: '27 Sep 2026', title: 'Tentukan area struk dulu, lensa kamera, dan biaya tambahan yang seragam', items: [
    ['📷', 'Setelah foto diambil atau dipilih, kamu menentukan area struknya dulu: geser titik atau sisi ke tepi struk, putar bila perlu, lalu “Baca struk”. Hanya bagian di dalam garis yang dibaca. Peringatan foto (buram, gelap, pudar) muncul di langkah ini, dengan pilihan “Ambil ulang”.'],
    ['🔒', 'Kamera tidak lagi mengingat lensa ultra-wide. Nama kamera berbahasa Indonesia (mis. “Kamera Ultra Lebar Belakang”) kini dikenali, lensa yang tidak bisa dibedakan dari namanya dicek dari kemampuannya (fokus otomatis, ukuran sensor), dan ada tombol “Ganti lensa” yang pilihannya diingat.'],
    ['✅', 'Tambahan & diskon di Split Bill tidak lagi macet saat dibuka-tutup. Pilihan jenis biaya muncul sebagai tombol di tempat, bukan menu melayang.'],
    ['💸', 'Nominal manual dan Persentase di Split Bill lebih rapi: nama di kiri, isian di kanan, total per orang di bawah nama, dan “Terisi … dari …” untuk melihat sisa yang belum dibagi.'],
    ['🧾', 'Biaya tambahan di Scan struk (pengeluaran dan pemasukan) kini tampil seperti di Split Bill: satu baris per biaya dengan ikon, ketuk untuk mengubah nominal, pilih 10%/11% cepat, tandai “Sudah termasuk harga”, atau hapus. “+ Tambah” untuk diskon, pajak, service, ongkir, biaya lain, atau pembulatan.'],
  ] },
  { version: '84', date: '27 Sep 2026', title: 'Split Bill lebih ringkas, scan struknya selengkap Scan struk', items: [
    ['🧾', 'Scan struk dari Split Bill kini memakai pemeriksaan struk yang sama dengan Scan struk: atur sudut, baca ulang, lihat di foto, foto lanjutan, ubah item, diskon, dan biaya. Tombolnya “Gunakan di Split Bill”, dan tidak ada transaksi yang tersimpan dari sana.'],
    ['✅', 'Yang sudah kamu perbaiki ikut masuk ke Split Bill. Diskon item tetap menempel di itemnya, jadi yang dibagi adalah harga bersihnya (Burger Rp50.000 − Rp10.000 → Rp40.000). Voucher, pajak, service, ongkir, dan biaya admin masuk sebagai biaya tambahan.'],
    ['💡', 'Split Bill jadi satu halaman: orang, item (ketuk untuk memilih siapa yang pesan), tambahan & diskon, total per orang (ketuk untuk rinciannya), dan “Cocok” atau selisihnya dengan total struk. Satu tombol “Selesai membagi”.'],
    ['📷', 'Kamera scan memilih kamera belakang utama (1×), bukan ultra-wide, bila browser memberi tahu lensanya, dan mengingat pilihan itu. Fokus otomatis terus-menerus dipakai bila didukung, dan ketuk-untuk-fokus hanya muncul di kamera yang benar-benar mendukungnya. Kamera bawaan tetap bisa dipakai.'],
  ] },
  { version: '83', date: '27 Sep 2026', title: 'Scan struk dan Catat otomatis lebih ringkas', items: [
    ['🧾', 'Hasil scan dimulai dari yang penting: tempat, tanggal, cara bayar, total besar, jumlah item, dan “Total cocok dengan rincian” atau berapa bagian yang perlu dicek. Yang perlu dicek langsung di bawahnya, lengkap dengan “Gunakan …” dan “Baca ulang”.'],
    ['💡', 'Item jadi baris sederhana (diskon item di bawahnya), biaya dan pajak dalam satu rincian, dan tombol foto (atur sudut, baca ulang, foto lanjutan, Split Bill, dll.) dikumpulkan di menu ⋯. Satu tombol Simpan yang jelas.'],
    ['📷', 'Atur sudut seperti aplikasi pemindai: bagian luar digelapkan, titik sudut besar, sisi bisa digeser, kaca pembesar saat menggeser, pratinjau struk yang sudah diluruskan, lalu Ulangi atau Gunakan.'],
    ['📝', 'Rincian struk ikut tersimpan: buka transaksinya nanti untuk melihat item, diskon, pajak, cara bayar, dan nomor struk. Catatan transaksi tidak lagi dipenuhi teks struk, dan struk tetap utuh walau nominal transaksinya diubah.'],
    ['✅', 'Catat otomatis lebih tenang: empat pilihan jenis dulu (sisanya di “Lainnya”), tiga contoh, pratinjau berupa ringkasan dengan tombol Simpan dan Ubah, dan hanya isian yang belum jelas yang ditandai.'],
  ] },
  { version: '82', date: '27 Sep 2026', title: 'Catat otomatis 2.0: satu pesan, banyak catatan', items: [
    ['📝', 'Satu pesan bisa berisi beberapa hal berbeda sekaligus: “besok bayar kos 1,5jt, ingetin perpanjang stnk tanggal 20, sama budget makan bulan depan 2jt” jadi rencana, pengingat, dan anggaran. Tiap catatan bisa diubah, dilewati, atau dibaca ulang sebagai jenis lain sebelum “Simpan semua”.'],
    ['💡', 'Mengerti koreksi dan rujukan: “makan 30rb eh 35rb”, “pakai gopay, bukan bca”, “kemarin, eh tadi pagi”, “dua-duanya pakai gopay”, “yang bensin pakai bca”, “sisanya pakai gopay”. Tanggal atau dompet yang disebut di satu bagian tidak menimpa yang disebut sendiri di bagian lain.'],
    ['✅', 'Tiap isian punya status: Terverifikasi, Kemungkinan benar, Perlu dicek, atau Belum terbaca. Hanya yang ragu yang ditandai, dan ketuk “Kenapa?” untuk melihat alasannya.'],
    ['🔒', 'Tidak menebak data keuangan: transfer tanpa dompet asal, dua nominal, dua dompet, dua tanggal, atau utang yang hanya mirip sebagian (“cicilan motor” bukan “Cicilan laptop”) diminta dipilih dulu, bukan diisi sendiri.'],
    ['💸', 'Lebih paham tulisan sehari-hari: kemaren, trf, go pay, 350rbu, 1.5jt, akhir bulan, awal bulan depan, pas gajian berikutnya, senin kemarin, jam 7 pagi. Nomor kamar, meja, atau rekening tidak lagi dibaca sebagai uang.'],
  ] },
  { version: '81', date: '27 Sep 2026', title: 'Konfirmasi struk lebih rapi', items: [
    ['📝', 'Tanggal, jam, tempat, dompet, kategori, keterangan, dan catatan kini dalam satu kartu ringkas: label di kiri, isian di kanan.'],
    ['🧾', 'Biaya tambahan jadi bagian yang bisa dibuka-tutup (tertutup dulu), dengan jumlah dan hasil hitungnya terlihat di judul.'],
    ['💡', 'Kotak isian lebih kecil dan membulat penuh, jadi layar tidak cepat penuh.'],
  ] },
  { version: '80', date: '27 Sep 2026', title: 'Hasil Scan struk lebih ringkas', items: [
    ['🧾', 'Item di struk kini satu baris per item (nama, jumlah, kategori, dan harga); ketuk item untuk mengubahnya.'],
    ['📝', 'Tombol foto (putar, sudut, baca ulang, foto lanjutan, ganti) jadi satu baris kecil, tanggal dan jam berdampingan, dan kolom isian lebih ringkas.'],
    ['💡', 'Bagian yang jarang dipakai dilipat: biaya & diskon (terbuka otomatis bila total belum cocok), pembayaran, catatan, dan detail hasil baca. Pilihan nominal lain cukup satu baris yang bisa digeser.'],
  ] },
  { version: '79', date: '27 Sep 2026', title: 'Scan struk 2.0: memahami struk, bukan sekadar membaca', items: [
    ['📷', 'Struk dicari keempat sudutnya lalu diluruskan penuh, jadi foto yang miring atau diambil dari samping tetap terbaca. Bayangan diratakan, dan struk yang terpotong bayangan tidak lagi kehilangan sisinya. Ada kamera dengan panduan (“Dekatkan kamera”, “Struk ditemukan”) dan foto otomatis bila mau.'],
    ['✅', 'Beberapa pembacaan digabungkan angka demi angka. Yang sama dipercaya, yang berbeda disimpan sebagai pilihan, dan hitungan dipakai hanya bila ada satu-satunya cara struk cocok. Hasilnya: Terverifikasi, Kemungkinan benar, Perlu dicek, atau Belum terbaca.'],
    ['🧾', 'Hasil scan hanya meminta kamu memeriksa yang ragu. Ketuk ikon mata untuk melihat di bagian mana struk angka itu dibaca, baca ulang satu bagian saja, atau atur sudut struk tanpa foto ulang.'],
    ['💡', 'Lebih paham isi struk: nama item dua baris, catatan item (NO ICE), tambahan berbayar, diskon per item, voucher, diskon ongkir, asuransi pengiriman, cashback (tidak mengurangi yang dibayar), BBM (liter × harga), parkir, nomor struk, dan cara bayar dari bagian pembayaran (promo GoPay di bawah tidak dianggap cara bayar).'],
    ['🔒', 'Struk panjang bisa difoto beberapa kali (Foto lanjutan) tanpa item ganda, dan struk yang mirip transaksi lama diberi peringatan sebelum disimpan. Semua tetap dibaca di perangkat ini.'],
  ] },
  { version: '78', date: '27 Sep 2026', title: 'Hasil Scan struk lebih rapi', items: [
    ['🧾', 'Layar hasil scan dirapikan untuk HP: foto jadi kecil (ketuk untuk memperbesar), tombolnya di samping foto, rincian biaya tidak berdempetan, dan tombol Simpan lebih ramping sambil menampilkan nominalnya.'],
    ['💡', 'Kategori kini dipilih dari daftar per kategori utama yang bisa dibuka-tutup, lengkap dengan pencarian, untuk kategori transaksi, tiap item, dan biaya yang dicatat terpisah.'],
    ['📝', 'Tiap item menampilkan total barisnya (jumlah × harga), dan kategori item tidak lagi terpotong.'],
  ] },
  { version: '77', date: '27 Sep 2026', title: 'Catat otomatis paling bisa diandalkan', items: [
    ['📝', 'Beberapa catatan sekaligus: “kemarin makan 25rb, parkir goceng, bensin 30rb pakai gopay” atau satu baris per catatan. Tanggal atau dompet yang disebut sekali berlaku untuk semuanya; baris bisa dilewati sebelum “Simpan semua”.'],
    ['💡', 'Anggaran bisa memilih subkategori: “budget makan 2jt untuk sarapan, makan siang dan kopi”, “kecuali delivery”, “selain bioskop”, “khusus sarapan”, “makan siang dan malam”. Pratinjau menampilkan chip subkategori yang bisa diketuk.'],
    ['💰', 'Nominal dalam kata dan bahasa gaul: dua puluh lima ribu, satu setengah juta, sejuta setengah, setengah juta, goceng, ceban, gocap, cepek. Tanggal “3/9” juga dikenali.'],
    ['💸', 'Arah uang selalu benar: top up GoPay dari BCA, isi GoPay pakai BCA, tarik tunai (bank ke Tunai), dan setor tunai (Tunai ke bank).'],
    ['✅', 'Konteks lebih pintar: freelance dan proyek jadi pemasukan, transferan dari orang tua jadi Hadiah Uang, dan grab/gojek masuk Taxi / Online.'],
  ] },
  { version: '76', date: '27 Sep 2026', title: 'Scan struk membaca semua biaya, Catat otomatis lebih cerdas', items: [
    ['🧾', 'Scan struk membaca diskon dan potongan (termasuk persen, voucher, promo ongkir), pajak (PB1, PPN, PBJT), service, ongkir, biaya lain (admin, kemasan, aplikasi, tip), dan pembulatan, dari struk resto, minimarket, GoFood/GrabFood, sampai marketplace.'],
    ['📝', 'Pengeluaran dari struk kini punya Rincian biaya yang bisa diubah, dengan hasil hitung yang langsung dicocokkan. Biaya bisa digabung ke belanja atau dicatat terpisah dengan kategorinya sendiri, dan rinciannya tersimpan di catatan transaksi.'],
    ['✅', 'Tanggal dan jam lebih tepat: tanggal kedaluwarsa voucher dan kode kasir tidak lagi terbaca sebagai tanggal, dan format AM/PM, WIB, serta tanggal gaya Amerika dikenali. PPN yang sudah termasuk harga tidak dihitung dua kali.'],
    ['💡', 'Catat otomatis lebih cerdas: “budget makan 2jt” masuk Makan & Minum, sedangkan “budget makan traveling” masuk Travel › Makan. Kata seperti ngopi, groceries, ortu, dan “pulsa dan kuota” dikenali.'],
    ['💰', 'Pengeluaran saat liburan atau dinas masuk ke subkategori yang pas, misalnya “makan pas liburan” ke Travel › Makan dan “grab waktu liburan” ke Transport Lokal.'],
  ] },
  { version: '75', date: '27 Sep 2026', title: 'Tambah/kurangi utang & piutang, Scan struk lebih pintar', items: [
    ['💸', 'Utang dan piutang kini bisa ditambah atau dikurangi. Pinjam atau meminjamkan lagi bisa langsung lewat dompet; potongan dan diskon cukup dikurangi. Ada juga Atur sisa, dan perubahan terakhir bisa dibatalkan dari Riwayat.'],
    ['📷', 'Scan struk mencari struk di foto, meluruskan foto miring, meratakan bayangan, dan membaca ulang dengan cara lain bila belum cocok. Foto yang diambil menyamping diputar otomatis.'],
    ['✅', 'Grand total tidak lagi masuk ke daftar item. Angka di bawah total (nomor kartu, kode approval, kembalian) tidak dianggap belanjaan.'],
    ['💡', 'Lebih pintar membaca struk minimarket (PPN sudah termasuk, DPP), kata yang salah baca (T0TAL, GRAND TOTAI), dan teks yang tersalin per kolom. Nama toko besar dikenali.'],
    ['📝', 'Angka yang salah baca dibetulkan hanya bila hasilnya pas dengan subtotal atau total (misalnya 6.920 jadi 6.900), dan setiap koreksi ditampilkan untuk kamu periksa.'],
  ] },
  { version: '74', date: '27 Sep 2026', title: 'Scan struk', items: [
    ['📷', 'Foto struk atau nota, lalu nominal, tanggal, jam, tempat, item, pajak, service, diskon, dan cara bayar dibaca otomatis. Ada di tombol + (Catat cepat) dan di formulir Catat transaksi.'],
    ['✅', 'Selalu dikonfirmasi dulu: periksa dan ubah semuanya sebelum disimpan. Aplikasi mencocokkan total, item, dan uang bayar dikurangi kembalian, lalu memberi tahu kalau ada yang belum pas.'],
    ['💡', 'Dompet ditebak dari cara bayar (tunai, QRIS, GoPay, OVO, dan lainnya) dan kategori dari tempat serta item. Belanja campuran bisa dipisah per kategori.'],
    ['🧾', 'Split Bill kini memakai pembaca yang sama, dan hasil scan bisa langsung dijadikan Split Bill.'],
    ['🔒', 'Foto dibaca di perangkat ini, tidak diunggah untuk dibaca, dan gratis. Bisa juga tempel teks struk.'],
  ] },
  { version: '73', date: '27 Sep 2026', title: 'Perbarui saldo utang & piutang, Arsip, dan privasi', items: [
    ['✏️', 'Utang dan piutang kini punya “Perbarui saldo” untuk bunga, denda, potongan, atau salah catat, tanpa mengubah saldo dompet.'],
    ['📝', 'Riwayat lengkap tiap utang dan piutang: pembayaran lewat dompet, pelunasan tanpa dompet, dan setiap perubahan saldo.'],
    ['🗂️', 'Mode Ringkas satu baris per catatan, dan yang sudah lunas pindah ke tab Arsip, dikelompokkan per bulan dan hari yang bisa dilipat.'],
    ['🔒', 'Pengaturan → Tampilan: “Selalu sembunyikan nominal” setiap aplikasi dibuka.'],
    ['🧾', 'Biaya tambahan Split Bill kini dipilih dari menu yang rapi, dan tiap biaya bisa dilipat.'],
  ] },
  { version: '72', date: '27 Sep 2026', title: 'Split Bill', items: [
    ['🧾', 'Menu baru Split Bill: bagi rata, sesuai pesanan (item berbagi dan per porsi), nominal manual, atau persentase, lengkap dengan pajak, service, diskon, ongkir, pembulatan, dan biaya bersama. Pembagian selalu pas sampai Rupiah terakhir.'],
    ['💳', 'Uang keluar dan pengeluaranmu dibedakan: bayar Rp600rb untuk berempat, saldo dompet berkurang Rp600rb tapi anggaran dan analisis hanya menghitung bagianmu. Bagian teman jadi piutang yang tertaut.'],
    ['🤝', 'Teman membayar balik tidak dihitung pemasukan; kalau orang lain yang bayar, bagianmu jadi pengeluaran dan utang, dan melunasinya tidak dihitung pengeluaran lagi.'],
    ['📷', 'Bisa dari transaksi yang sudah ada, dari foto struk (teks dibaca bila perangkat mendukung, atau tempel teks struk), atau dihitung manual; hasil baca selalu diperiksa dulu.'],
    ['📝', 'Status tiap orang, pembayaran sebagian, orang tersimpan dan grup, bagikan teks atau gambar ke WhatsApp, dan pengingat yang bisa kamu ubah sebelum dikirim.'],
    ['📊', 'Terhubung ke Beranda, Insight, Laporan, Periksa Data, Piutang, dan Utang.'],
  ] },
  { version: '71', date: '27 Sep 2026', title: 'Kategori yang membaca konteks', items: [
    ['💡', 'Kata yang punya banyak arti dibaca dari konteksnya: “beli air 5rb di alfa” jadi minuman, “bayar air 150rb” jadi tagihan air; “tiket kereta” masuk transportasi, “tiket konser” masuk hiburan; “grabfood” masuk makanan.'],
    ['✅', 'Arah uang ikut dibaca: “gaji art”, “thr art”, dan “tiket masuk” tetap pengeluaran; “bunga deposito”, “komisi”, dan “dapat hadiah” jadi pemasukan.'],
    ['🔄', 'Belajar dari kebiasaanmu: barang, tempat, dan kata yang biasa kamu catat di satu kategori ikut diperhitungkan.'],
    ['📝', 'Alasan pilihan kategori ditampilkan, dan formulir transaksi kini menyarankan kategori dari keterangan yang kamu ketik.'],
  ] },
  { version: '70', date: '26 Sep 2026', title: 'Catat otomatis untuk semua menu', items: [
    ['🚀', 'Satu kalimat kini bisa membuat anggaran, tujuan dana, wish list, dompet, kategori, jadwal rutin, rencana, dan pengingat, contohnya “anggaran makan 2jt” atau “langganan netflix 54rb tiap tanggal 5”.'],
    ['💰', 'Perbarui saldo cukup dengan “saldo bca sekarang 12jt”; selisihnya dicatat sebagai penyesuaian.'],
    ['🧭', 'Ketik “buka laporan”, “lihat utang”, atau “pengingat” untuk langsung pindah ke menunya.'],
    ['📝', 'Tanggal bisa ditulis bebas: besok, lusa, tgl 5, 17 agustus, minggu depan. Pengeluaran yang masih akan datang disimpan sebagai rencana.'],
    ['✅', 'Dompet default dan pilihan dompet kini mengikuti urutan di halaman Dompet.'],
  ] },
  { version: '69', date: '26 Sep 2026', title: 'Catat otomatis lebih jelas', items: [
    ['📝', 'Teks Catat otomatis dirapikan, dan contoh kalimat tampil sebagai kartu yang tinggal diketuk, lengkap dengan hasilnya.'],
  ] },
  { version: '68', date: '26 Sep 2026', title: 'Tombol Catat otomatis', items: [
    ['🚀', 'Tombol khusus “Catat otomatis” di atas Pengeluaran dan Pemasukan: ketik, cek pratinjau, lalu “Sesuai, simpan”.'],
  ] },
  { version: '67', date: '26 Sep 2026', title: 'Ketik cepat makin pintar', items: [
    ['🚀', 'Ketik cepat kini paham utang, piutang, klaim kantor, target, dan wish list, bukan hanya masuk dan keluar.'],
    ['✅', 'Pratinjau langsung saat mengetik, lalu Simpan sekali ketuk. Salah tebak? Ketuk “Bukan?” atau pilih jenisnya.'],
  ] },
  { version: '66', date: '26 Sep 2026', title: 'Ketik cepat', items: [
    ['🚀', 'Tulis “beli pocari 8rb di alfa”, formulir transaksi langsung terisi: nominal, tempat, kategori, dompet, dan tanggal.'],
  ] },
  { version: '65', date: '26 Sep 2026', title: 'Utang, piutang, dan grafik pemasukan', items: [
    ['💳', 'Bayar utang dan pelunasan piutang bisa diberi kategori dan masuk ke laporan.'],
    ['📊', 'Grafik kategori untuk pemasukan, di Beranda dan Analisis.'],
  ] },
  { version: '64', date: '26 Sep 2026', title: 'Privasi dan hemat kuota', items: [
    ['🔒', 'Ikon mata di sebelah lonceng: sembunyikan semua nominal sekali ketuk.'],
    ['📝', 'Transaksi, utang, piutang, dan klaim yang disimpan tercatat di notifikasi.'],
    ['🔄', 'Hemat kuota: data disimpan di perangkat, hanya perubahan yang diunduh.'],
    ['⚡', 'Laporan, riwayat siklus, dan pindah tab tidak memakai kuota baca.'],
    ['✅', 'Riwayat siklus hanya menandai siklus yang punya transaksi sebagai siap ditutup.'],
    ['📌', 'Tempat belanja di Laporan tidak lagi tercampur kategori atau keterangan.'],
    ['📊', 'Kartu Pemasukan & Pengeluaran di Beranda lebih ringkas dan muat lebih banyak.'],
  ] },
  { version: '63', date: '26 Sep 2026', title: 'Lebih ringkas, lebih mulus', items: [
    ['📱', 'Geser antartab, misalnya di Laporan, kini mulus tanpa kedipan.'],
    ['🚀', 'Halaman yang sudah siap langsung tampil, tanpa layar memuat sesaat.'],
    ['🛠️', 'Tombol Urutkan, Rentang, dan Periode lebih ringkas dan proporsional.'],
  ] },
  { version: '62', date: '26 Sep 2026', title: 'Lebih halus, lebih kaca', items: [
    ['🌙', 'Pindah ke mode gelap tanpa kedipan terang.'],
    ['⚡', 'Dari tombol Tambah ke formulir transaksi tanpa jeda.'],
    ['💳', 'Menu Lainnya di Dompet membuka ke atas bila dekat bilah bawah.'],
    ['🎨', 'Ukuran teks dan tampilan SS (super kecil); teks S jadi bawaan.'],
    ['🧾', 'Subkategori anggaran dipilih lewat dropdown.'],
    ['🤝', 'Utang & Piutang serta Tujuan dana tampil baru bergaya kaca.'],
    ['📱', 'Info aplikasi di Pengaturan: versi dan apa yang baru.'],
  ] },
  { version: '61', date: '26 Sep 2026', title: 'Kendali akun penuh', items: [
    ['🧹', 'Reset semua data untuk mulai dari awal, akun tetap ada.'],
    ['🛡️', 'Hapus akun permanen beserta semua datanya.'],
    ['🔒', 'Lupa dan ganti password versi baru, lengkap dengan meter kekuatan.'],
    ['🗂️', 'Tambah kartu Beranda dalam 9 kategori dropdown dan pencarian.'],
  ] },
  { version: '60', date: '26 Sep 2026', title: 'Beranda makin kaya', items: [
    ['📊', '15 kartu Beranda baru, misalnya Rasio Menabung dan Belanja 7 Hari.'],
    ['📝', 'Pilihan jenis huruf: Bawaan, Inter, Google Sans, Plus Jakarta Sans.'],
    ['📌', 'Kategori tampil ringkas; ketuk untuk membuka subkategori.'],
    ['💰', 'Saldo Dompet dan Komposisi Aset selalu cocok dengan Aset bersih.'],
  ] },
  { version: '59', date: '26 Sep 2026', title: 'Anggaran dan kategori baru', items: [
    ['🎯', 'Satu anggaran bisa mencakup beberapa subkategori.'],
    ['🎉', 'Tampilan baru untuk Anggaran, Kategori, dan panduan awal.'],
    ['💎', 'Kartu kantong bergaya kaca.'],
    ['📈', 'Perkiraan return investasi di Insight dibuat realistis.'],
  ] },
  { version: '56–58', date: '26 Sep 2026', title: 'Riwayat dan bantuan', items: [
    ['📉', 'Riwayat siklus dengan ringkasan setiap bulan gaji.'],
    ['🧭', 'Kontrol keuangan lebih fleksibel, lengkap dengan penjelasan.'],
    ['❓', 'Menu Tanya Jawab: istilah, fungsi menu, dan cara pakai.'],
  ] },
  { version: '52–55', date: '25 Sep 2026', title: 'Dompet ringkas', items: [
    ['👛', 'Tampilan Dompet Ringkas dengan warna kartu tiap dompet.'],
    ['📥', 'Kartu Pemasukan & Pengeluaran di Beranda.'],
    ['⌨️', 'Lembar isian naik di atas keyboard HP.'],
    ['🔁', 'Jadwal rutin tetap di tanggal yang sama tiap bulan.'],
  ] },
  { version: '42–51', date: '25 Sep 2026', title: 'Kantong dan formulir baru', items: [
    ['🪙', 'Kantong tabungan yang mengelompokkan beberapa dompet.'],
    ['🏦', 'Logo bank, e-money, dan kartu; cari emoji di semua pilihan ikon.'],
    ['💸', 'Formulir transaksi dan pop-up yang baru.'],
    ['✅', 'Audit menyeluruh: satu rumus Uang bebas di semua halaman.'],
  ] },
  { version: '25–41', date: '25 Sep 2026', title: 'Insight hadir', items: [
    ['💡', 'Insight: skor kesehatan, temuan, dan rencana aksi dari datamu sendiri.'],
    ['🎁', 'Wish list untuk barang impian.'],
    ['📱', 'Buka kunci dengan sidik jari atau wajah.'],
    ['🚀', 'Layar pembuka baru dan notifikasi mengambang.'],
  ] },
];
