export type WithId = { id: string };
export type Wallet = WithId & { name: string; type: 'bank'|'cash'|'ewallet'|'savings'|'credit'|'investment'|'other'; group?: 'operational'|'savings'|'investment'; openingBalance: number; cachedBalance: number; purpose: string; isReserved: boolean; isSpendable: boolean; includeInNetWorth: boolean; isArchived: boolean; icon?: string; color?: string; cardStyle?: 'soft'|'solid'; displayOrder?: number; canPay?: boolean; canReceive?: boolean; canTransferOut?: boolean; canTransferIn?: boolean; contextNotes?:ContextNote[]; institution?: string; createdAt?: unknown; updatedAt?: unknown };
export type Category = WithId & { name: string; type: 'expense'|'income'|'savings'|'debt'|'receivable'|'reimbursement'; parentId: string|null; icon: string; color?: string; sortOrder: number; isArchived: boolean; templateKey?: string; templateVersion?: number; createdAt?: unknown; updatedAt?: unknown };
export type Budget = WithId & { name: string; categoryId: string; /** First chosen subcategory (null = the whole category). */ subcategoryId: string|null; /** Every chosen subcategory when the budget covers only part of the category. */ subcategoryIds?: string[]; amount: number; classification: 'living'|'fixed'|'sinking'|'savings'; cycleType: 'salary'|'calendar'|'custom'|'weekly'; /** Day of month for custom, or weekday for weekly (1 = Senin … 7 = Minggu). */ cycleStartDay?:number; warningPercent?:number; notes?:string; sortOrder?:number; rolloverEnabled: boolean; rolloverCarry?: number; lastSettledStart?: string; createdDate?: string; active: boolean; createdAt?: unknown; updatedAt?: unknown };
export type TxType = 'expense'|'income'|'transfer'|'adjustment'|'borrowing'|'debt_payment'|'claim_advance'|'claim_payment'|'claim_writeoff'|'receivable_issue'|'receivable_payment'|'fund_contribution';
export type SplitLine = { categoryId:string; subcategoryId:string|null; amount:number };
/** `splitBillId`: the transaction belongs to a Split Bill. `ownShare` (the bill's cash payment): the part that is the
 * person's own spending; the rest was paid for others and is owed back (Piutang). `ownSplits`: that own part by category. */
export type LedgerTx = WithId & { splitBillId?: string|null; ownShare?: number|null; ownSplits?: SplitLine[]; type: TxType; amount: number; date: string; time?: string; walletId: string; destinationWalletId: string|null; categoryId: string|null; subcategoryId: string|null; merchant: string; description: string; notes: string; tags: string[]; claimId: string|null; debtId: string|null; receivableId: string|null; fundId: string|null; recurringTransactionId: string|null; draftId: string|null; adjustmentDirection: 'in'|'out'; splits?:SplitLine[]; transferFee?:number; transferFeeCategoryId?:string|null; reconciliationReason?:string; plannedId?:string|null; createdAt?: unknown; updatedAt?: unknown };
export type Claim = WithId & { name: string; amount: number; remainingAmount: number; sourceWalletId: string; submissionDate: string; expectedPaymentDate: string; paidDate: string; status: 'draft'|'submitted'|'waiting'|'approved'|'paid'|'rejected'; description: string; notes: string; contextNotes?:ContextNote[]; attachmentPath?: string; createdAt?: unknown; updatedAt?: unknown };
export type ContextNote = { id:string; text:string; createdAt:string; updatedAt?:string; pinned?:boolean };
export type ManualPayment = { id: string; amount: number; date: string; note?: string };
/** "Perbarui saldo" on a debt or receivable: the amount still owed was changed to match reality (interest, a discount, a correction). No wallet moves. */
export type BalanceUpdate = { id: string; date: string; from: number; to: number; note?: string; at: string; /** How it was entered: added, reduced, or set to an amount. */ mode?: 'add'|'reduce'|'set'; /** Added with money moving: the wallet and the transaction that moved it. */ walletId?: string; transactionId?: string };
/** Piutang/Utang created by a Split Bill carry `sourceType: 'split_bill'` and the bill, person and payment they come from. */
export type SplitLink = { sourceType?: 'split_bill'; splitBillId?: string; participantId?: string; transactionId?: string };
export type Receivable = WithId & SplitLink & { manualPayments?: ManualPayment[]; balanceUpdates?: BalanceUpdate[]; person: string; description: string; originalAmount: number; remainingAmount: number; sourceWalletId: string; date: string; dueDate: string; status: 'open'|'partial'|'paid'; contextNotes?:ContextNote[]; createdAt?: unknown; updatedAt?: unknown };
export type Debt = WithId & SplitLink & { manualPayments?: ManualPayment[]; balanceUpdates?: BalanceUpdate[]; name: string; provider: string; originalAmount: number; outstandingAmount: number; dueDate: string; interestRate: number; installmentAmount: number; notes: string; contextNotes?:ContextNote[]; status: 'open'|'paid'; createdAt?: unknown; updatedAt?: unknown };
/** Tujuan dana. With `walletIds` it is a kantong whose amount is those wallets' balance; `kind: 'emergency'` marks the emergency fund. */
export type Fund = WithId & { kind?: 'emergency'|'goal'; icon?: string; /** Kantong: wallets grouped by this fund; its amount is their total balance. */ walletIds?: string[]; isArchived?: boolean; name: string; targetAmount: number; currentAmount: number; monthlyContribution: number; targetDate: string; linkedWalletId: string; notes: string; contextNotes?:ContextNote[]; createdAt?: unknown; updatedAt?: unknown };
export type Recurring = WithId & { name: string; type: TxType; amount: number; walletId: string; destinationWalletId: string|null; categoryId: string|null; frequency: 'weekly'|'monthly'|'yearly'; /** Intended day of the month (1–31) for monthly/yearly schedules. */ anchorDay?: number; nextDate: string; active: boolean; mode: 'reminder'|'draft'|'inbox'|'auto'; createdAt?: unknown; updatedAt?: unknown };
export type Draft = WithId & { recurringId:string; plannedDate:string; type:TxType; amount:number; walletId:string; destinationWalletId:string|null; categoryId:string|null; name:string; status:'pending'|'posted'|'dismissed'; mode?:'inbox'|'draft'|'auto'; createdAt?:unknown; updatedAt?:unknown };
export type PlannedTransaction = WithId & { title:string; type:'expense'|'income'; amount:number; date:string; walletId:string|null; categoryId:string|null; subcategoryId:string|null; notes:string; committed:boolean; status:'planned'|'posted'|'cancelled'; postedTransactionId?:string|null; createdAt?:unknown;updatedAt?:unknown };
export type CategorizationRule = WithId & { name:string; priority:number; active:boolean; type?:TxType|''; merchantContains?:string; descriptionContains?:string; transactionNameContains?:string; amountMin?:number; amountMax?:number; walletId?:string; destinationWalletId?:string; categoryId?:string; subcategoryId?:string; tag?:string; setMerchant?:string; suggestedWalletId?:string; recurringCandidate?:boolean; createdAt?:unknown;updatedAt?:unknown };
export type FinancialNote = WithId & { title:string; description:string; date:string; amount?:number; categoryId?:string|null; transactionId?:string|null; cycleStart?:string|null; createdAt?:unknown;updatedAt?:unknown };
export type CycleSnapshot = WithId & { startDate:string; endDate:string; openingAssets:number; closingAssets:number; openingNetWorth:number; closingNetWorth:number; income:number; expense:number; cashFlow:number; budgetTotal:number; budgetSpent:number; budgetRemaining:number; reservedMoney:number; debtOutstanding:number; claimsOutstanding:number; savings:number; debtPaid:number; claimReceived:number; budgetDefinitions?:Budget[]; notes?:string; updatedAt?:unknown;createdAt?:unknown };
export type QuickAction = { id:string; label:string; kind:'expense'|'income'|'transfer'|'claims'|'receivables'|'debts'; amount?:number; description?:string; categoryId?:string; subcategoryId?:string; walletId?:string; icon?:'default'|'coffee'|'food'|'shopping'|'transport'|'bill'|'wallet'|'star' };
export type TimeZone = 'Asia/Jakarta'|'Asia/Makassar'|'Asia/Jayapura'|'UTC';
export type ThemePreset = 'default'|'peach'|'blush'|'lavender'|'sage'|'ocean'|'rose'|'monochrome';
export type ColorMode = 'system'|'light'|'dark';
export type Profile = { uid: string; username: string; email: string; displayName: string; currency: 'IDR'; salaryCycleStartDay: number; monthlySalary: number; onboardingDone: boolean; hideReserved: boolean; theme: 'light'|'dark'; themePreset?:ThemePreset; colorMode?:ColorMode; accentColor?:string; density?:'xxs'|'xs'|'compact'|'comfortable'|'large';fontSize?:'xxs'|'xs'|'s'|'m'|'l';/** 2 once the text-size default moved from M to S (v62). */ appearanceDefaults?:number;/** Typeface: the default pair (DM Sans + Manrope) or one of the extra Google fonts. */ fontFamily?:'default'|'inter'|'google'|'jakarta';pinHash?:string|null;pinSalt?:string|null;pinLockAfter?:number;reminders?:{balanceEnabled:boolean;times:string[];billsEnabled:boolean;billTime:string;billDaysBefore:number;budgetAlerts?:boolean}; timeZone?:TimeZone; defaultExpenseWalletId?:string; defaultIncomeWalletId?:string; salaryIncomeCategoryId?:string; budgetWarningPercent?:number; dashboardWidgets: string[]; /** Uang tersedia: money always kept aside, and how far ahead unpaid bills count (default: until payday). */ freeMoneyBuffer?: number; commitmentHorizon?: 'week'|'cycle'|'month'; /** Layout format; below 2 the new Pemasukan & Pengeluaran card is added under Saldo Dompet. */ dashboardWidgetsVersion?: number; dashboardWidgetConfig?:Record<string,{period?:import('./period').PeriodPreset;categoryId?:string}>; primaryMetric?:string; dashboardPeriod?:import('./period').PeriodPreset; dashboardCustom?:import('./period').DateRange; analyticsPeriod?:import('./period').PeriodPreset; analyticsCustom?:import('./period').DateRange; analyticsGranularity?:import('./period').Granularity; quickActions?:QuickAction[]; realisticMode?:boolean; largeTransactionThreshold?:number; excludeCommittedFromAvailable?:boolean; /** Count unpaid receivables and office claims in Aset bersih (off by default). */ netWorthIncludesReceivables?:boolean; /** Personal settings that tune Insight (risk profile, targets, household…). */ insightProfile?:Partial<import('./insight-profile').InsightProfile>; /** Insight page: section order, hidden sections and pinned advice. */ insightLayout?:{order?:string[];hidden?:string[];pinned?:string[]}; defaultCategoryTemplateVersion?:number; /** When a device last deleted documents, per collection, so other devices drop them from their copy (lib/sync.ts). */ syncMarks?:Record<string,unknown>; createdAt?: unknown; updatedAt?: unknown; lastLoginAt?: unknown };
/** Something the user wants to buy: money can be set aside for it (an earmark, not a wallet move). */
export type WishItem = WithId & { name: string; emoji: string; color?: string; price: number; saved: number; monthly?: number; priority: 1|2|3; link?: string; notes?: string; targetDate?: string; status: 'active'|'bought'|'dropped'; addedDate: string; boughtDate?: string; sortOrder?: number; history?: { date: string; amount: number }[]; createdAt?: unknown; updatedAt?: unknown };
export type Data = { wishlist: WishItem[]; wallets: Wallet[]; categories: Category[]; budgets: Budget[]; transactions: LedgerTx[]; claims: Claim[]; receivables: Receivable[]; debts: Debt[]; funds: Fund[]; recurring: Recurring[]; drafts: Draft[]; plannedTransactions:PlannedTransaction[]; categorizationRules:CategorizationRule[]; financialNotes:FinancialNote[]; cycleSnapshots:CycleSnapshot[] };
export const emptyData: Data = { wishlist: [], wallets: [], categories: [], budgets: [], transactions: [], claims: [], receivables: [], debts: [], funds: [], recurring: [], drafts: [],plannedTransactions:[],categorizationRules:[],financialNotes:[],cycleSnapshots:[] };

/** Split Bill: how a shared bill is divided. Money itself stays in the ledger (transactions, Piutang, Utang); this is the allocation and its context. */
export type SplitMethod = 'equal'|'items'|'amount'|'percent';
export type SplitDistribution = 'proportional'|'equal'|'custom';
/** `amount`: the person's part of the subtotal (Nominal manual). `percent`: basis points, 10000 = 100% (Persentase). */
export type SplitParticipant = { id: string; name: string; personId?: string|null; isMe?: boolean; emoji?: string; amount?: number; percent?: number; receivableId?: string|null; debtId?: string|null };
/** Who had an item: shared equally by `people`, `units` of `qty` per person, or `custom` Rupiah amounts. */
export type SplitItem = { id: string; name: string; qty: number; price: number; discount?: number; categoryId?: string|null; subcategoryId?: string|null; assign: 'shared'|'units'|'custom'; people: string[]; units?: Record<string, number>; custom?: Record<string, number> };
export type SplitExtraKind = 'tax'|'service'|'discount'|'delivery'|'admin'|'tip'|'rounding'|'other'|'shared';
/** Tax, service, discount, fees, tip, rounding or a shared cost. `amount` is positive except for rounding; a discount is subtracted.
 * `percent` (with items only) recalculates the amount from the subtotal. `people` empty = everyone. */
export type SplitExtra = { id: string; kind: SplitExtraKind; label: string; amount: number; percent?: number; distribution: SplitDistribution; people?: string[]; custom?: Record<string, number>; categoryId?: string|null; subcategoryId?: string|null };
/** A payment between two other people (the payer is someone else): it moves none of the user's money, so it lives on the bill. */
export type SplitPayment = { id: string; participantId: string; amount: number; date: string; note?: string; createdAt: string };
export type SplitBill = WithId & { title: string; merchant: string; date: string; time?: string; dueDate?: string; status: 'draft'|'active'|'cancelled'; payer: 'me'|'other'; payerId: string; walletId: string; transactionId: string; fromTransaction?: boolean; categoryId: string|null; subcategoryId: string|null; total: number; method: SplitMethod; participants: SplitParticipant[]; items: SplitItem[]; extras: SplitExtra[]; payments: SplitPayment[]; shares?: Record<string, number>; myShare?: number; groupId?: string|null; receiptPath?: string; notes: string; contextNotes?: ContextNote[]; cancelledAt?: string; createdAt?: unknown; updatedAt?: unknown };
/** Saved people and groups for Split Bill (they don't need an account). */
export type SplitPerson = WithId & { name: string; nickname?: string; emoji?: string; notes?: string; lastUsed?: string; createdAt?: unknown; updatedAt?: unknown };
export type SplitGroup = WithId & { name: string; emoji?: string; memberIds: string[]; createdAt?: unknown; updatedAt?: unknown };
