/**
 * Insight V2.5 held-out scenarios: written after the engine was built and before it ever ran on them.
 * First run frozen in bench/insight/heldout-first.json; later fixes do not change that record.
 */
import { addDays } from './scenarios.mjs';

export const heldout = [
  { id: 'h01-fuel-price', tags: ['ticket'], options: { seed: 31, change: (h, ci, cur) => cur && h.key === 'fuel' ? { ticket: 1.4 } : {} }, expectAny: ['spending:category:trans', 'spending:subcategory:trans-fuel', 'merchant:pertamina'], mech: 'ticket' },
  { id: 'h02-ride-often', tags: ['frequency'], options: { seed: 32, change: (h, ci, cur) => cur && h.key === 'ride' ? { perCycle: 3 } : {} }, expectAny: ['spending:category:trans', 'spending:subcategory:trans-ride', 'merchant:gojek'], mech: 'frequency' },
  { id: 'h03-groceries-down', tags: ['positive'], options: { seed: 33, change: (h, ci, cur) => cur && h.key === 'groc' ? { perCycle: 0 } : {} }, expectAny: ['spending:category:shop', 'spending:subcategory:shop-groc', 'merchant:indomaret'], positive: true },
  { id: 'h04-fresh-claims', tags: ['claims'], options: { seed: 34, build: ({ data, today }) => { data.claims.push({ id: 'k1', name: 'Makan klien', amount: 350_000, remainingAmount: 350_000, sourceWalletId: 'bca', submissionDate: addDays(today, -4), expectedPaymentDate: addDays(today, 10), paidDate: '', status: 'submitted', description: '', notes: '' }); } }, expect: ['claims:outstanding'], forbid: [/^claims:aging/] },
  { id: 'h05-new-loan', tags: ['debt'], options: { seed: 35, build: ({ data, cycles, tx }) => { data.debts.push({ id: 'd9', name: 'Pinjaman teman', provider: '', originalAmount: 3_000_000, outstandingAmount: 3_000_000, dueDate: '', interestRate: 0, installmentAmount: 0, notes: '', status: 'open' }); data.debts.push({ id: 'd8', name: 'Paylater', provider: '', originalAmount: 2_000_000, outstandingAmount: 2_000_000, dueDate: '', interestRate: 0, installmentAmount: 0, notes: '', status: 'open' }); data.transactions.push(tx('borrowing', 3_000_000, addDays(cycles[5].start, 3), { debtId: 'd9' })); } }, expect: ['debt:trajectory'], type: 'debt_up' },
  { id: 'h06-stable-day1', tags: ['false-alarm'], options: { seed: 36, salaryDay: 1, today: '2026-10-19' }, expect: [], forbid: [/^spending:|^merchant:|^cashflow:spending-pace/] },
  { id: 'h07-stable-day10', tags: ['false-alarm'], options: { seed: 999, salaryDay: 10, today: '2026-10-28' }, expect: [], forbid: [/^spending:|^merchant:|^cashflow:spending-pace/] },
  { id: 'h08-surge-uncategorized', tags: ['data-quality', 'frequency'], options: { seed: 38, uncategorized: .1, change: (h, ci, cur) => cur && h.key === 'grabfood' ? { perCycle: 3 } : {} }, expectAny: ['spending:category:food', 'spending:subcategory:food-delivery'], caveat: /belum memiliki kategori/ },
  { id: 'h09-internet-cheaper', tags: ['recurring'], options: { seed: 39, build: ({ data, cycles }) => { for (const t of data.transactions) if (t.recurringTransactionId === 'r-net' && t.date >= cycles[5].start) t.amount = 300_000; } }, expect: ['recurring:drift:r:r-net'], tone: 'positive' },
  { id: 'h10-one-person', tags: ['receivable'], options: { seed: 40, build: ({ data, today }) => { data.receivables.push({ id: 'q1', person: 'Dodi', description: '', originalAmount: 2_000_000, remainingAmount: 2_000_000, sourceWalletId: 'bca', date: addDays(today, -10), dueDate: '', status: 'open' }, { id: 'q2', person: 'Nisa', description: '', originalAmount: 200_000, remainingAmount: 200_000, sourceWalletId: 'bca', date: addDays(today, -6), dueDate: '', status: 'open' }); } }, expect: ['receivable:outstanding', 'receivable:concentration'] },
  { id: 'h11-warteg-feast', tags: ['anomaly'], options: { seed: 41, build: ({ data, today, tx }) => { data.transactions.push(tx('expense', 450_000, addDays(today, -1), { categoryId: 'food', subcategoryId: 'food-warteg', merchant: 'Warteg Bahari', id: 'w1', time: '13:00' })); } }, expect: ['behavior:unusual:w1'] },
  { id: 'h12-two-cycles-surge', tags: ['learning', 'confidence'], options: { seed: 42, cycles: 2, change: (h, ci, cur) => cur && h.key === 'grabfood' ? { perCycle: 3 } : {} }, expectAny: ['spending:category:food', 'spending:subcategory:food-delivery', 'merchant:grabfood'], notHigh: true },
];
