'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { Eye, EyeOff, LockKeyhole, Sparkles, WalletCards } from 'lucide-react';
import { useApp } from '@/components/app-provider';
import { Field, Input } from '@/components/fields';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent } from '@/components/ui/dialog';
import { forgotPassword, friendlyError, login } from '@/lib/auth';
export default function LoginPage(){const {user,loading,ready}=useApp();const router=useRouter();const [identifier,setIdentifier]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[remember,setRemember]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[resetOpen,setResetOpen]=useState(false),[resetDone,setResetDone]=useState(false);
 useEffect(()=>{if(user)router.replace('/');},[user,router]);
 async function submit(e:FormEvent){e.preventDefault();if(!identifier.trim()){setError('Masukkan username.');return;}if(!password){setError('Masukkan password.');return;}setBusy(true);setError('');try{await login(identifier,password,remember);router.replace('/');}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
 return <main className="login-shell"><div className="login-art"><div className="brand"><span className="brand-mark"><Sparkles size={21}/></span><strong>dompet ajaib<span className="brand-dot">.</span></strong></div><div className="login-copy"><span className="eyebrow">PERSONAL FINANCE, MADE CLEAR</span><h1>Uangmu,<br/><em>lebih jelas.</em></h1><p>Lihat mana yang sudah punya tujuan, mana yang bebas dipakai, dan ke mana setiap rupiah pergi.</p></div><div className="login-statement"><WalletCards size={23}/><span>Saldo besar belum tentu uang bebas.</span></div></div><div className="login-panel"><div className="login-card"><div className="mobile-brand brand"><span className="brand-mark"><Sparkles size={20}/></span><strong>dompet ajaib<span className="brand-dot">.</span></strong></div><div className="login-icon"><LockKeyhole size={23}/></div><p className="eyebrow ink">SELAMAT DATANG</p><h2>Masuk ke akunmu</h2><p className="muted">Catatan keuanganmu tersedia setelah masuk.</p>{!ready&&<p className="form-error">Konfigurasi Firebase belum diisi. Lihat README untuk menghubungkan proyek.</p>}
 <form onSubmit={submit}><Field label="Username atau email"><Input autoComplete="username" value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="contoh: rama"/></Field><Field label="Password"><div className="password-wrap"><Input autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} type={show?'text':'password'} placeholder="Masukkan password"/><button type="button" className="password-toggle" aria-label={show?'Sembunyikan password':'Tampilkan password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></Field><div className="form-meta"><label className="check-row"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/> Ingat saya</label><button type="button" className="link-button" onClick={()=>setResetOpen(true)}>Lupa password?</button></div>{error&&<p role="alert" className="form-error">{error}</p>}<Button className="full" disabled={busy||loading||!ready}>{busy?'Memeriksa akun…':'Masuk'}</Button></form><p className="login-foot">Data setiap akun tersimpan terpisah dan dilindungi oleh aturan akses Firebase.</p></div></div><Dialog open={resetOpen} onOpenChange={setResetOpen}><DialogContent title="Atur ulang password">{resetDone?<p>Jika akun tersedia, instruksi reset password akan dikirim.</p>:<form onSubmit={async e=>{e.preventDefault();await forgotPassword(identifier);setResetDone(true);}}><Field label="Username atau email"><Input required value={identifier} onChange={e=>setIdentifier(e.target.value)}/></Field><Button className="full">Kirim instruksi</Button></form>}</DialogContent></Dialog></main>;
}
