/**
 * General Language Intelligence v1.0 — development set (state: fixtures-v33state.mjs, today 2026-10-15).
 *
 *   A canonical   sentences already written in full words: the language layer must change nothing that matters.
 *   B variants    the same meanings typed the way people chat: abbreviations, unseen vowel-dropped forms, typos,
 *                 mobile typing (glued amounts, "mkn:25k"), fillers, command words, emoji, companions.
 *   C adversarial names that look like shorthand ("SRPN Coffee", "Mkn", "MKN Store", "BBM Cafe", "Ceban Cafe"),
 *                 real words that look like shortened money words ("kota", "krim", "kamus"), direction words.
 *
 * `keep` lists words that must reach the grammar untouched (a change to one is a FALSE NORMALIZATION).
 * `cat` is the expected category or subcategory id. No sentence → answer pair is stored anywhere in the engine.
 */
export const cases = [
  // ——— A: canonical ———
  { id: 'a1', group: 'A', text: 'makan 25rb pakai jago', expect: { kind: 'expense', amount: 25000, description: 'Makan', wallet: 'jago', cat: 'food' } },
  { id: 'a2', group: 'A', text: 'sarapan bubur 15rb cash', expect: { kind: 'expense', amount: 15000, wallet: 'cash', cat: 'food' } },
  { id: 'a3', group: 'A', text: 'parkir 5rb cash', expect: { kind: 'expense', amount: 5000, description: 'Parkir', wallet: 'cash', cat: 'park' } },
  { id: 'a4', group: 'A', text: 'bensin 80rb pakai jago', expect: { kind: 'expense', amount: 80000, description: 'Bensin', wallet: 'jago', cat: 'fuel' } },
  { id: 'a5', group: 'A', text: 'belanja bulanan 450rb mandiri', expect: { kind: 'expense', amount: 450000, wallet: 'mandiri' } },
  { id: 'a6', group: 'A', text: 'kemarin makan 30rb jago', expect: { kind: 'expense', amount: 30000, wallet: 'jago', date: '2026-10-14', cat: 'food' } },
  { id: 'a7', group: 'A', text: 'bayar listrik 200rb mandiri', expect: { kind: 'expense', amount: 200000, wallet: 'mandiri', cat: 'bills' } },
  { id: 'a8', group: 'A', text: 'gaji masuk 6,3jt jenius', expect: { kind: 'income', amount: 6300000, wallet: 'jenius', cat: 'salary' } },
  { id: 'a9', group: 'A', text: 'transfer 500rb dari jago ke mandiri', expect: { kind: 'transfer', amount: 500000, wallet: 'jago', to: 'mandiri' } },
  { id: 'a10', group: 'A', text: 'aku utang 100rb ke aldi', expect: { kind: 'debt_new', amount: 100000, person: 'Aldi' } },
  { id: 'a11', group: 'A', text: 'aldi pinjam 100rb', expect: { kind: 'receivable_new', amount: 100000, person: 'Aldi' } },
  { id: 'a12', group: 'A', text: 'jajan 15rb krom', expect: { kind: 'expense', amount: 15000, description: 'Jajan', wallet: 'krom' } },
  { id: 'a13', group: 'A', text: 'beli es krim di mixue 16rb gopay', expect: { kind: 'expense', amount: 16000, description: 'Es Krim', merchant: 'Mixue', wallet: 'gopay' } },
  { id: 'a14', group: 'A', text: 'sewa sepeda di taman kota 12rb cash', expect: { kind: 'expense', amount: 12000, merchant: 'Taman Kota', wallet: 'cash' } },
  { id: 'a15', group: 'A', text: 'beli kamus 85rb jago', expect: { kind: 'expense', amount: 85000, description: 'Kamus', wallet: 'jago' } },
  { id: 'a16', group: 'A', text: 'tadi ngopi 20rb krom', expect: { kind: 'expense', amount: 20000, description: 'Ngopi', wallet: 'krom', cat: 'drink' } },
  { id: 'a17', group: 'A', text: 'top up gopay 100rb dari jago', expect: { kind: 'transfer', amount: 100000, wallet: 'jago', to: 'gopay' } },
  { id: 'a18', group: 'A', text: 'tiket kereta 50rb bri', expect: { kind: 'expense', amount: 50000, wallet: 'bri', cat: 'trans' } },
  { id: 'a19', group: 'A', text: 'bayar cicilan motor 900rb mandiri', expect: { amount: 900000, wallet: 'mandiri' } },
  { id: 'a20', group: 'A', text: 'pulsa 50rb gopay', expect: { kind: 'expense', amount: 50000, wallet: 'gopay' } },

  // ——— B: variants (sarapan / makan / parkir / bensin / belanja families first) ———
  { id: 'b1', group: 'B', text: 'srpn 20k jago', expect: { amount: 20000, description: 'Sarapan', wallet: 'jago', cat: 'food' } },
  { id: 'b2', group: 'B', text: 'srpan 20k jago', expect: { amount: 20000, description: 'Sarapan', wallet: 'jago', cat: 'food' } },
  { id: 'b3', group: 'B', text: 'srapn 22rb cash', expect: { amount: 22000, description: 'Sarapan', wallet: 'cash', cat: 'food' } },
  { id: 'b4', group: 'B', text: 'sarapn 15k gopay', expect: { amount: 15000, description: 'Sarapan', wallet: 'gopay', cat: 'food' } },
  { id: 'b5', group: 'B', text: 'sarpan 18k krom', expect: { amount: 18000, description: 'Sarapan', wallet: 'krom', cat: 'food' } },
  { id: 'b6', group: 'B', text: 'mkn 25k jago', expect: { amount: 25000, description: 'Makan', wallet: 'jago', cat: 'food' } },
  { id: 'b7', group: 'B', text: 'makn 25k jago', expect: { amount: 25000, description: 'Makan', wallet: 'jago', cat: 'food' } },
  { id: 'b8', group: 'B', text: 'makannn 30k cash', expect: { amount: 30000, description: 'Makan', wallet: 'cash', cat: 'food' } },
  { id: 'b9', group: 'B', text: 'prkr 5k cash', expect: { amount: 5000, description: 'Parkir', wallet: 'cash', cat: 'park' } },
  { id: 'b10', group: 'B', text: 'prkir 5rb cash', expect: { amount: 5000, description: 'Parkir', wallet: 'cash', cat: 'park' } },
  { id: 'b11', group: 'B', text: 'bnsn 80k jago', expect: { amount: 80000, description: 'Bensin', wallet: 'jago', cat: 'fuel' } },
  { id: 'b12', group: 'B', text: 'bensn 50rb jago', expect: { amount: 50000, description: 'Bensin', wallet: 'jago', cat: 'fuel' } },
  { id: 'b13', group: 'B', text: 'blnja 120k mandiri', expect: { amount: 120000, description: 'Belanja', wallet: 'mandiri', cat: 'shop' } },
  { id: 'b14', group: 'B', text: 'jjn 15k krom', expect: { amount: 15000, description: 'Jajan', wallet: 'krom' } },
  { id: 'b15', group: 'B', text: 'kmrn mkn 30k jago', expect: { amount: 30000, description: 'Makan', wallet: 'jago', date: '2026-10-14' } },
  { id: 'b16', group: 'B', text: 'td ngopi 20k krom', expect: { amount: 20000, description: 'Ngopi', wallet: 'krom' } },
  { id: 'b17', group: 'B', text: 'byr lstrk 200k mandiri', expect: { amount: 200000, wallet: 'mandiri', cat: 'bills' } },
  { id: 'b18', group: 'B', text: 'byr tghn 150k mandiri', expect: { amount: 150000, description: 'Tagihan', wallet: 'mandiri', cat: 'bills' } },
  { id: 'b19', group: 'B', text: 'gaji msk 6,3jt jenius', expect: { kind: 'income', amount: 6300000, wallet: 'jenius', cat: 'salary' } },
  { id: 'b20', group: 'B', text: 'tf 500k jago ke mandiri', expect: { kind: 'transfer', amount: 500000, wallet: 'jago', to: 'mandiri' } },
  { id: 'b21', group: 'B', text: 'trnsfr 500k dr jago ke mandiri', expect: { kind: 'transfer', amount: 500000, wallet: 'jago', to: 'mandiri' } },
  { id: 'b22', group: 'B', text: 'transferin 500rb ke mandiri dr jago', expect: { kind: 'transfer', amount: 500000, wallet: 'jago', to: 'mandiri' } },
  { id: 'b23', group: 'B', text: 'gue ngutang 100k ke aldi', expect: { kind: 'debt_new', amount: 100000, person: 'Aldi' } },
  { id: 'b24', group: 'B', text: 'aldi ngutang 100k', expect: { kind: 'receivable_new', amount: 100000, person: 'Aldi' } },
  { id: 'b25', group: 'B', text: 'topup gopay 100k dr jago', expect: { kind: 'transfer', amount: 100000, wallet: 'jago', to: 'gopay' } },
  { id: 'b26', group: 'B', text: 'mkn:25k jago', expect: { amount: 25000, description: 'Makan', wallet: 'jago' } },
  { id: 'b27', group: 'B', text: 'makan, 25k jago', expect: { amount: 25000, description: 'Makan', wallet: 'jago' } },
  { id: 'b28', group: 'B', text: 'makan25k jago', expect: { amount: 25000, description: 'Makan', wallet: 'jago', cat: 'food' } },
  { id: 'b29', group: 'B', text: 'makan 25k jago wkwk', expect: { amount: 25000, description: 'Makan', wallet: 'jago' } },
  { id: 'b30', group: 'B', text: 'catetin makan 25k jago', expect: { amount: 25000, description: 'Makan', wallet: 'jago' } },
  { id: 'b31', group: 'B', text: 'tolong catat bensin 80k jago', expect: { amount: 80000, description: 'Bensin', wallet: 'jago' } },
  { id: 'b32', group: 'B', text: 'ngopi 22k ama temen', expect: { amount: 22000, description: 'Ngopi' } },
  { id: 'b33', group: 'B', text: 'makan 25k 😋 jago', expect: { amount: 25000, description: 'Makan', wallet: 'jago' } },
  { id: 'b34', group: 'B', text: 'pesen gofood 45k gopay', expect: { amount: 45000, wallet: 'gopay', notDescription: 'Pesen Gofood' } },
  { id: 'b35', group: 'B', text: 'plng naik ojek 20k gopay', expect: { amount: 20000, wallet: 'gopay', cat: 'trans' } },
  { id: 'b36', group: 'B', text: 'kmrn srpn 22rb trus prkr 5k', expect: { actions: [{ amount: 22000, description: 'Sarapan', date: '2026-10-14' }, { amount: 5000, description: 'Parkir', date: '2026-10-14' }] } },
  { id: 'b37', group: 'B', text: 'budget mkn 1,5jt', expect: { kind: 'budget', amount: 1500000 } },
  { id: 'b38', group: 'B', text: 'nabung 300k buat kuliah', expect: { amount: 300000 } },
  { id: 'b39', group: 'B', text: 'rencana beli hp 3jt bulan dpn', expect: { kind: 'plan_new', amount: 3000000, date: '2026-11-15' } },
  { id: 'b40', group: 'B', text: 'tkt kreta 50k bri', expect: { amount: 50000, wallet: 'bri', cat: 'trans' } },

  // ——— C: adversarial ———
  { id: 'c1', group: 'C', text: 'makan di SRPN Coffee 30k jago', keep: ['srpn'], expect: { amount: 30000, merchant: 'Srpn Coffee', wallet: 'jago' } },
  { id: 'c2', group: 'C', text: 'Mkn ngutang 50k', keep: ['mkn'], expect: { kind: 'receivable_new', amount: 50000, person: 'Mkn' } },
  { id: 'c3', group: 'C', text: 'belanja di MKN Store 100k jago', keep: ['mkn'], expect: { amount: 100000, merchant: 'Mkn Store', wallet: 'jago' } },
  { id: 'c4', group: 'C', text: 'ngopi di BBM Cafe 25k jago', keep: ['bbm'], expect: { amount: 25000, merchant: 'Bbm Cafe', wallet: 'jago', notCat: 'fuel' } },
  { id: 'c5', group: 'C', text: 'jajan di Jajan Cafe 20k', expect: { amount: 20000, merchant: 'Jajan Cafe', description: 'Jajan' } },
  { id: 'c6', group: 'C', text: 'Adi ngutang 50k', expect: { kind: 'receivable_new', amount: 50000, person: 'Adi' } },
  { id: 'c7', group: 'C', text: 'makan di Ceban Cafe 25k jago', keep: ['ceban'], expect: { amount: 25000, merchant: 'Ceban Cafe', wallet: 'jago' } },
  { id: 'c8', group: 'C', text: 'beli es krim 16rb gopay', keep: ['krim'], expect: { amount: 16000, description: 'Es Krim' } },
  { id: 'c9', group: 'C', text: 'parkir di taman kota 5rb', keep: ['kota'], expect: { amount: 5000, merchant: 'Taman Kota' } },
  { id: 'c10', group: 'C', text: 'beli kamus 85rb jago', keep: ['kamus'], expect: { amount: 85000, description: 'Kamus' } },
  { id: 'c11', group: 'C', text: 'beli tuna kaleng 30rb', keep: ['tuna'], expect: { amount: 30000 } },
  { id: 'c12', group: 'C', text: 'gaji ditransfer 5jt ke jenius', expect: { kind: 'income', amount: 5000000, wallet: 'jenius' } },
  { id: 'c13', group: 'C', text: 'gue talangin Aldi makan 40rb pake jago, catat dia utang ke gue', expect: { actions: [{ kind: 'receivable_new', amount: 40000, person: 'Aldi', wallet: 'jago' }] } },
  { id: 'c14', group: 'C', text: 'aldi balikin 50k', expect: { kind: 'receivable_payment', amount: 50000, person: 'Aldi' } },
  { id: 'c15', group: 'C', text: 'Rudi ngutangin gue 200k', keep: ['rudi'], expect: { kind: 'debt_new', amount: 200000, person: 'Rudi' } },
  { id: 'c16', group: 'C', text: 'ngopi di Kopi Klm 20k', keep: ['klm'], expect: { amount: 20000, merchant: 'Kopi Klm' } },
  { id: 'c17', group: 'C', text: 'beli seolah olah murah 10rb', expect: { amount: 10000 } },
  { id: 'c18', group: 'C', text: 'beli 2 kaos 100rb', expect: { amount: 100000 } },
  { id: 'c19', group: 'C', text: 'makan 25 ribu jago', expect: { amount: 25000, wallet: 'jago' } },
  { id: 'c20', group: 'C', text: 'MAKAN 25K JAGO', expect: { amount: 25000, wallet: 'jago', cat: 'food' } },
  { id: 'c21', group: 'C', text: 'sewa kosan 1,2jt mandiri', expect: { amount: 1200000, wallet: 'mandiri' } },
  { id: 'c22', group: 'C', text: 'beli 20 bakso', expect: { kind: 'expense' } },
  { id: 'c23', group: 'C', text: 'Plng Store 50k jago', keep: ['plng'], expect: { amount: 50000, wallet: 'jago' } },
  { id: 'c24', group: 'C', text: 'kopi kenangan 22k gopay', expect: { amount: 22000, wallet: 'gopay', cat: 'drink' } },
];
